### PR TITLE
Mtac2 1.0 is out!

### PR DESCRIPTION
**Pull request by beta-ziliani**
Officially releasing Mtac2 for Coq 8.7. It depends on coq-unicoq.

### CODE REVIEW

**Comment by Zimmi48** [comment]
@beta-ziliani Two questions/remarks:

- We test a branch of Mtac2 that we keep compatible with master in our CI. Is this useful to anyone (since you apparently all work on the 8.7 branch anyways)?
- Since 8.8, we distribute the Windows installers with a few plugins (in 8.8.0 only Bignums and in 8.8.1 we added Equations and Ltac2) because compiling/installing plugins is much harder on Windows (no good OPAM support). If Mtac2 1.0 is ported to Coq 8.8 very soon, we could include it in the Windows installer for Coq 8.8.2, and if it is ported to Coq master before October, it could be included in the installer for Coq 8.9.0.

**Comment by beta-ziliani** [comment]
The idea to have different branches for the different Coq versions is to be able to progress in our work without having the disturbance from changes in Coq's codebase.
Now, originally I thought we were not going to make great changes to the OCaml part of the code until a release, but I couldn't be more wrong. Now I'm trying to sync everything and I'm having a real hard time.
My goal is to reach a working 8.8 version soon, but it's not that easy (I found a bug in Coq, I think).

**Comment by Zimmi48** [comment]
>I found a bug in Coq, I think

Did you report it? You can ask it to be fixed instead of working around it ^^

**Comment by beta-ziliani** [comment]
Not yet, I want to obtain a self-contained example.

**Comment by beta-ziliani** [comment]
Hey @Zimmi48 I merged master with master-8.8. If you want to pack it up for the windows installer, be my guest. Do you need an opam package? Or is it ok just with the code? I will eventually do an opam package anyway. Note that for coq-unicoq you need the tag v1.3-8.8

**Comment by Zimmi48** [comment]
No need for an opam package but a tag would be great. Something like `1.0-8.8`?

**Comment by beta-ziliani** [comment]
that exists: https://github.com/Mtac2/Mtac2/releases/tag/v1.0.1-coq8.8

**Comment by Zimmi48** [comment]
great thanks :smile:

**Comment by Zimmi48** [comment]
See coq/coq#8305.

**Pull request merged**
