### PR TITLE
std++ 1.1 and Iris 3.1

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by mattam82** [comment]
Hmm, again the Coq opam package...

**Comment by RalfJung** [comment]
You mean, it is failing the CI?

**Comment by mattam82** [comment]
Yep

**Comment by RalfJung** [comment]
Yeah, the 8.7.0 package fails. Which is strange because it works here...

**Comment by RalfJung** [comment]
@gares how was the CI cache used here initially created? Any idea why it would not use the Coq 8.7.0 package from https://github.com/ocaml/opam-repository/blob/master/packages/coq/coq.8.7.0/ but another one? (And it clearly does, as one can see from both the download URL and the flags passed to `./configure`.)

**Comment by RalfJung** [comment]
I rebased this so hopefully we get some more debug information out of the CI.

**Comment by RalfJung** [comment]
I'm no wiser than before. My best guess is that the cache *somehow* contains a broken coq opam package. Notice the `./configure` call:
```
./configure "-configdir" "/home/travis/opam-root/4.05.0/lib/coq/config" "-mandir" "/home/travis/opam-root/4.05.0/man" "-prefix" "/home/travis/opam-root/4.05.0" "-usecamlp5" "-camlp5dir" "/home/travis/opam-root/4.05.0/lib/camlp5" "-coqide" "no" "-debug" 
```
and compare with <https://github.com/ocaml/opam-repository/blob/master/packages/coq/coq.8.7.0/opam>:
```
    "./configure"
    "-configdir" "%{lib}%/coq/config"
    "-prefix" prefix
    "-mandir" man
    "-docdir" doc
    "-libdir" "%{lib}%/coq"
    "-datadir" "%{share}%/coq"
    "-usecamlp5"
    "-camlp5dir" "%{lib}%/camlp5"
    "-coqide" "no"
```
In the CI, the `-debug` is extra and the `-libdir` and `-datadir` are missing.

@gares any idea what's going on? Can we just ignore CI?^^ Seems like it doesn't really work very well :/ and we'd like to tell people for the POPL Iris tutorial that they can just use the opam packages.

**Comment by RalfJung** [comment]
Yes, there is definitely something wrong with the cache. I got this to run on my own Travis, and it is using a newer Coq version, and not using a broken script. Let's see if adding `opam update` helps.

**Comment by mattam82** [comment]
opam update seems like the way to go! Thanks for investigating @RalfJung

**Comment by RalfJung** [comment]
Yay, the Linux build passed. :D  Mac is still in the queue.

**Pull request merged**
