### PR TITLE
[coq-poltac] Split build and installation phase

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**
Note: Not my package

### CODE REVIEW

**Comment by silene** [comment]
The failure is mind-boggling. I am starting to think this is a bug in Opam.

**Comment by silene** [comment]
And this is indeed a bug in Opam: https://github.com/ocaml/opam/issues/5447.

**Comment by LasseBlaauwbroek** [comment]
Mhm, good find. In the mean time what do you want to do with this PR? It seems clear that the problem is just with the linter. I can install the packages successfully locally. Any objection to merging?

**Comment by palmskog** [comment]
@LasseBlaauwbroek how about changing `src` to use a `.tar.gz` extension? Then it will work on opam 2.1, which I believe most users will be on for a while.

**Comment by LasseBlaauwbroek** [comment]
Okay, extension changed. I also changed the license to lgpl 2.1 only. CC @thery to check that this is as intended.

**Comment by thery** [comment]
From what I've seen, the only license that is in the files  was the one generated by coq_makefile: 
``` GNU Lesser General Public License Version 2.1```

**Comment by palmskog** [comment]
@thery the problem is the following: "GNU Lesser General Public License Version 2.1" is ambiguous without the "only" / "or later".

@LasseBlaauwbroek since there is no explicit statement "or later", I think we conservatively assume "only".

**Comment by thery** [comment]
@palmskog then you should fix the `coq_makefile` too

**Pull request merged**
