### PR TITLE
sync Coq opam packages with ocaml repository

### PR DESCRIPTION
**Pull request by RalfJung**
I usually use the packages here as template for the next release, assuming that this is where we keep the latest opam file (as the one in the repo is for experimental dune support). So let's make sure they are in sync.

### CODE REVIEW

**Comment by RalfJung** [comment]
CI is failing again, but somehow also failed to report that back to GH.

These are the exact configurations that we use for the opam package for Coq 8.12.0, so I am fairly confident the PR is fine. My guess is that the CI cache is somehow broken. Unfortunately, the log doesn't contain much information about what went wrong.

**Comment by RalfJung** [comment]
Hm okay it could also be something about Coq master that breaks the old opam? coqide.8.12+beta1 and coqide.8.12.dev work fine.

**Comment by RalfJung** [comment]
Indeed `coqide.dev` already fails to install without these changes:
```
#=== ERROR while installing coqide.dev ========================================#
Some files in /home/r/.opam/coq-test/.opam-switch/install/coqide.install couldn't be installed:
  - /home/r/.opam/coq-test/.opam-switch/build/coqide.dev/ide/coq_style.xml to /home/r/.opam/coq-test/share
  - /home/r/.opam/coq-test/.opam-switch/build/coqide.dev/ide/coq.png to /home/r/.opam/coq-test/share
  - /home/r/.opam/coq-test/.opam-switch/build/coqide.dev/ide/coq-ssreflect.lang to /home/r/.opam/coq-test/share
  - /home/r/.opam/coq-test/.opam-switch/build/coqide.dev/ide/coq.lang to /home/r/.opam/coq-test/share
```

**Comment by herbelin** [comment]
Hi @RalfJung,

> ```
> #=== ERROR while installing coqide.dev ========================================#
> Some files in /home/r/.opam/coq-test/.opam-switch/install/coqide.install couldn't be installed:
>   - /home/r/.opam/coq-test/.opam-switch/build/coqide.dev/ide/coq_style.xml to /home/r/.opam/coq-test/share
>   - /home/r/.opam/coq-test/.opam-switch/build/coqide.dev/ide/coq.png to /home/r/.opam/coq-test/share
>   - /home/r/.opam/coq-test/.opam-switch/build/coqide.dev/ide/coq-ssreflect.lang to /home/r/.opam/coq-test/share
>   - /home/r/.opam/coq-test/.opam-switch/build/coqide.dev/ide/coq.lang to /home/r/.opam/coq-test/share
> ```

I don't know frow where `coqide.install` comes but the location of these four files in master is now `ide/coqide` (instead of `ide`).

**Comment by RalfJung** [comment]
> I don't know frow where coqide.install comes 

It's in the opam repository.

**Comment by RalfJung** [comment]
@herbelin that works locally, thanks!
Let's see what CI says.

**Pull request merged**
