### PR TITLE
MetaCoq 1.0alpha2 for Coq 8.10

### PR DESCRIPTION
**Pull request by mattam82**
ci-skip: coq-metacoq-checker.1.0~alpha2+8.10 coq-metacoq-template.1.0~alpha2+8.10 coq-metacoq-pcuic.1.0~alpha2+8.10 coq-metacoq-safechecker.1.0~alpha2+8.10 coq-metacoq-erasure.1.0~alpha2+8.10 coq-metacoq-translations.1.0~alpha2+8.10

### CODE REVIEW

**Comment by mattam82** [comment]
Hmm the CI is not very efficient, install Coq n times for n packets...

**Comment by gares** [comment]
Yes, it is very silly. If it times out you can put a list of packages to ignore in the PR first comment, see README

**Comment by mattam82** [comment]
Ah, good

**Comment by mattam82** [comment]
@gares Hmm, there's something fishy: it says the translations packages should be skipped but is still trying to install it https://gitlab.com/coq/opam-coq-archive/-/jobs/467946560

**Comment by mattam82** [comment]
It should be fine though, it will only install things twice this time

**Comment by gares** [comment]
It should work now, you don't have to use `code` blocks.
Then it interprets `~` as a markup, but CI should not have problems

**Pull request merged**
