### PR TITLE
sanboxing fix

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
OK, now I know why my fix was not enough. The point it that the *dockerized* runner on pyrolyse changes to hostname to a random valued. Dear @coq/ci-maintainers is there a reliable way to know on which runner a job is being run?

**Comment by SkySkimmer** [comment]
One of the CI_RUNNER variables? https://gitlab.com/help/ci/variables/predefined_variables.md

**Comment by SkySkimmer** [comment]
eg tag the pyrolise runner with `no-sandbox` then use the CI_RUNNER_TAGS variable

**Comment by silene** [comment]
Why is pyrolyse used in the first place? Why not disable it for coq-opam-archive?

**Comment by gares** [comment]
Because we can have a longer timeout on pyrolise... and sometimes PR take a long time.

**Comment by gares** [comment]
> eg tag the pyrolise runner with `no-sandbox` then use the CI_RUNNER_TAGS variable

thanks, but I've no idea about how this tag can be added. If you do it, I can then use that variable in the scripts.

**Comment by silene** [comment]
I have added it. You just need to click on the runner to change tags.

**Pull request merged**
