### PR TITLE
adding coq-math-comp packages to extra-dev

### PR DESCRIPTION
**Pull request by matej-kosik**
These packages enable us to test `math-comp` with the `HEAD` of Coq branches.

### CODE REVIEW

**Comment by silene** [comment]
That does not make sense to me. Why would you create three new packages that all point to the same url and are all built the exact same way?

**Comment by gares** [comment]
You should use symlinks for the files

**Comment by gares** [comment]
Wait a sec, `coq-math-comp` does not exists, there are many `coq-mathcomp-$thing` packages.
If you need a package pulling in everything, please call it `coq-mathcomp-all` not `coq-math-comp` (too confusing).

Note that a single coq-mathcomp package used to exists before the split, but I think it had not `-` in it anyway.

**Comment by gares** [comment]
In any case, if the package only makes sense for testing/benchmarking, I think we should come up with a naming schema for this class of packages.  So that users don't use them by mistake.  We could even have another "suite", i.e. toplevel directory.

**Comment by mattam82** [comment]
I also think a separate repo would be advisable. Maybe not even publicized
outside the dev team.

**Comment by matej-kosik** [comment]
I think that I now see that I made a mistake. The packages are, luckily, already there (named `coq-mathcomp*` rather than `coq-math-comp` which is what I was checking). I apologize and close this pull-request.

**Pull request closed without merging**
