### PR TITLE
Non-offical versions of Coq removed

### PR DESCRIPTION
**Pull request by clarus**
As suggested by @herbelin, the non-official versions of Coq (including `coq.hott`) are removed from the `core-dev` repository.

### CODE REVIEW

**Comment by JasonGross** [comment]
Are these versions available from another opam repo?  It would be nice to be able to install Coq with the profiler from opam (coq.hott is outdated, though, and can probably be be removed entirely; HoTT/HoTT builds with one of the beta versions of Coq 8.5.)

**Comment by clarus** [comment]
OK for the outdated status of `coq.hott`. I added back the LTac profiler.

**Comment by Zimmi48** [comment]
I remarked that when installing the `coq-core-dev` repo (with `opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev` as indicated on @clarus blog), if I then do `opam search coq`, the description that I get for coq is `HoTT/Coq stable branch` which comes from `coq.hott` being the last version listed for Coq and opam confusing description for versions and description for packages. Since the description for `coq.dev` is "Formal proof management system", removing the `coq.hott` version will solve the issue.

**Comment by clarus** [comment]
OK, I think we can remove `coq.hott` then.

**Pull request merged**
