### PR TITLE
Fix max menhir version for compcert.dev

### PR DESCRIPTION
**Pull request by SkySkimmer**
cf https://github.com/AbsInt/CompCert/blob/92b2d35f701ae55129fe2c34066d59d045460852/configure#L558

### CODE REVIEW

**Comment by SkySkimmer** [comment]
cc @jhjourdan according to the opam file

**Comment by jhjourdan** [comment]
That is going to change soon : https://github.com/AbsInt/CompCert/pull/276

**Comment by SkySkimmer** [comment]
I don't know why CI failed, it doesn't seem related.

**Comment by SkySkimmer** [comment]
>That is going to change soon : AbsInt/CompCert#276

Merging this now won't make it harder to fix the package when upstream changes.

**Comment by jhjourdan** [comment]
That's a matter of days. But that's as you want!

**Pull request merged**
