### PR TITLE
VST 2.7: allow Coq 8.13.2

### PR DESCRIPTION
**Pull request by liyishuai**

### CODE REVIEW

**Comment by gares** [comment]
> # Makefile:29: *** FAILURE: You need Coq 8.12.0 or-else 8.12.1 or-else 8.12.2 or-else 8.13.0 or-else 8.13.1 but you have this version: The Coq Proof Assistant, version 8.13.2 (May 2021) compiled on May 4 2021 6:50:44 with OCaml 4.05.0.  Stop.

The makefile of VST is really picky

**Comment by liyishuai** [comment]
Added `IGNORECOQVERSION` to install command. Hope it passes this time...

**Comment by liyishuai** [comment]
The GitLab pipeline seems paused. Is it waiting for something?

**Comment by gares** [comment]
Just to be sure. Did you test that the install target really works? Last time I used the ignore flag it did not.

**Comment by Zimmi48** [comment]
> Did you test that the install target really works? Last time I used the ignore flag it did not.

Was it tested? I also recall that there was a bug with this flag used in combination with `make install`.

**Comment by liyishuai** [comment]
`make install` uses the Makefile itself to determine what files to install, but didn't pass the `IGNORECOQVERSION` flags when computing the list of files, thus installs nothing. Reverting to `cp`-based install in #1707.

**Pull request merged**
