### PR TITLE
New release of TLC.

### PR DESCRIPTION
**Pull request by fpottier**

### CODE REVIEW

**Comment by jhjourdan** [comment]
(One of) The error message is the following:

```
/builds/coq/opam-coq-archive/released/packages/coq-tlc/coq-tlc.20181116/opam: Errors.
             error 57: Synopsis and description must not be both empty
```

And indeed, quoting from [Opam manual](https://opam.ocaml.org/doc/Packaging.html) :

> synopsis should be a one-line description of what your package does, used in listings. It is recommended to also add a description field for a longer explanation (hint: you may delimit long strings with triple-quotation mark delimiters """ to avoid escaping issues). Since opam2.0.1, linting requires to have at least synopsis or description filled.

**Comment by gares** [comment]
The linter is the 2.0 one, in version 1.2 the synopsis was not required. The archive is still in version 1.2, so I would have ignored the error, but you fixed it anyway....

**Comment by gares** [comment]
FTR: by (automatically) converting a 1.2 package to 2.0 format the `descr` file becomes the `description` field of the `opam` file (so synopsis is not strictly needed).

**Comment by fpottier** [comment]
Is there a command to perform this conversion?

**Comment by gares** [comment]
We have to do it atomically on the entire repository. See: https://sympa.inria.fr/sympa/arc/coqdev/2018-11/msg00030.html

**Pull request merged**
