### PR TITLE
coq-coqeal-theory: depends on coq-math-comp 1.5 OR coq-mathcomp-* 1.6

### PR DESCRIPTION
**Pull request by strub**

### CODE REVIEW

**Comment by gares** [comment]
I guess @Barbichu knows better

**Comment by clarus** [comment]
Should we merge it?

**Comment by strub** [comment]
This would be great as I have a project depending on it. FYI, I already checked on my laptop that coqeal can be installed via opam with ssr-1.5 && ssr-1.6...

**Comment by Barbichu** [comment]
I didn't have time to check yet. If you checked @strub and it work then you should proceed.

**Pull request merged**
