### PR TITLE
add dev package for Coq 8.10

### PR DESCRIPTION
**Pull request by palmskog**
Since there is now a `v8.10` branch for Coq, here is a dev package for that branch.

### CODE REVIEW

**Comment by ejgallego** [comment]
I suggest you use the opam file in the main repos.

**Comment by palmskog** [comment]
Not sure I follow, what should I change? This is mostly just copied from the `coq.dev` package, which was updated very recently.

**Comment by ejgallego** [comment]
> Not sure I follow, what should I change? This is mostly just copied from the `coq.dev` package, which was updated very recently.

I was referring to this file: https://github.com/coq/coq/blob/master/coq.opam

But never mind, maybe it is not a good idea to complicate your life with this.

**Comment by RalfJung** [comment]
FWIW, this lacks the coqide package. I'll submit a PR shortly.

**Pull request merged**
