### PR TITLE
switch core-dev to opam2 format

### PR DESCRIPTION
**Pull request by gares**
The open question is if the `opam admin upgrade` command should then also be run on the machine serving the repo (in this case this PR cannot be merged without some help from others)

### CODE REVIEW

**Comment by gares** [comment]
For reference: https://opam.ocaml.org/blog/opam-2-0-0-repo-upgrade-roadmap/#Advice-for-package-maintainers

**Comment by Zimmi48** [comment]
I can change the `output_limit` setting for the Pyrolyse runner. The default is 4096KB. How much would you need?

**Comment by gares** [comment]
I've no idea, the job fails but I can't see why... maybe we should change approach, log to files and in case of failure run `tail -c3M` on them? So that we get in the console the *last* 3 megabytes

**Comment by Zimmi48** [comment]
Would make sense. You can use the artifact system to upload the full log too.

**Comment by gares** [comment]
I think so. There is a possibility I did not explore: opam admin lets you "replicate" a 2.0 archive in 1.2 format.
This may be the way to go for the released archive. For the dev ones, I would not bother: If you use opam for development you have been forced to upgrade to 2.0 already, nothing works anymore as you would like on 1.2 (since the archive is frozen).

**Comment by gares** [comment]
on 4.02 Coq v8.0 fails because
```
- OCAMLC -o bin/coqmktop
- /usr/bin/ld: cannot find -lcurses
```
This if from the C linker, is seems `libncurses5-dev` is not installed (I've no idea why it is needed by Coq but still...). @Zimmi48 is it doable?

**Comment by Zimmi48** [comment]
It should be possible, just change this line:
https://github.com/coq/opam-coq-archive/blob/68068736cffc4c55a1b02e9cc1e74da000eb1db9/.gitlab-ci.yml#L13

**Comment by gares** [comment]
@Zimmi48 I need some extra help here. The old script, the one for travis, was using https://github.com/coq/opam-coq-archive/blob/master/scripts/opam-coq-list-pr-files in order to know which files were touched by the PR. It seems it is not working anymore. IIRC travis makes a merge commit for you, why gitlab CI does not. Could it be the cause of the fact that now this script lists more files (e.g. the failed jobs try to compile files not part of the PR)? Can we fix the script?

**Comment by gares** [comment]
> now this script lists more files

Sorry for the noise, the script lists the same files as before.
For some reason jobs try to build coq packages that are not touched by the PR, so I'll have to investigate more.

**Comment by gares** [comment]
CI still fails because at some point its tries to compile coq-highschool-geometry tat fails with 8.8.2.
I could not figure out why it tries to compile that package, given that this PR touches only coq.* packages.
Help is welcome. Otherwise I think we should announce on Coq dev the switch and after some delay merge this PR and move to switching extra-dev to opam 2.0

**Comment by gares** [comment]
Oh no, CI is still broken, packages are not tested

**Comment by gares** [comment]
@Zimmi48 @SkySkimmer I've debugged the issue here, since I managed to find a log in which it was apparent.

sometimes `master` is not up to date, as a result the PR computes the files touched *other* PRs merged in master (from the out of date value of master to the current PR head, that was rebased on top of current master to make coqbot happy).

 How is the git repo set up on the workers? In my last commit I did add some random git commands to update remotes etc, but I guess I could be more precise.

**Comment by gares** [comment]
are you saying I should use `origin/master` instead of `master` ?

**Comment by SkySkimmer** [comment]
I didn't know that's what you were using but yes.

**Comment by Zimmi48** [comment]
The mirroring of master is done by GitLab itself.

**Pull request merged**
