### PR TITLE
Remove broken packages

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Comment by gares** [comment]
@beta-ziliani : I've to merge this PR since the `opam` tool generating the indexes for the repo stops working if a `url` file is found to point to an archive with a wrong checksum. Please use tags (or simply a .dev packge that are meant to point to branches).

**Comment by herbelin** [comment]
Do we have an interaction with Hengruo Zhang?

**Comment by gares** [comment]
His github account is not there anymore, these is a similar one (remove the z from the other account) but he does not have the repo for coq-toolbox.

**Comment by herbelin** [comment]
I see. So, the assumption is that @hengruo does not maintain his submission anymore. That makes sense, and, in any case, he shall be able to re-submit a package with a working url if it is not the case. Well done.

**Pull request merged**
