### PR TITLE
Stop running bicats in unimath.dev

### PR DESCRIPTION
**Pull request by SkySkimmer**
It wastes too much time in the bench

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@palmskog why did you merge with broken CI?

**Comment by palmskog** [comment]
The CI failure was clearly not related to the package, but to some missing external dependency. I thought you wanted this merged for bench reasons? The extra-dev repo generally has failures for most of its packages.

**Comment by palmskog** [comment]
Specifically, this is what I saw:
> bwrap: execvp : No such file or directory

**Comment by SkySkimmer** [comment]
That's a broken script not a missing dep

**Pull request merged**
