### PR TITLE
GitLab CI

### PR DESCRIPTION
**Pull request by Zimmi48**
There are two ways to proceed from here:
- keep Travis CI for normal jobs and only trigger build on GitLab CI on demand
- use GitLab CI for everything (ditch Travis) and use the pyrolyse runner on demand (no timeout).

In the second case, the triggering of the use of the pyrolyse runner could be automatic: if it failed with a timeout (which in any case should be closer to 2 hours than 50 minutes), then retry the job on pyrolyse.

### CODE REVIEW

**Comment by Zimmi48** [comment]
>use GitLab CI for everything (ditch Travis)

Probably not a good idea in fact since there is only Linux testing on GitLab CI.

**Comment by Zimmi48** [comment]
I don't know what was the idea being testing this on both Linux and macOS. Maybe mostly for Coq and CoqIDE indeed...

**Comment by gares** [comment]
Linux only is fine, so I'm fine with pyrolise only

**Comment by gares** [comment]
I think you should put on top of this one a silly commit touching an opam file, so that we can see what goes on. If I'm not mistaken here I only see the setup of the opam root.

**Comment by Zimmi48** [comment]
I did this and I got an interesting error:
On both Travis and GitLab CI we get a linter error but on Travis it is ignored and on GitLab CI it makes the build fail:

```
Linting core-dev/packages/coqide.dev/opam
/home/travis/build/coq/opam-coq-archive/core-dev/packages/coqide.dev/opam: Errors.
    error 57: Synopsis and description must not be both empty
  warning 58: Found `doc` variable, predefined one is `with-doc`
The command "scripts/opam-coq-list-pr-files | xargs scripts/opam-coq-lint" exited with 123.
```

Let me know what to think of this before I proceed further.

**Comment by gares** [comment]
In Travis I can collect the output of all "lines". If onefail the job fail but you still get all the errors/ feedback. It is intentional. I guess you could make two parallel jobs, the linter and the rest

**Comment by Zimmi48** [comment]
@gares WDYT of the results? These are what should be expected right? And the distinction between the linting and the building actually gives a clearer overview. So how do you want to proceed from there?

**Comment by Zimmi48** [comment]
>If you remove the fake package I think we should merge this.

You mean the second commit?

**Comment by Zimmi48** [comment]
Do not merge yet.

**Comment by Zimmi48** [comment]
FTR, the current version of this PR adds GitLab CI and removes Travis. When a branch is pushed to the GitLab repository, it will build on any available runner (many free runners have timeout at 2h). To build on Pyrolyse, it is just a matter of starting a pipeline with the green "Run Pipeline" button at https://gitlab.com/coq/opam-coq-archive/pipelines (maybe I should document this). In case a pipeline is manually started like this, the build jobs will necessarily run on a runner that is tagged `no-timeout` (currently only Pyrolyse). The `no-timeout` tag is a bit of a lie because while the runner does not set any timeout, GitLab CI forces the project to set one, so I've set the timeout to 10 hours for now.

Besides the documentation, what remains to be done before merging is to have @coqbot automatically push PRs to GitLab like is done in Coq (this shouldn't take too long). I'll let you know when this is done.

**Comment by Zimmi48** [comment]
OK this is ready. I have added doc and the integration with @coqbot.

**Comment by gares** [comment]
awesome!

**Pull request merged**
