### PR TITLE
Update of coq packages wrt ocaml versions

### PR DESCRIPTION
**Pull request by herbelin**
These are mini-fixes for some coq "dev" packages:

- more precise ocaml version requirements
- new need for `num` since OCaml 4.06.0
- ~~`make -j` not working on some old versions~~

~~I may update it further in the next hours, but, to minimize possible worries regarding the different ways to get Coq in relation with the ocaml 4.06 + coq 8.6 [coq-club](https://sympa.inria.fr/sympa/arc/coq-club/2017-12/msg00033.html) discussion, a confirmation that someone will merge it by tomorrow say noon would be good (note that for 8.6.dev, it is only about the `num` dependency).~~

(Edited to reflect the new state of the PR).

### CODE REVIEW

**Comment by Zimmi48** [comment]
@gares is the main maintainer of this repository and was the one who implemented the Travis check. I'll let him say whether he thinks that the failing Travis can be fixed or not (one of them is "wrong `opam-version`", and the other one is "`gtk-dev` not installed on the system").

**Comment by gares** [comment]
I think the best way to know is to integrate in this PR a commit updating travis.yml to include the dependency on the system library gtk.  An alternative is to have the packages not depend on lablgtk (and not build coqide).
This is what happens today, the coq package does not build coqide (and does not depend on lablgtk).

The wrong opam version is because the opam files contain `opam-version 1.1`, while it should be `1.2`.  This has to be fixed in the packages.

**Comment by Zimmi48** [comment]
Right, while I would support having CoqIDE packages in this repository, this should probably be done in another PR so this one could just remove the dependency on lablgtk.

**Comment by RalfJung** [comment]
CI can now test CoqIDE and indeed has done so in #242. @herbelin could you rebase onto current master, so the tests re-run with the latest CI?

**Comment by Zimmi48** [comment]
Another way to retrigger CI is closing / reopening.

**Comment by RalfJung** [comment]
Yes but won't it use the old CI from this branch now?

**Comment by Zimmi48** [comment]
Nope, Travis uses the merge commit that GitHub automatically creates.
You can see on the Travis build page https://travis-ci.org/coq/opam-coq-archive/builds/320245473, the reference to the commit https://github.com/coq/opam-coq-archive/commit/563fad94dd933d8ff55c936b253f8378b33d77f9 which is merging the tip of this branch into current master.

**Comment by herbelin** [comment]
> The wrong opam version is because the opam files contain opam-version 1.1, while it should be 1.2. This has to be fixed in the packages.

Fixed.

> CI can now test CoqIDE and indeed has done so in #242. @herbelin could you rebase onto current master, so the tests re-run with the latest CI?

Rebased.

> It may however be necessary to split this into multiple PRs. This will build Coq 5 times on the CI (once for each package that changed), which may take too long. Maybe make one PR for Coq 8.2 - 8.4, and one PR for 8.5 - 8.6?

Do you confirm I should do it? Or maybe it will be too late tomorrow?

**Comment by RalfJung** [comment]
> Do you confirm I should do it? Or maybe it will be too late tomorrow?

Well, feel free to first try them all in one PR if you like to gamble on it not timing out. ;)

**Comment by herbelin** [comment]
OK, I had not understood that it was about timing out.

I created #249 for 8.2, 8.3 and 8.4. This one is now only for 8.5 and 8.6.

**Comment by Zimmi48** [comment]
Now the linter says:

```
Linting core-dev/packages/coq.8.5.dev/opam
Errors found in ~/build/coq/opam-coq-archive/core-dev/packages/coq.8.5.dev/opam:
    error 25: Missing field 'authors'
  warning 37: Missing field 'dev-repo'
```

**Comment by mattam82** [comment]
Thanks @herbelin !

**Pull request merged**
