### PR TITLE
Remove generation of pages from LAYOUT etc which are gone now

### PR DESCRIPTION
**Pull request by mattam82**
I think that was just forgotten by @vbgl

### CODE REVIEW

**Comment by vbgl** [comment]
Indeed thanks.

**Comment by vbgl** [comment]
The pages <https://coq.inria.fr/opam/www/using.html>, <https://coq.inria.fr/opam/www/layout.html>, and <https://coq.inria.fr/opam/www/packaging.html> still exist. I can’t find where there are generated.

Some leftover files on the server?

**Comment by mattam82** [comment]
Indeed, should I put in redirects? To where?

**Comment by vbgl** [comment]
I was contemplating adding the following rule to https://github.com/coq/www/blob/master/aliases.footer.conf
~~~
RewriteRule ^opam/www/(layout|packaging|using).html opam-$1.html [R=301]
~~~

**Comment by mattam82** [comment]
Sounds good to me. I removed the leftover files

**Comment by vbgl** [comment]
Thanks. I think discussion can continue there: https://github.com/coq/www/pull/91

**Pull request merged**
