### PR TITLE
Changes to support opam 2.0's sandboxing

### PR DESCRIPTION
**Pull request by Garogolun**
As far as I can see, these files should be compatible with opam 1.2 as well.

### CODE REVIEW

**Comment by gares** [comment]
travis cannot find the commits because you force pushed, closing/reopening (sometimes it works)

**Comment by gares** [comment]
You need to fill in the `authors` field.
Also, the Coq 8.5 + ltacprof seems to lack a dependency on `num` (required for OCaml 4.06). Could you include such a fix in your PR?

**Comment by Garogolun** [comment]
Is `num` a dependency for all Coq versions? If so, I'll add the dependency to all of them.

**Comment by ejgallego** [comment]
> Is num a dependency for all Coq versions? If so, I'll add the dependency to all of them.

Yes, it is.

**Pull request merged**
