### PR TITLE
build json using opam and findlib (ditch dune and nix)

### LINKED ISSUE #1995: Invalid dune file in json-data CI job
We recently started seeing failing `json-data` CI jobs, with the following message:
```
File "nix/store/2w9yyr6c3py70kwsv8zvvx5afsfx3zx3-dune-2.8.5/bin/dune", line 1, characters 0-0:
Error: Invalid dune file
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 1
```
As was figured out by @silene in #1994, the error message only appears with "latest" Nix Docker images, and disappears with `nixos/nix:2.3.12`. However, setting the latter may only be a band-aid for the underlying issue, which may be some bad interaction between Nix and Dune.

Example of failing job: https://gitlab.com/coq/opam-coq-archive/-/jobs/1889653040

Pinging Nix-knowledgeable people who may be able to comment: @Zimmi48 @vbgl.

### PR DESCRIPTION
**Pull request by gares**
Apparently dune does not like itself. We build using findlib and we install specific versions of the dependencies of archive2web using opam.

fix #1995

### CODE REVIEW

**Comment by gares** [comment]
It seems to build fine now, but I did not check the resulting json.
I've improved the warning about multiple dates (so that we know which package can be fixed).

**Comment by gares** [comment]
```
W: multiple date tag in released/packages/coq-lc/coq-lc.8.10.0/opam
W: multiple date tag in released/packages/coq-lc/coq-lc.8.9.0/opam
W: multiple date tag in released/packages/coq-lc/coq-lc.8.8.0/opam
W: multiple date tag in released/packages/coq-lc/coq-lc.8.7.0/opam
W: multiple date tag in released/packages/coq-lc/coq-lc.8.6.0/opam
```

**Comment by palmskog** [comment]
This all looks reasonable to me, I think we can fix the multiple dates thing in another PR.

**Comment by gares** [comment]
ok, let's put the archive back on track this way

**Pull request merged**
