### PR TITLE
[opam2] convert released archive

### LINKED ISSUE #257: opam 2.0 switch
We should try opam 2.0 at some point, the release candidate is out:
https://opam.ocaml.org/blog/opam-2-0-0-rc/

### PR DESCRIPTION
**Pull request by gares**
Plan is:
- iterate until it works (each removal of broken packages is a separate commit)
- announce on coq-club with 1 month advance
- copy the old archive somewhere CC @vbgl 
- update `repo` file with a redirect
- merge

fix #257
CC @sacerdot https://gl.mathhub.info/Coqxml

## Packages that work
ci-skip: coq-aac-tactics.8.5.0 coq-aac-tactics.8.5.1 coq-aac-tactics.8.6.1 coq-aac-tactics.8.8.0 coq-abp.8.5.0 coq-abp.8.6.0 coq-abp.8.7.0 coq-abp.8.8.0 coq-additions.8.5.0 coq-additions.8.6.0 coq-additions.8.7.0 coq-additions.8.8.0 coq-ails.8.5.0 coq-aac-tactics.8.8.0 coq-abp.8.7.0 coq-abp.8.8.0 coq-additions.8.7.0 coq-additions.8.8.0 coq-ails.8.7.0 coq-ails.8.8.0 coq-algebra.8.7.0 coq-algebra.8.8.0 coq-amm11262.8.7.0 coq-amm11262.8.8.0 coq-angles.8.7.0 coq-angles.8.8.0 coq-area-method.8.7.0 coq-area-method.8.8.0 coq-atbr.8.7.0 coq-atbr.8.8.0 coq-automata.8.7.0 coq-automata.8.8.0 coq-axiomatic-abp.8.7.0 coq-axiomatic-abp.8.8.0 coq-bbv.1.0 coq-bdds.8.7.0 coq-bellantonicook.1.0.0 coq-bertrand.8.7.0 coq-bertrand.8.8.0 coq-bignums.8.7.0 coq-bignums.8.8.0 coq-bignums.8.9.0 coq-buchberger.8.7.0 coq-buchberger.8.8.0 coq-canon-bdds.8.7.0 coq-canon-bdds.8.8.0 coq-cantor.8.7.0 coq-cantor.8.8.0 coq-cats-in-zfc.8.7.0 coq-cats-in-zfc.8.8.0 coq-ccs.8.7.0 coq-ccs.8.8.0 coq-cecoa.1.0.0 oq-ails.8.6.0 coq-algebra.8.5.0 coq-algebra.8.6.0 coq-amm11262.8.5.0 coq-amm11262.8.6.0 coq-angles.8.5.0 coq-angles.8.6.0 coq-area-method.8.5.0 coq-area-method.8.6.0 coq-atbr.8.5.0 coq-cfgv.8.7.0 coq-cfgv.8.8.0 coq-cfml.20181201 coq-charge-core.1.2.0 coq-checker.8.7.0 coq-checker.8.8.0 coq-chinese.8.7.0 coq-chinese.8.8.0 coq-circuits.8.7.0 coq-circuits.8.8.0 coq-classical-realizability.8.7.0 coq-classical-realizability.8.8.0 coq-coalgebras.8.7.0 coq-coalgebras.8.8.0 coq-coinductive-examples.8.7.0 coq-coinductive-examples.8.8.0 coq-coinductive-reals.8.7.0 coq-coinductive-reals.8.8.0 coq-color.1.4.0 coq-color.1.5.0 coq-color.1.6.0 coq-compcert.3.2.0 coq-compcert.3.3.0 coq-concat.8.7.0 coq-concat.8.8.0 coq-constructive-geometry.8.7.0 coq-constructive-geometry.8.8.0 coq-containers.8.7.0 coq-containers.8.8.0 coq-continuations.8.7.0 coq-continuations.8.8.0 coq-coq-in-coq.8.7.0 coq-coq-in-coq.8.8.0 coq-coq2html.1.0 coq-coq2html.1.1 coq-coqoban.8.7.0 coq-coqoban.8.8.0 coq-coqprime.1.0.1 coq-coqprime.1.0.2 coq-coqprime.1.0.3 coq-coquelicot.3.0.2 coq-corn.1.2.0 coq-corn.8.8.1 coq-cours-de-coq.8.7.0 coq-cours-de-coq.8.8.0 coq-ctltctl.8.7.0 coq-ctltctl.8.8.0 coq-cunit.1.0.0 coq-dblib.8.7.0 coq-dblib.8.8.0 coq-demos.8.7.0 coq-demos.8.8.0 coq-dep-map.8.7.0 coq-dep-map.8.8.0 coq-descente-infinie.8.7.0 coq-descente-infinie.8.8.0 coq-dictionaries.8.7.0 coq-dictionaries.8.8.0 coq-disel.2.0 coq-disel.2.1 coq-distributed-reference-counting.8.7.0 coq-distributed-reference-counting.8.8.0 coq-domain-theory.8.7.0 coq-domain-theory.8.8.0 coq-dpdgraph.0.6.2 coq-dpdgraph.0.6.3 coq-equations.1.0+8.7 coq-equations.1.0+8.8 coq-equations.1.0~beta2+8.7 coq-equations.1.1+8.8 coq-equations.1.2~beta+8.8 coq-equations.1.2~beta+8.9 coq-error-handlers.1.0.0 coq-error-handlers.1.1.0 coq-error-handlers.1.1.1 coq-error-handlers.1.2.0 coq-euclidean-geometry.8.7.0 coq-euclidean-geometry.8.8.0 coq-euler-formula.8.7.0 coq-euler-formula.8.8.0 coq-exact-real-arithmetic.8.7.0 coq-exact-real-arithmetic.8.8.0 coq-exceptions.8.7.0 coq-exceptions.8.8.0 coq-ext-lib.0.10.0 coq-ext-lib.0.10.1 coq-ext-lib.0.9.7 coq-ext-lib.0.9.8 coq-extructures.0.1.0 coq-fairisle.8.7.0 coq-fairisle.8.8.0 coq-fcsl-pcm.1.0.0 coq-fermat4.8.7.0 coq-fermat4.8.8.0 coq-finger-tree.8.7.0 coq-firing-squad.8.7.0 coq-firing-squad.8.8.0 coq-float.8.7.0 coq-float.8.8.0 coq-flocq.2.6.1 coq-flocq.3.0.0 coq-flocq.3.1.0 coq-founify.8.7.0 coq-founify.8.8.0 coq-free-groups.8.7.0 coq-free-groups.8.8.0 coq-fsets.8.7.0 coq-fsets.8.8.0 coq-fssec-model.8.7.0 coq-fssec-model.8.8.0 coq-function-ninjas.1.0.0 coq-functional-algebra.1.0.2 coq-functions-in-zfc.8.7.0 coq-functions-in-zfc.8.8.0 coq-fundamental-arithmetics.8.7.0 coq-fundamental-arithmetics.8.8.0 coq-gappa.1.3.3 coq-gappa.1.3.4 coq-gappa.1.4.0 coq-gc.8.7.0 coq-gc.8.8.0 coq-generic-environments.8.7.0 coq-generic-environments.8.8.0 coq-geocoq.2.3.0 coq-geometric-algebra.0.8.8 coq-goedel.8.7.0 coq-goedel.8.8.0 coq-graph-basics.8.7.0 coq-graph-basics.8.8.0 coq-graphs.8.7.0 coq-graphs.8.8.0 coq-group-theory.8.7.0 coq-group-theory.8.8.0 coq-groups.8.7.0 coq-groups.8.8.0 coq-hammer.1.0.8+8.7 coq-hammer.1.0.9+8.8.0 coq-hammer.1.0.9+8.8.1 coq-hammer.1.1+8.8 coq-hammer.1.1+8.9 coq-hardware.8.7.0 coq-hardware.8.8.0 coq-hedges.8.7.0 coq-hedges.8.8.0 coq-higman-cf.8.7.0 coq-higman-cf.8.8.0 coq-higman-nw.8.7.0 coq-higman-nw.8.8.0 coq-higman-s.8.7.0 coq-higman-s.8.8.0 coq-historical-examples.8.7.0 coq-historical-examples.8.8.0 coq-hoare-tut.8.7.0 coq-hoare-tut.8.8.0 coq-huffman.8.7.0 coq-huffman.8.8.0 coq-icharate.8.7.0 coq-icharate.8.8.0 coq-idxassoc.8.7.0 coq-idxassoc.8.8.0 coq-ieee754.8.7.0 coq-ieee754.8.8.0 coq-improper-integrals.0.1.0 coq-int-map.8.7.0 coq-int-map.8.8.0 coq-interval.3.3.0 coq-interval.3.4.0 coq-io-list.1.0.0 coq-io-list.1.1.0 coq-io.2.0.0 coq-io.2.1.0 coq-io.3.0.0 coq-io.3.1.0 coq-ipc.8.7.0 coq-ipc.8.8.0 coq-iris.3.1.0 coq-iterable.1.0.0 coq-izf.8.7.0 coq-izf.8.8.0 coq-jordan-curve-theorem.8.7.0 coq-jordan-curve-theorem.8.8.0 coq-jsast.1.0.7 coq-jsast.1.0.8 coq-karatsuba.8.7.0 coq-karatsuba.8.8.0 coq-kildall.8.7.0 coq-kildall.8.8.0 coq-label.1.0.0 coq-lambda.8.7.0 coq-lambda.8.8.0 coq-lambek.8.7.0 coq-lambek.8.8.0 coq-lazy-pcf.8.7.0 coq-lazy-pcf.8.8.0 coq-lc.8.7.0 coq-lc.8.8.0 coq-lemma-overloading.8.8.0 coq-lesniewski-mereology.8.7.0 coq-lesniewski-mereology.8.8.0 coq-lin-alg.8.7.0 coq-lin-alg.8.8.0 coq-list-plus.1.0.0 coq-list-plus.1.1.0 coq-ltac2.0.1-8.7 coq-ltl.8.7.0 coq-ltl.8.8.0 coq-maple-mode.8.7.0 coq-maple-mode.8.8.0 coq-markov.8.7.0 coq-markov.8.8.0 coq-math-classes.8.8.1 coq-mathcomp-algebra.1.6.2 coq-mathcomp-algebra.1.6.4 coq-mathcomp-algebra.1.7.0 coq-mathcomp-bigenough.1.0.0 coq-mathcomp-character.1.6.2 coq-mathcomp-character.1.6.4 coq-mathcomp-character.1.7.0 coq-mathcomp-field.1.6.2 coq-mathcomp-field.1.6.4 coq-mathcomp-field.1.7.0 coq-mathcomp-fingroup.1.6.2 coq-mathcomp-fingroup.1.6.4 coq-mathcomp-fingroup.1.7.0 coq-mathcomp-finmap.1.0.0 coq-mathcomp-finmap.1.1.0 coq-mathcomp-multinomials.1.0 coq-mathcomp-multinomials.1.1 coq-mathcomp-odd-order.1.6.2 coq-mathcomp-odd-order.1.7.0 coq-mathcomp-real-closed.1.0.1 coq-mathcomp-solvable.1.6.2 coq-mathcomp-solvable.1.6.4 coq-mathcomp-solvable.1.7.0 coq-mathcomp-ssreflect.1.6.2 coq-mathcomp-ssreflect.1.6.4 coq-mathcomp-ssreflect.1.7.0 coq-mathcomp-sum-of-two-square.1.0.0 coq-mathcomp-sum-of-two-square.1.0.1 coq-maths.8.7.0 coq-maths.8.8.0 coq-matrices.8.7.0 coq-matrices.8.8.0 coq-menhirlib.20180530 coq-menhirlib.20180827 coq-min-imports.1.0.0 oq-ails.8.6.0 coq-atbr.8.6.0 coq-automata.8.5.0 coq-automata.8.6.0 coq-axiomatic-abp.8.5.0 coq-axiomatic-abp.8.6.0 coq-bdds.8.5.0 coq-bdds.8.6.0 coq-bertrand.8.5.0 coq-bertrand.8.6.0 coq-bignums.8.6.0 coq-buchberger.8.5.0 coq-buchberger.8.6.0 coq-canon-bdds.8.5.0 coq-canon-bdds.8.6.0 coq-cantor.8.5.0 coq-cantor.8.6.0 coq-cats-in-zfc.8.5.0 coq-cats-in-zfc.8.6.0 coq-ccs.8.5.0 coq-ccs.8.6.0 coq-cfgv.8.5.0 coq-cfgv.8.6.0 coq-charge-core.1.0.1 coq-charge-core.1.1.0 coq-checker.8.5.0 coq-checker.8.6.0 coq-chinese.8.5.0 coq-chinese.8.6.0 coq-circuits.8.5.0 coq-circuits.8.6.0 coq-classical-realizability.8.5.0 coq-classical-realizability.8.6.0 coq-coalgebras.8.5.0 coq-coalgebras.8.6.0 coq-coinductive-examples.8.5.0 coq-coinductive-examples.8.6.0 coq-coinductive-reals.8.5.0 coq-coinductive-reals.8.6.0 coq-color.1.0.0 coq-color.1.1.0 coq-color.1.2.0 coq-color.1.3.0 coq-compcert.2.0.0 coq-compcert.2.3.2 coq-compcert.2.4.0 coq-compcert.2.5.0 coq-compcert.2.6.0 coq-compcert.3.0.0 coq-compcert.3.0.1 coq-compcert.3.1.0 coq-concat.8.5.0 coq-concat.8.6.0 coq-constructive-geometry.8.5.0 coq-constructive-geometry.8.6.0 coq-constructors.1.0.0 coq-containers.8.5.0 coq-containers.8.6.0 coq-continuations.8.5.0 coq-continuations.8.6.0 coq-coq-in-coq.8.5.0 coq-coq-in-coq.8.6.0 coq-coqeal-refinements.0.9.1 coq-coqeal-theory.0.9.1 coq-coqoban.8.5.0 coq-coqoban.8.6.0 coq-coqprime.1.0.0 coq-coqrel.0.1.0 coq-coquelicot.2.1.1 coq-coquelicot.2.1.2 coq-corn.1.0.0 coq-counting.8.5.0 coq-counting.8.6.0 coq-cours-de-coq.8.5.0 coq-cours-de-coq.8.6.0 coq-ctltctl.8.5.0 coq-ctltctl.8.6.0 coq-cybele.1.3.0 coq-dblib.8.5.0 coq-dblib.8.6.0 coq-demos.8.5.0 coq-demos.8.6.0 coq-dep-map.8.5.0 coq-dep-map.8.6.0 coq-descente-infinie.8.5.0 coq-descente-infinie.8.6.0 coq-dictionaries.8.5.0 coq-dictionaries.8.6.0 coq-distributed-reference-counting.8.5.0 coq-distributed-reference-counting.8.6.0 coq-domain-theory.8.5.0 coq-domain-theory.8.6.0 coq-dpdgraph.0.4 coq-dpdgraph.0.5.1 coq-dpdgraph.0.5 coq-dpdgraph.0.6.1 coq-dpdgraph.0.6 coq-equations.1.0 coq-equations.1.0~beta2 coq-ergo.8.5.0 coq-ergo.8.6.0 coq-euclidean-geometry.8.5.0 coq-euclidean-geometry.8.6.0 coq-euler-formula.8.5.0 coq-euler-formula.8.6.0 coq-exact-real-arithmetic.8.5.0 coq-exact-real-arithmetic.8.6.0 coq-exceptions.8.5.0 coq-exceptions.8.6.0 coq-ext-lib.0.9.0 coq-ext-lib.0.9.0~beta3 coq-ext-lib.0.9.1 coq-ext-lib.0.9.2 coq-ext-lib.0.9.3 coq-ext-lib.0.9.4 coq-ext-lib.0.9.5 coq-ext-lib.0.9.6 coq-fairisle.8.5.0 coq-fairisle.8.6.0 coq-fermat4.8.5.0 coq-fermat4.8.6.0 coq-finger-tree.8.5.0 coq-finger-tree.8.6.0 coq-firing-squad.8.5.0 coq-firing-squad.8.6.0 coq-float.8.5.0 coq-float.8.6.0 coq-flocq.2.2.0 coq-flocq.2.3.0 coq-flocq.2.4.0 coq-flocq.2.5.2 coq-founify.8.5.0 coq-founify.8.6.0 coq-fpmods.0.2.0 coq-free-groups.8.5.0 coq-free-groups.8.6.0 coq-fsets.8.5.0 coq-fsets.8.6.0 coq-fssec-model.8.5.0 coq-fssec-model.8.6.0 coq-functions-in-zfc.8.5.0 coq-functions-in-zfc.8.6.0 coq-fundamental-arithmetics.8.5.0 coq-persistent-union-find.8.7.0 coq-persistent-union-find.8.8.0 coq-pi-agm.1.2.2 coq-pi-calc.8.7.0 coq-pi-calc.8.8.0 coq-pigeonhole-principle.1.0.3 coq-pigeonhole-principle.1.0.4 coq-plouffe.1.4.0 coq-pocklington.8.7.0 coq-pocklington.8.8.0 coq-poltac.0.8.8 coq-ppsimpl.1.0.0 coq-ppsimpl.8.8.0 coq-presburger.8.7.0 coq-presburger.8.8.0 coq-prfx.8.7.0 coq-prfx.8.8.0 coq-procrastination.1.0 coq-procrastination.1.1 coq-procrastination.1.2 coq-projective-geometry.8.7.0 coq-projective-geometry.8.8.0 coq-propcalc.8.7.0 coq-propcalc.8.8.0 coq-pts.8.7.0 coq-pts.8.8.0 coq-ptsatr.8.7.0 coq-ptsatr.8.8.0 coq-ptsf.8.7.0 coq-ptsf.8.8.0 coq-qarith-stern-brocot.8.7.0 coq-qarith-stern-brocot.8.8.0 coq-qarith.8.7.0 coq-qarith.8.8.0 coq-qcert.1.1.0 coq-qcert.1.2.0 coq-quickchick.1.0.0 coq-quicksort-complexity.8.7.0 coq-quicksort-complexity.8.8.0 coq-railroad-crossing.8.7.0 coq-railroad-crossing.8.8.0 coq-ramsey.8.7.0 coq-ramsey.8.8.0 coq-random.8.7.0 coq-random.8.8.0 coq-reflexive-first-order.8.7.0 coq-reflexive-first-order.8.8.0 coq-regexp.8.7.0 coq-regexp.8.8.0 coq-reglang.1 coq-relation-algebra.1.7 coq-relation-extraction.8.7.0 coq-relation-extraction.8.8.0 coq-rem.8.7.0 coq-rem.8.8.0 coq-rsa.8.7.0 coq-rsa.8.8.0 coq-ruler-compass-geometry.8.7.0 coq-ruler-compass-geometry.8.8.0 coq-schroeder.8.7.0 coq-schroeder.8.8.0 coq-search-trees.8.7.0 coq-search-trees.8.8.0 coq-shuffle.8.7.0 coq-shuffle.8.8.0 coq-simple-io.0.1 coq-simple-io.0.2 coq-simple-io.1.0.0 coq-smc.8.7.0 coq-smc.8.8.0 coq-square-matrices.8.7.0 coq-square-matrices.8.8.0 coq-squiggle-eq.1.0.3 coq-ails.8.6.0 coq-fundamental-arithmetics.8.6.0 coq-gappa.1.2.1 coq-gappa.1.3.2 coq-gc.8.5.0 coq-gc.8.6.0 coq-generic-environments.8.5.0 coq-generic-environments.8.6.0 coq-geocoq.1.0.1 coq-geocoq.1.1.0 coq-geocoq.2.0.0 coq-geocoq.2.1.0 coq-geocoq.2.2.0 coq-geocoq.2.2.1 coq-goedel.8.5.0 coq-goedel.8.6.0 coq-graph-basics.8.5.0 coq-graph-basics.8.6.0 coq-graphs.8.5.0 coq-graphs.8.6.0 coq-group-theory.8.5.0 coq-group-theory.8.6.0 coq-groups.8.5.0 coq-groups.8.6.0 coq-hammer.1.0.3 coq-hardware.8.5.0 coq-hardware.8.6.0 coq-hedges.8.5.0 coq-hedges.8.6.0 coq-high-school-geometry.1.0.0 coq-high-school-geometry.8.6.0 coq-higman-cf.8.5.0 coq-higman-cf.8.6.0 coq-higman-nw.8.5.0 coq-higman-nw.8.6.0 coq-higman-s.8.5.0 coq-higman-s.8.6.0 coq-historical-examples.8.5.0 coq-historical-examples.8.6.0 coq-hoare-tut.8.5.0 coq-hoare-tut.8.6.0 coq-huffman.8.5.0 coq-huffman.8.6.0 coq-icharate.8.5.0 coq-icharate.8.6.0 coq-idxassoc.8.5.0 coq-idxassoc.8.6.0 coq-ieee754.8.5.0 coq-ieee754.8.6.0 coq-int-map.8.5.0 coq-int-map.8.6.0 coq-interval.3.1.1 coq-interval.3.2.0 coq-intuitionistic-nuprl.8.6.0 coq-io-exception.1.0.0 coq-io.3.2.0 coq-io.3.3.0 coq-ipc.8.5.0 coq-ipc.8.6.0 coq-iris.3.0.0 coq-izf.8.5.0 coq-jordan-curve-theorem.8.5.0 coq-jordan-curve-theorem.8.6.0 coq-jprover.8.5.0 coq-jprover.8.6.0 coq-karatsuba.8.5.0 coq-karatsuba.8.6.0 coq-kildall.8.5.0 coq-kildall.8.6.0 coq-lambda.8.5.0 coq-lambda.8.6.0 coq-lambek.8.5.0 coq-lambek.8.6.0 coq-lazy-pcf.8.5.0 coq-lazy-pcf.8.6.0 coq-lc.8.5.0 coq-lc.8.6.0 coq-legacy-ring.8.5.0 coq-lesniewski-mereology.8.5.0 coq-lesniewski-mereology.8.6.0 coq-lin-alg.8.5.0 coq-lin-alg.8.6.0 coq-list-string.1.0.0 coq-ltl.8.5.0 coq-ltl.8.6.0 coq-maple-mode.8.5.0 coq-maple-mode.8.6.0 coq-markov.8.5.0 coq-markov.8.6.0 coq-math-classes.1.0.3 coq-math-classes.1.0.4 coq-math-classes.1.0.5 coq-math-classes.1.0.6 coq-mathcomp-algebra.1.6.1 coq-mathcomp-algebra.1.6 coq-mathcomp-character.1.6.1 oq-paradoxes.8.7.0 coq-paradoxes.8.8.0 coq-param-pi.8.7.0 coq-param-pi.8.8.0 coq-paramcoq.1.0.6 coq-paramcoq.1.0.9 coq-paramcoq.1.1.0 coq-paramcoq.1.1.1+coq8.7 coq-paramcoq.1.1.1+coq8.8 coq-paramcoq.1.1.1+coq8.9 coq-pautomata.8.7.0 coq-pautomata.8.8.0 coq-semantics.8.7.0 coq-semantics.8.8.0 coq-squiggle-eq.1.0.4 coq-stalmarck.8.7.0 coq-stalmarck.8.8.0 coq-stdpp.1.0.0 coq-stdpp.1.1.0 coq-streams.8.7.0 coq-streams.8.8.0 coq-subst.8.7.0 coq-subst.8.8.0 coq-sudoku.8.7.0 coq-sudoku.8.8.0 coq-sum-of-two-square.8.7.0 coq-sum-of-two-square.8.8.0 coq-switch.1.0.0 coq-tait.8.7.0 coq-tait.8.8.0 coq-tarski-geometry.8.7.0 coq-tarski-geometry.8.8.0 coq-template-coq.2.1~beta3 coq-three-gap.8.7.0 coq-three-gap.8.8.0 coq-tlc.20171206 coq-tlc.20180316 coq-tlc.20181116 coq-topology.8.7.0 coq-topology.8.8.0 coq-tortoise-hare-algorithm.8.7.0 coq-tortoise-hare-algorithm.8.8.0 coq-traversable-fincontainer.8.7.0 coq-traversable-fincontainer.8.8.0 coq-tree-automata.8.7.0 coq-tree-automata.8.8.0 coq-tree-diameter.8.7.0 coq-tree-diameter.8.8.0 coq-vst.2.2 coq-weak-up-to.8.7.0 coq-weak-up-to.8.8.0 coq-zchinese.8.7.0 coq-zchinese.8.8.0 coq-zf.8.7.0 coq-zf.8.8.0 coq-zfc.8.7.0 coq-zfc.8.8.0 coq-zorns-lemma.8.7.0 coq-zorns-lemma.8.8.0 coq-zsearch-trees.8.7.0 coq-zsearch-trees.8.8.0 coq.8.8.2 coq.8.9.0 coqide.8.8.2 coqide.8.9.0 coq-paradoxes.8.6.0 coq-paradoxes.8.7.0 coq-paradoxes.8.8.0 coq-param-pi.8.5.0 coq-param-pi.8.6.0 coq-param-pi.8.7.0 coq-param-pi.8.8.0 coq-paramcoq.1.0.6 coq-paramcoq.1.0.9 coq-paramcoq.1.1.0 coq-paramcoq.1.1.1+coq8.7 coq-paramcoq.1.1.1+coq8.8 coq-paramcoq.1.1.1+coq8.9 coq-pautomata.8.5.0 coq-pautomata.8.6.0 coq-pautomata.8.7.0 coq-pautomata.8.8.0 coq-persistent-union-find.8.5.0 coq-persistent-union-find.8.6.0 coq-pi-agm.1.1.0 coq-ott.0.28 coq-otway-rees.8.7.0 coq-otway-rees.8.8.0 coq-paco.1.2.8 coq-paco.1.2.9 coq-paco.2.0.0 coq-paco.2.0.1 coq-paco.2.0.2 coq-ott.0.28 coq-otway-rees.8.5.0 coq-otway-rees.8.6.0 coq-otway-rees.8.7.0 coq-otway-rees.8.8.0 coq-paco.1.2.8 coq-paco.1.2.9 coq-paco.2.0.0 coq-paco.2.0.1 coq-paco.2.0.2 coq-paradoxes.8.5.0 coq-pi-agm.1.2.0 coq-pi-calc.8.5.0 coq-pi-calc.8.6.0 coq-plouffe.1.2.0 coq-plouffe.1.2.1 coq-plouffe.1.3.0 coq-plugin-utils.1.1.0 coq-plugin-utils.1.2.0 coq-plugin-utils.1.3.0 coq-pocklington.8.5.0 coq-pocklington.8.6.0 coq-presburger.8.5.0 coq-presburger.8.6.0 coq-prfx.8.5.0 coq-prfx.8.6.0 coq-projective-geometry.8.5.0 coq-projective-geometry.8.6.0 coq-propcalc.8.5.0 coq-propcalc.8.6.0 coq-pts.8.5.0 coq-pts.8.6.0 coq-ptsatr.8.5.0 coq-ptsatr.8.6.0 coq-ptsf.8.5.0 coq-ptsf.8.6.0 coq-qarith-stern-brocot.8.5.0 coq-qarith-stern-brocot.8.6.0 coq-qarith.8.5.0 coq-qarith.8.6.0 coq-quicksort-complexity.8.5.0 coq-quicksort-complexity.8.6.0 coq-railroad-crossing.8.5.0 coq-railroad-crossing.8.6.0 coq-ramsey.8.5.0 coq-ramsey.8.6.0 coq-random.8.5.0 coq-random.8.6.0 coq-rational.8.5.0 coq-recursive-definition.8.5.0 coq-recursive-definition.8.6.0 coq-reflexive-first-order.8.5.0 coq-reflexive-first-order.8.6.0 coq-regexp.8.5.0 coq-regexp.8.6.0 coq-relation-algebra.1.3 coq-relation-algebra.1.4 coq-relation-algebra.1.5 coq-relation-algebra.1.6 coq-relation-extraction.8.5.0 coq-relation-extraction.8.6.0 coq-rem.8.5.0 coq-rem.8.6.0 coq-rsa.8.5.0 coq-rsa.8.6.0 coq-ruler-compass-geometry.8.5.0 coq-ruler-compass-geometry.8.6.0 coq-scev.1.0.1 coq-schroeder.8.5.0 coq-schroeder.8.6.0 coq-search-trees.8.5.0 coq-search-trees.8.6.0 coq-semantics.8.5.0 coq-semantics.8.6.0 coq-shuffle.8.5.0 coq-shuffle.8.6.0 coq-smc.8.5.0 coq-smc.8.6.0 coq-smt-check.1.0.0 coq-smt-check.2.0.0 coq-square-matrices.8.5.0 coq-square-matrices.8.6.0 coq-squiggle-eq.1.0.1 coq-squiggle-eq.1.0.2 coq-stalmarck.8.5.0 coq-stalmarck.8.6.0 coq-streams.8.5.0 coq-streams.8.6.0 coq-string.8.6.0 coq-subst.8.5.0 coq-subst.8.6.0 coq-sudoku.8.5.0 coq-sudoku.8.6.0 coq-sum-of-two-square.8.5.0 coq-sum-of-two-square.8.6.0 coq-tait.8.5.0 coq-tait.8.6.0 coq-tarski-geometry.8.5.0 coq-tarski-geometry.8.6.0 coq-template-coq.1.1.0~beta3 coq-three-gap.8.5.0 coq-three-gap.8.6.0 coq-tlc.20161010 coq-tlc.20171128 coq-topology.8.5.0 coq-topology.8.6.0 coq-tortoise-hare-algorithm.8.5.0 coq-orb-stab.8.5.0 coq-orb-stab.8.6.0 coq-orb-stab.8.7.0 coq-orb-stab.8.8.0 coq-ott.0.26 coq-ott.0.27 coq-pi-agm.1.2.3 coq-relation-algebra.1.7.1 coq-tortoise-hare-algorithm.8.6.0 coq-traversable-fincontainer.8.5.0 coq-traversable-fincontainer.8.6.0 coq-tree-automata.8.5.0 coq-tree-automata.8.6.0 coq-tree-diameter.8.5.0 coq-tree-diameter.8.6.0 coq-unicoq.1.0.0 coq-unicoq.1.3+8.6 coq-universe-comparator.1.1.0 coq-weak-up-to.8.5.0 coq-weak-up-to.8.6.0 coq-zchinese.8.5.0 coq-zchinese.8.6.0 coq-zf.8.5.0 coq-zf.8.6.0 coq-zfc.8.5.0 coq-zfc.8.6.0 coq-zorns-lemma.8.5.0 coq-zorns-lemma.8.6.0 coq-zsearch-trees.8.5.0 coq-zsearch-trees.8.6.0

### CODE REVIEW

**Comment by gares** [comment]
@vgbl CI is essentially green, I'm about to announce to switch to opam2 in 1 month on coq-club. I still need an ACK that we will be able to publish a 1.2 version of the repo (frozen) somewhere. Can I count on you for doing this? (take a snapshot of the current master, put is somewhere, take this PR, hack the repo file with redirects, put this next to the frozen copy, run make, test with both opam1.2 and 2.x that things get fetched)?
Actually, I don't even know how we deploy this today. Is it already on github.io ?

**Comment by vbgl** [comment]
Thank you Enrico. Deployment to GitHub-Pages is not going to happen: we don’t have enough control on the server configuration. Maxime and myself will figure out soon a suitable hosting plan for the opam repositories.

Can you please tag the version to freeze? I’ll deploy it as soon as we know where.

**Comment by vbgl** [comment]
Sounds good. I’ll deploy the frozen version when you think it’s time to do so. I believe that by that time we’ll have sorted out the hosting issues.

**Comment by gares** [comment]
rebased on top of master, @vbgl I think we should tag master and merge this next week if you have time to put the contents of the tag somewhere.

**Comment by gares** [comment]
ping @vbgl

**Comment by vbgl** [comment]
I’ll put a copy of the tagged state at “coq.github.io/opam1” or something like that. I can do it today. We’ll also need to update the documentation on the main website.

**Comment by gares** [comment]
What we should try to do (and I don't have time today, not tomorrow) is to see how redirection works.
I imagine a `repo` file such as
```
opam-version: "2.0"
browse: "https://coq.inria.fr/opam/www/"
upstream: "https://github.com/coq/opam-coq-archive"
redirect: [
  "https://coq.github.io/opam-coq-archive/released-$GIT_HASH" {opam-version < "2.0~"}
]
archive-mirrors: "cache"
stamp: "ec180e2c"
```
at the root of https://coq.inria.fr/opam/released/ does it, but I did not try, and I don't know what the last two lines mean.

**Comment by vbgl** [comment]
I’m not sure I understand. Do we need to store a copy somewhere or is putting a tag enough?

**Comment by gares** [comment]
We need to store a copy. We also need to test if the redirect file above works (otheriwise there is not point in storing a 1.2 compatible copy of the archive).

**Comment by gares** [comment]
I named the URL of the old copy using $GIT-HASH, but it could be as well a name of a tag (but should be something that signals which version of the repo is frozen)

**Comment by gares** [comment]
I've tested and updated the repo file, redirection works (but the place I point to is empty).
@vbgl if you snapshot the current contents of coq.inria.fr/opam/released there I will then merge

**Comment by vbgl** [comment]
Thank you Enrico. I’ll do the copy tomorrow.

As I have no control over the server at coq.inria.fr, the URL will be: coq.github.io/opam1 (or feel free to suggest something better, but coq.github.io will have to stay).

**Comment by gares** [comment]
Ok, I picked a longer URL in my last commit, see the release file

**Comment by vbgl** [comment]
This means that the snapshot will be in the `docs/released-opam1.2/` of the **master** branch of this repository.

**Comment by vbgl** [comment]
My bad. It can be at the root of the `gh-pages` branch. I’ll to this.

**Comment by vbgl** [comment]
Done.

**Comment by gares** [comment]
Can you tell me the precise url? The current `repo` file points to:
  https://coq.github.io/opam-coq-archive/released-opam1.2/urls.txt
and opam does not find the file (note that this file is not in the repo, it is generated a deployment time by the Makefile that calls opam admin).

**Comment by vbgl** [comment]
http://coq.github.io/opam-coq-archive/released-opam1.2/

This should now have all you need.

**Comment by gares** [comment]
it works! I'll merge this one ASAP and send a message on coq-club

**Comment by gares** [comment]
@sacerdot we just switched to opam 2.0 format. You can find in the commits we merged the precise list of packages that were removed

**Pull request merged**
