### PR TITLE
Add paramcoq in extra-dev

### PR DESCRIPTION
**Pull request by proux01**

### CODE REVIEW

**Comment by gares** [comment]
please fix the errors given by the linter

**Comment by proux01** [comment]
fixed

**Comment by proux01** [comment]
Thanks!

Would it be possible to update https://coq.inria.fr/opam/extra-dev/index.tar.gz ?

The repo file reads `stamp: "2019-02-04 13:20"` and there seems to be two missing packages (coq-mathcomp-real-closed and coq-paramcoq) and one renamed (from coq-fiat to coq-fiat-core)

**Comment by gares** [comment]
@mattam82 is there something not working in the cron job? Looks like opam admin is not doing its job.

**Comment by mattam82** [comment]
Let me check

**Comment by mattam82** [comment]
You removed extra-dev from PKGIDX but did not add it to the SUITES variable in the Makefile. I fixed that, the index seems to be updated correctly now.

**Comment by proux01** [comment]
Thanks!

**Pull request merged**
