### PR TITLE
add ott 0.29 package and minor update of extra-dev ott package

### PR DESCRIPTION
**Pull request by palmskog**

### CODE REVIEW

**Comment by gares** [comment]
The master branch contains ocamlgraph, that it LGPLv2 http://ocamlgraph.lri.fr/
If it is dead code, I'd be more comfortable with an request for removal on the upstream repo (they cite it in the README, but I could not find it in the main Makefile).

**Comment by palmskog** [comment]
But the ocamlgraph code is never touched or installed in this package. I thought the license pertained to the actual library of the package, rather than the whole archive.

For example, if I distribute a GPL3 library in an archive contains non-library documentation under some Creative Commons license, does every package of the library therefore need to be stamped with "part GPL3, part CC"?

**Comment by gares** [comment]
I guess you are right. Still I'm wondering why the archive is there in the first place...

**Comment by palmskog** [comment]
Thanks, I will take it up with the maintainers at some point. I have some ideas for that project like switching to dune and other automation, addressing the ocamlgraph bundling goes on the list for sure.

**Pull request merged**
