### PR TITLE
Update dependencies of coq-mathcomp-dioid.dev

### PR DESCRIPTION
**Pull request by proux01**

### CODE REVIEW

**Comment by gares** [comment]
Hum, I guess recent updates to HB broke it

**Comment by proux01** [comment]
I'll remove the `| "dev"` for now. I'll put them back when mathcomp will be ported (I have a branch of dioid working with the hierarchy-builder brnach of mathcomp).

**Comment by gares** [comment]
You are living on a razor blade ;-)

I'm fine merging a package in .dev which "today" does not work (since it is the whole point of .dev package to find out problems).
If the right deps are with the `| dev`, you can put it back.

**Comment by proux01** [comment]
> You are living on a razor blade ;-)

Indeed, I should have said "was working with the hierarchy-builder branch two weeks ago" ;)

> I'm fine merging a package in .dev which "today" does not work (since it is the whole point of .dev package to find out problems).
> If the right deps are with the `| dev`, you can put it back.

So, opam is not able to find a solution in the "build:any" CI job, no idea why. We can probably merge it as is without bothering too much since it is just a dev package.

**Pull request merged**
