### PR TITLE
New release of TLC.

### PR DESCRIPTION
**Pull request by fpottier**
New release of TLC, for Coq 8.6.

### CODE REVIEW

**Comment by herbelin** [comment]
@fpottier: I had a (very quick) look and it looks like there is a lot to learn in this library. I don't know where to ask, so I'm doing it here. Two side-comments in passing:
- In [LibTactics.v](http://www.chargueraud.org/viewcoq.php?sFile=softs%2Ftlc%2Fsrc%2FLibTactics.v), is there a reason I don't see for defining notations for `exists` with up to 10 variables and not use a single recursive notation?
- The three "Use" Tutorial links at http://www.chargueraud.org/softs/tlc/ do a 404.

**Comment by fpottier** [comment]
Hello Hugo -- you can ask questions on the TLC mailing list, `tlc-users@lists.gforge.inria.fr`,
or send them directly to Arthur (@charguer).

**Comment by charguer** [comment]
@herbelin: you were looking I think at deprecated files that I forgot to update on my webpage. The gitlab hosts the latest version of the file. I'll look into presenting the library at a Coq WG.

**Comment by herbelin** [comment]
Hi @charguer,

Thanks for the news. I still did not have time to look closely at this version of TLC but I'm looking forward your presentation.

About the web site, didn't you change the style since two days ago? I don't know if it is important but I still see a 404 on the links at http://www.chargueraud.org/teach/coq (which is not about TLC though).

For the opam package, I don't know either how important it is but don't you want the `homepage` field to link to http://www.chargueraud.org/softs/tlc/ rather than to https://gitlab.inria.fr/charguer/tlc which does not seem to provide a very human-friendly structure.

Hugo

**Pull request merged**
