### PR TITLE
VST.dev: "IGNORECOMPCERTVERSION=true"

### PR DESCRIPTION
**Pull request by SkySkimmer**
cf https://github.com/PrincetonUniversity/VST/pull/658

### CODE REVIEW

**Comment by gares** [comment]
Thanks!

**Comment by palmskog** [comment]
The only failure is because CompCert doesn't work yet on OCaml 5. Should we maybe mark the CompCert `dev` package as incompatible with OCaml 5 @MSoegtropIMC?

**Comment by MSoegtropIMC** [comment]
@palmskog : it definitely makes sense to represent the facts in opam. Should I do a PR and CC Xavier?

**Comment by SkySkimmer** [comment]
see also https://github.com/AbsInt/CompCert/issues/477

**Comment by palmskog** [comment]
@MSoegtropIMC let's wait for someone to react to https://github.com/AbsInt/CompCert/issues/477 before we change `coq-compcert.dev`. In the meantime, none of the of the OCaml 5 stuff is directly related to VST, so let's merge this PR.

**Pull request merged**
