### PR TITLE
Fix coq-unimath for opam 2

### PR DESCRIPTION
**Pull request by clarus**

### CODE REVIEW

**Comment by palmskog** [comment]
No idea why 4.02.3 fails here, and log is uninformative. @gares any advice?

**Comment by gares** [comment]
I think it is spurious, you can see a detailed log by browsing the job artifacts (click Details, then on the right Job Artifacts -> Browse). The ktheory one fails to untar the downloaded archive. I let you restart Ci (if I do I believe the logs are lost, and I'd like you to find them)

**Comment by palmskog** [comment]
@gares you're right that's it's probably spurious (and per my inspection indeed due to failing to untar an archive). However, I don't seem to have any rights to restart a job.

**Comment by gares** [comment]
Tell me your login on gitlab and I'll try to fix the permission today

**Pull request merged**
