### PR TITLE
no upper bound for coq version in multinomials

### PR DESCRIPTION
**Pull request by CohenCyril**

### CODE REVIEW

**Comment by CohenCyril** [comment]
How can fixing just the dependency version can lead to this error message?
```
builds/coq/opam-coq-archive/released/packages/coq-mathcomp-multinomials/coq-mathcomp-multinomials.1.1/opam: Errors.
             error 57: Synopsis and description must not be both empty
```

**Comment by silene** [comment]
Because the whole file is checked, and it contains neither `synopsis` nor `description` fields. Just add the first (and only) line of the `descr` file as a `synopsis: "..."` field (and remove the final stop, otherwise you will get another warning).

**Comment by CohenCyril** [comment]
@silene everthing is ok now :smile: thanks!

**Comment by CohenCyril** [comment]
Hi @gares @silene may I merge PR that pass the CI myself?

**Comment by gares** [comment]
I made a mistake, there was an issue with this PR that we wanted to eavluate before the merge.
In particular you did submit a 1.2 format opam file, while the archive is now in 2.0 format.

**Comment by gares** [comment]
sorry, it is fine, I'm just tired ;-)

**Comment by CohenCyril** [comment]
thanks

**Pull request merged**
