### PR TITLE
coq-simple-io.dev

### PR DESCRIPTION
**Pull request by liyishuai**
per QuickChick/QuickChick#129

### CODE REVIEW

**Comment by Lysxia** [comment]
Would it be possible to make extra-dev and Coq CI to point to the branch named `dev`? @liyishuai @ejgallego

**Comment by liyishuai** [comment]
QuickChick uses `dev` to develop on `coq.dev` (compared to `8.8`); `master` branch accepts PRs from Coq developers. Maybe this could be some convention?

**Comment by Lysxia** [comment]
The least surprising setup for drive-by contributors is for active development to happen on the default branch that they get first when they clone the repo. So I'm tempted to promote the opposite convention making `dev` the common name for what Coq CI and extra-dev should point to, and keep `master` as the default branch for development simply because that's git's default (I know you can change it, but that's one more step than doing nothing).

**Comment by Lysxia** [comment]
Thanks, that's very helpful! For coq-simple-io I will manage better with separate branches.

**Comment by ejgallego** [comment]
Cool, please submit a PR or Issue when Coq is ready for the update.

**Pull request merged**
