### PR TITLE
fix(coq-elpi.dev): Update spec w.r.t. [1], also allowing coq.dev

### PR DESCRIPTION
**Pull request by erikmd**
[1] = https://github.com/LPCIC/coq-elpi/blob/master/coq-elpi.opam

Cc @gares: FYI this PR appears to be necessary given this failure:

* job https://gitlab.inria.fr/math-comp/math-comp/-/jobs/3343343
* in pipeline https://gitlab.inria.fr/math-comp/math-comp/-/pipelines/844235

~~Do you approve the two commits? or just the coq-elpi.dev commit?~~ (**edit:** see [this comment](https://github.com/coq/opam-coq-archive/pull/2668#issuecomment-1675161366))

Cc @palmskog

### CODE REVIEW

**Comment by erikmd** [comment]
On second thought according to [opam-coq-archive's CI](https://gitlab.com/coq/opam-coq-archive/-/jobs/4850237494),

coq-elpi.dev compiles with coq.dev, *unlike* coq-elpi.1.19.0

I force-pushed to fix this accordingly.

**Comment by erikmd** [comment]
@palmskog the CI is green now :heavy_check_mark: so I think the PR is mergeable now 👍

**Comment by palmskog** [comment]
@erikmd I can merge, but unfortunately it will not be deployed properly until the website gets back. So maybe best to wait

**Comment by erikmd** [comment]
Indeed @palmskog, I agree.

I just posted a related comment in the-PR-that-I-will-merge-just-after-this-one:
https://github.com/math-comp/math-comp/pull/1057#issuecomment-1675213434

**Pull request merged**
