### PR TITLE
Allow Coq 8.16 for packages which support it

### PR DESCRIPTION
**Pull request by MSoegtropIMC**
also allow mathcomp 1.15 for 2 packages

Skip CI for packages which only change the allowed coq version:

ci-skip: coq-compcert coq-compcert-32 coq-deriving coq-iris coq-libhyps coq-math-classes coq-mathcomp-algebra-tactics coq-mathcomp-zify coq-ott coq-record-update coq-simple-io coq-compcert-32.3.11 coq-compcert.3.11 coq-deriving.0.1.0 coq-extructures.0.3.1 coq-iris.3.6.0 coq-libhyps.2.0.5

CI is kept for coq-reglang and coq-extructures.

Note on coq-math-classes: it might seem odd to enable 8.16 for a package with version 8.15, but it did happen before that a release spanned two versions of Coq.

### CODE REVIEW

**Comment by gares** [comment]
CI did timeout, so I did re-run it (from the gitlab interface which should give us 24h timeout) and added to ci-skip the packages which did actually pass. I'm not so sure your previous syntax is OK.

**Comment by Zimmi48** [comment]
> Note on coq-math-classes: it might seem odd to enable 8.16 for a package with version 8.15, but it did happen before that a release spanned two versions of Coq.

Not odd to me. It just happens that for old coq-contribs or packages that decided to follow a similar versioning scheme, the version numbers are based on the latest Coq version number at the time of the release. Yet, in coq-community, we strive to support multiple Coq releases at once, and avoid creating new releases for no reason (beyond the bump in the version number) like has frequently happened with coq-contribs.

**Comment by Zimmi48** [comment]
> CI did timeout, so I did re-run it (from the gitlab interface which should give us 24h timeout)

Does that still work? I thought this was based on the pyrolyse runner, which is no offline.

**Comment by gares** [comment]
well, maybe we get a 3h timeout then

**Comment by MSoegtropIMC** [comment]
@gares : you could disable CI for all packages (as I did - just didn't give the versions as I should), since it is anyway not tested with Coq 8.16 - it does not exist in the released folder as yet.

**Comment by MSoegtropIMC** [comment]
P.S.: I tested all packages in Coq Platform preview with 8.16+rc1.

**Pull request merged**
