### PR TITLE
added package for ssreflect 1.5 patched for Coq 8.5beta3

### PR DESCRIPTION
**Pull request by tebbi**
I patched ssreflect 1.5 to build with Coq 8.5beta3 and created an opam package containing this patch.

Best,
Tobias

### CODE REVIEW

**Comment by gares** [comment]
Thanks!  I'll look at this tomorrow.

**Comment by tebbi** [comment]
Oh, I just found the https://github.com/math-comp/math-comp repository I was not aware of. And there, all of this has been done already a long time ago. -.-
It is hard to find the repo if you google ssreflect. A link from http://ssr.msr-inria.inria.fr/ would be super helpful.

**Comment by clarus** [comment]
+1

**Comment by maximedenes** [comment]
Ok, the link is there now (except the website is down at the moment). So closing this PR, thanks!

**Pull request closed without merging**
