### PR TITLE
adding new release of unicoq with some bugfixes

### PR DESCRIPTION
**Pull request by beta-ziliani**

### CODE REVIEW

**Comment by palmskog** [comment]
I was able to replicate the build problems locally on OCaml 4.09.0, and the problem seems to be this line: https://github.com/unicoq/unicoq/blob/master/Makefile.local#L1 

When this line is gone, it builds fine. Dune builds work fine regardless, since they ignore `Makefile.local`.

You can either do a new release or create a patch to be applied by OPAM.

**Comment by palmskog** [comment]
@beta-ziliani it seems there is a build error only on 4.09.0:

```
Error: while loading /builds/coq/opam-coq-archive/opam-root-4.09.0-2.0.5-sandbox/4.09.0/.opam-switch/build/coq-unicoq.1.3.2+8.10/src/unicoq.cmxs:
The module `Int_misc' is already loaded (either by the main program or a previously-dynlinked library)
```

This could be due to build parallelism flakiness, you may want to try removing the `-j%{jobs}%` from the OPAM file.

**Comment by beta-ziliani** [comment]
that wasn't the reason :( installing 4.09 and see what can it be

**Comment by beta-ziliani** [comment]
compiling manually (works):
https://gist.github.com/beta-ziliani/83170ea2c49a694f0514b42d23a2d9aa

compiling with opam:
https://gist.github.com/beta-ziliani/086d608b89e326820127c4a8bbc16a21

**Comment by beta-ziliani** [comment]
I'm loosing it here, if I point opam to the local directory (master-8.10 exactly where the tag is) it works fine :(

**Comment by beta-ziliani** [comment]
I don't know how to proceed. The same line that makes it work in some cases seem to be problematic for other releases of Ocaml.

**Comment by palmskog** [comment]
You can always set OCaml < 4.09.0 in the OPAM file and work on a solution later (e.g., start to use pure dune builds). Most Coq users are probably on 4.07.1 or 4.05.0 anyway.

**Comment by beta-ziliani** [comment]
good idea. I wonder what can be happening, it is really frustrating...

**Comment by palmskog** [comment]
I tested locally again, and it seems the recently added line is to blame for the failures:
```
CAMLPKGS = $(if $(filter %.cmxa,$@),,-package num)
```
Specifically, I get the same error as reported by OPAM when compiling outside OPAM when the line is present. However, when the line is removed, I can both compile manually and install via OPAM.

**Comment by palmskog** [comment]
It also looks like the problem manifests on OCaml >= 4.08.0, hence CI still fails. I suggest you either adjust the bound down again (`< 4.08`) or remove the line in `Makefile.local` and re-release or patch.

**Comment by beta-ziliani** [comment]
the problem is that I need that line for some other build cases (I don't know why, but with a 4.07 it compiled only WITH that line). So I will adjust the bound and make a separate release for >= 4.08...

**Comment by gares** [comment]
I've merged a PR in coq to fix this problem. You should also consider using a .mlpack instead of .mllib (same syntax, just rename the file)

**Comment by beta-ziliani** [comment]
that doesn't work for some reason. I can compile Unicoq no problem, but then I cannot import it from Mtac2:
```
Error: while loading /home/beta/projects/Mtac2/src/MetaCoqPlugin.cmxs:
error loading shared library: /home/beta/projects/Mtac2/src/MetaCoqPlugin.cmxs: undefined symbol: camlMunify
```

**Comment by gares** [comment]
I think you need to add a `open Unicoq_plugin` (or something like that). Unfortunately the build system puts the .cmi files in the path, so you get the error at link time, instead of compilation time. With the .mlpack all OCaml modules part of unicoq are put inside a toplevel module.

**Pull request merged**
