### PR TITLE
Using the NamingScheme familiar to Coq users to name opam packages

### PR DESCRIPTION
**Pull request by herbelin**
I attach a proposal which seizes the opportunity of the requirement to rename the packages to (re)use the NamingScheme familiar to Coq users. Additionally, this naming scheme generally satisfies the following properties:
- For packages which are libraries, most of the time, the name of the package is the name of the module to require, so that, virtually, "From Foo Require Import Bar" could simply look into an appropriate opam repository, finds Foo, installs it, and requires Bar from it.
- Use of capitals allows for more ways to split words: not only _ and -, but also capitalization; use of capitals gives more information on names such as AACTactics, CoLoR, CompCert, OCaml, CUnit, MathComp, etc.

Analyzing the naming schemes spontaneously used for new packages, it is interesting that a qualifier like we had with the "Site" directory of contribs is spontaneously coming back taking the form of a vendor name, like in coq:mathcomp:solvable or of a mixed vendor-topic name as in coq:concurrency:pluto but also under the form of a reference to the plugin used, as in coq:equations:fpred or coq:ssr:elliptic-curves.

Here are some exceptions to the "Require PackageName" schemes:
- CompCert which installs as compcert, using the name it has in contribs
- MathComp-Some_name which installs as mathcomp/some_name (extra-dev only)
- LC which installs in lc
- FPMods which installs in fpmods (btw, couldn't it be called less enigmatically FinitelyPresentedModules?)
- CoqOfOCaml installs to OCaml
- Equations-Fpred installs to Fpred
- Concurrency-System in Concurrency

Analyzing the packages shows that we have three kinds of packages (sometimes in combination):
- plugins
- libraries (or end result)
- executable programs developed in Coq

In the later category, here are packages with purely executable programs (to be installed in bin, not in user-contrib):
- Io-HelloWorld
- Concurrency-Pluto
- Concurrency-Proxy
- Opam-website (btw, why "Opam" in the name?)
- a couple of programs preexisting the contribs (e.g. BDD-based tautology solver)
I wonder whether they should not be in a separate repository explicitly marked e.g. as certified-software, since they are directly usable as programs.

I wonder whether we should not be more explicit on what is library, what is plugin, what is end result, so that when someone new to Coq looks at the opam Coq website, he/she can directly grasp the intent of the package (compare e.g. to names of the form libfoo used in Debian). After all, we have to be conscious that the naming choices we are now making might influence the whole way the package distribution grows in the future.

I did not test the compilation.

### CODE REVIEW

**Comment by gares** [comment]
Hello, the patch is quite long but as far as I can read the pattern is coq:foobar -> FooBar. My question is: why the "coq:" namespace has gone?

**Comment by herbelin** [comment]
The idea is that the coq: namespace is not needed. I guess your question is about coq-shell and I thought I had posted a comment about it but I don't find it. My proposal is that coq-shell simply looks directly into the $OPAMROOT/{released,extra-dev}/packages directories (and possibly other directories) to find what are the Coq packages, rather than using opam search or grep with a regexp. What do you think of this alternative?

**Comment by gares** [comment]
Oh, I did not have in mind coq:shell, but yes, I guess there are other ways to filter out non coq packages.  Why the namespace is not needed? In coq:foobar we are sort of sure that if a conflict arises, then it is solvable within the "coq world".  Without coq:, a Coq package may conflict with a non Coq package (a standard OPAM package, since you can't really hide the main OPAM repository).

For example "containers" exists both as "coq:containers" and simply "containers" (an OCaml library providing containers).  With your patch we sould have Containers (for Coq) and containers (for OCaml).

**Comment by herbelin** [comment]
The standard opam repository does not have to be present (you can do "opam repo remove default" to remove it). So, you are saying that users who want to have simultaneously both the standard OCaml repository and the standard Coq repository on case-insensitive file systems in the same opam root might have to do some contortions if they want to install one of those packages which share the same name up to case (assuming that OCaml packages have a lowercase initial letter and that Coq packages have a capital initial letter). That's right and I don't know what to think about it.

**Comment by mattam82** [comment]
For sure we don't want to make it incompatible with the standard opam repository, and having Containers and containers be two different packages surely is confusing. I thought the coq: namespace was good, as Enrico says, to maintain a kind of world of our own. "Coq-" could replace it.

**Comment by herbelin** [comment]
I think it depends on what are the aims for opam. If there are objectives for opam to be a universal package manager independent of a particular programming language, as I've been told there are, we should think as opam as a package manager for Coq, and not opam as a package manager for OCaml which is used for Coq. If otherwise opam is a package manager for OCaml which we use also for Coq, then, it is normal that Coq only takes a subset of the OCaml name space, and that we use a Coq- prefix.

**Comment by clarus** [comment]
To me, since our runtime is OCaml (for Coq, the plugins and most of the extractions), it is simpler to reuse their repository, and get for free all the OCaml version, `camlp4`, `camplp5`, `lablgtk`, ... correctly configured and up-to-date.

To put it differently, in my opinion, we should first have a Coq which does not depend on OCaml, and then have a package manager which does not depend on OCaml. But this would be really long term.

**Comment by herbelin** [comment]
Yes, it is natural to find the ocaml, camlp4/5, lablgtk as well as various packages possibly needed for Coq plugins on the OCaml repository and I don't see reasons not to be dependent on it.

But this is independent of my question. If ever the objective of opam is to be seen as a general package manager which can be used indifferently for Coq, for OCaml or for any other language, including the possibility of using it for a combination of languages, the question is not a question of how to isolate a subset of the name space for Coq, but the question is an instance of the more general question of dealing with clashes when mixing different repositories being managed independently. I don't know if opam alone is able to address this question automatically (for instance, I see no way to qualify a package name with a repo name), but I see how to technically address it manually by interleaving calls to "opam repo add", "opam repo remove" and "opam install", since, apparently, when a package is installed, the repo it was coming from can be removed without the information about the installed package being lost.

I'm conscious that I may look like placing my discourse into a perspective that immediate pragmatism would not require, but I don't think it can harm to ask ourselves these questions.

**Comment by herbelin** [comment]
Considering that what I perceived as a part of the identity of Coq (use of capitals, control of the name space) and that the technical arguments coming with this perception (a more expressive naming language, ability to use "From ThisPackage Require bar" as an implicit way to install "ThisPackage") are apparently not perceived as important by what seems to be a quasi-unanimity of the other developers, considering that even "senior" people like Guillaume M. expressed a preference for lowercase, and that another "senior" person like Frédéric Blanqui does not seem to care about preserving the lower-/upper- "colors" of the name of his package, as well as so seems to be the case for the names CompCert and Ssreflect, I'm withdrawing this pull request.

**Pull request closed without merging**
