### PR TITLE
add coq-htt.dev in extra-dev

### PR DESCRIPTION
**Pull request by palmskog**
@clayrat OK with you to add this? The main motivation is for CI use (Disel).

### CODE REVIEW

**Comment by clayrat** [comment]
Is there any maintenance burden with this, or should we just push two opamfiles for a new release from now on?

**Comment by palmskog** [comment]
This is a git-based package, so essentially the only time it needs to be updated is when dependency requirements change (e.g., a new dependency is added). Also, the `extra-dev` opam repo is mostly used by advanced users for CI purposes, rather than for regular Coq development, so support issues with the package should be very few.

**Comment by clayrat** [comment]
All right then!

**Comment by palmskog** [comment]
For the record, `coq-fcsl-pcm` also already has a package like this, which Anton and I both helped maintain: https://github.com/coq/opam-coq-archive/blob/master/extra-dev/packages/coq-fcsl-pcm/coq-fcsl-pcm.dev/opam

**Pull request merged**
