### PR TITLE
Update coq-mathcomp-multinomials & coq-ssr-elliptic-curves to take Coq 8.7 into account.

### PR DESCRIPTION
**Pull request by strub**

### CODE REVIEW

**Comment by gares** [comment]
May I just point out that you have packages named "coq-mathcomp-X" and also "coq-ssr-Y" ... is it intended?

**Comment by strub** [comment]
The multinomials library is under the "mathcomp" organization. This is not
that case for the elliptic curves one.

2017-10-20 10:17 GMT+02:00 Enrico <notifications@github.com>:

**Comment by gares** [comment]
OK, but why ssr then? I mean, I see why, but it is not the case that projects using ssr are called coq-ssr-*

**Comment by strub** [comment]
The project is quite old. This was more or less the case at that time :) I
don't mind changing the name if you've a proposition.

2017-10-20 11:50 GMT+02:00 Enrico <notifications@github.com>:

**Pull request merged**
