### PR TITLE
Packaging coq-flocq-quickchick version 1.0.0

### PR DESCRIPTION
**Pull request by p3rsik**
This package provides binary_float generators for Flocq library and, also, it provides sub-generators to create custom generators to test edge-cases of you software. This is just small and convenient tool to use when you want to test Flocq related functions using QuickChick.

### CODE REVIEW

**Comment by silene** [comment]
Did you really mean to commit all the original files?

**Comment by p3rsik** [comment]
I think I made a mistake here. The 3 files url, descr and <package-name>.opam is all that is needed, am I correct?

**Comment by silene** [comment]
Actually, just the `opam` file is sufficient. The content of the `url` and `descr` files should be embedded into it. (That is one of the main differences between Opam 1 and Opam 2.) Look at the other packages for an example.

**Comment by p3rsik** [comment]
Thank you, cleaned repo from unnecessary files

**Comment by palmskog** [comment]
@p3rsik please rename the package file to just `opam`.

**Pull request merged**
