### PR TITLE
Remove data that belongs to `coq/www`

### PR DESCRIPTION
**Pull request by vbgl**
See https://github.com/coq/www/pull/87

### CODE REVIEW

**Comment by Zimmi48** [comment]
You should fix the link in the README and possibly add others to the pages that are moved. The current way of doing was odd but add this advantage that the doc was easily browsable in the repo as well.

**Comment by gares** [comment]
This is OK for me, but I'm not sure about the timing. Is the new site online already? @vbgl do you have the rights to merge this yourself when the time is right?

**Comment by vbgl** [comment]
I guess that coq/www#87 should be merged first. It seems that I have merging rights on this repository.

**Comment by maximedenes** [comment]
The other PR was merged, so merging this one too.

**Pull request merged**
