### PR TITLE
new relase of UniCoq for 8.6

### PR DESCRIPTION
**Pull request by beta-ziliani**

### CODE REVIEW

**Comment by mattam82** [comment]
The Travis jobs are stale, so you maybe have a user Travis running?

**Comment by beta-ziliani** [comment]
Sorry, what does it mean? I have a user in Travis, yes.

**Comment by mattam82** [comment]
If you show me that this commit passed on your user Travis I can push the
merge button lightheartedly
Le ven. 1 déc. 2017 à 14:58, Beta Ziliani <notifications@github.com> a
écrit :

**Comment by beta-ziliani** [comment]
how do you do that? I have the fork, I turn it on on Travis, but no build is being done. more general, is that a reasonable request to make to contributors? willn't that prevent people from contributing if they have to go through all the travis thing?

**Comment by mattam82** [comment]
Ideally our global travis would do it but it's overloaded right now, we're
looking at solving that issue. You can request a build, or just push a
commit to the branch somewhere in Travis.

**Comment by beta-ziliani** [comment]
It's currently running (testing my two PRs at the same time). According to Travis, the one in Linux is green.

**Comment by beta-ziliani** [comment]
The MacOs builder is running for an hour and a half. In any case, the green is there.

**Comment by RalfJung** [comment]
This now also contains Mtac2?

**Comment by beta-ziliani** [comment]
Nope, PR #236 does. Both can be safely merged (ejem @mattam82 ).

**Comment by RalfJung** [comment]
<https://github.com/coq/opam-coq-archive/pull/234/files> quite clearly shows that this PR contains Mtac2.

**Comment by beta-ziliani** [comment]
darn, I tried to do this cleanly and failed. ok, both are here.

**Pull request merged**
