### PR TITLE
Packages for PluginUtils and LtacIter

### PR DESCRIPTION
**Pull request by gmalecha**

### CODE REVIEW

**Comment by clarus** [comment]
Thanks! Just before merging, I think the version numbers should be `1.0.0` without the `8.5`, since this information is about the dependencies and is in the `depends` field.

**Comment by gmalecha** [comment]
Alright. I will fix and update the pull request.

**Comment by gmalecha** [comment]
This fixes the version numbers.

**Comment by clarus** [comment]
OK, thanks!

**Pull request merged**
