### PR TITLE
Package coq-mathcomp-word 2.0

### PR DESCRIPTION
**Pull request by eponier**

### CODE REVIEW

**Comment by eponier** [comment]
@strub for your information

**Comment by palmskog** [comment]
@MSoegtropIMC if this package is included in the Platform, then this version (2.0) is a better choice, since it has `logpath` consistent with its package name (`mathcomp.word` rather than the possibly-confusing `CoqWord`).

**Comment by MSoegtropIMC** [comment]
@palmskog : thanks - I will reopen the picking issue.

**Comment by MSoegtropIMC** [comment]
Actually the new versions breaks `coq-mathcomp-algebra-tactics` - there is a name conflict about file `ssrZ` with zify:
```
===============================================================================
/Users/runner/.opam/log/coq-mathcomp-algebra-tactics-66058-b80608.out
===============================================================================

    42	File "./theories/ring.v", line 5, characters 0-39:
    43	Error: Required library ssrZ matches several files in path (found
    44	/Users/runner/.opam/__coq-platform.2022.09.0~8.16~2022.09~beta1/lib/coq/user-contrib/mathcomp/zify/ssrZ.vo and
    45	/Users/runner/.opam/__coq-platform.2022.09.0~8.16~2022.09~beta1/lib/coq/user-contrib/mathcomp/word/ssrZ.vo).
```
This did work fine with 1.1.

**Comment by strub** [comment]
Maybe should we use the tactic from that package directly. But this means releasing a 2.1. I can take care of this.

**Comment by MSoegtropIMC** [comment]
> Maybe should we use the tactic from that package directly. But this means releasing a 2.1. I can take care of this.

Yes please. If you use zify, please make the opam package depend on the zify package and assume it is installed.

**Pull request merged**
