### PR TITLE
fix iris checksums after repository move

### PR DESCRIPTION
**Pull request by RalfJung**

### CODE REVIEW

**Comment by gares** [comment]
I'm fine with the change but I'm curious about the second file (3.1.0). Why did the md5 change? It seems the file was "just moved"

**Comment by gares** [comment]
Said otherwise, you did not simply move the repo, did you?

**Comment by RalfJung** [comment]
We simply moved the repo, but the tarball is auto-generated by GitLab and the toplevel directory contains the repo name.  This means that moving the repo actually changes the checksums of the archives.

**Comment by gares** [comment]
Oh I see, you removed the `-coq`. It's all good then, thanks.

**Pull request merged**
