### PR TITLE
packages for Mtac2 1.1 for Coq 8.8 and 8.9 and Unicoq 1.3 for Coq 8.9

### PR DESCRIPTION
**Pull request by beta-ziliani**

### CODE REVIEW

**Comment by silene** [comment]
```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - coq-unicoq.1.3+8.9:
            https://github.com/unicoq/unicoq/archive/v1.3-8.9.tar.gz (Bad checksum, expected md5=d41d8cd98f00b204e9800998ecf8427e)
```

**Comment by beta-ziliani** [comment]
@silene Sorry for the mess, now it should be OK

**Comment by beta-ziliani** [comment]
I see that the linter complains about the lack of description. What is the right way to proceed? @silene

**Comment by silene** [comment]
You can just add the first line of the `descr` files as a `synopsis: "..."` line in the `opam` files. That change is not strictly needed as long as this part of the repository is based on opam 1 (which still uses `descr` files), so I am merging the pull request; but this will be mandatory for new packages once the switch to opam 2 has been completed.

**Pull request merged**
