### PR TITLE
Providing opam files for those contribs which compile with Coq 8.7

### PR DESCRIPTION
**Pull request by herbelin**
Split of #496.

### CODE REVIEW

**Comment by gares** [comment]
Now that I've merged #519 could you please rebase and re-run CI with no timeout?

**Comment by herbelin** [comment]
According to https://coq-bench.github.io/clean/Linux-x86_64-4.05.0-1.2.2/released/, compilation in 8.6 failed only for uninstall of lesniewski-mereology (plus an enigmatic interruption of log for projective geometry).

I just fixed installation of lesniewski-mereology. I also updated the source tar.gz for bertrand to fix a compilation problem which I overlooked in 8.7 (thanks to @zimmi48 for noticing it).

So, this seems to be even more ready to be merged than #499 was.

**Comment by herbelin** [comment]
Hi, is there something I should do about this PR (and about #501)?

**Comment by Zimmi48** [comment]
On Gitter, @gares said:

>These two PR fail CI as far as I can tell. The problem is that they touch 100 packages, and if one fails then the entire PR fails. The PR that got in was still failing but, IIRC, using another CI (on coq.io) @herbelin figured out that only few packages were broken, so we merged the PR and fixed the package later on. If you want some package to get in soon, IMO, you should open a separate PR.
The PRs also need a rebase, it seems

**Comment by herbelin** [comment]
@zimmi48: I don't know what conclusion to draw from @gares' message. Cannot we do like for #499, i.e. we merge, check `coq.io` and fix afterwards the packages which may have to be fixed. Since I already fixed for 8.7 the only package that was failing in 8.6 (lesniewski-mereology), the bet is that no packages will have to be fixed.

I could split the PR into more pieces, but I'm unsure that it is worth the burden (compared to fixing the packages a posteriori if ever this is really needed).

**Comment by herbelin** [comment]
Ah, I see. There is still a problem with Bertrand which I thought was solved.

**Comment by herbelin** [comment]
@palmskog: Out of habit, I built opam packages for developments which are now under coq-community. This is the case e.g. of atbr and huffman. However, it does not seem right that these packagings are built independently of the maintainers of the corresponding repositories  (respectively @tchajed and you if I'm correct). On the other side, that would be nice to have opam packages produced automatically for coq-community packages. Are there plans in this direction?

@Zimmi48 pointed me to the opam files put in the coq-community repositories. Are there plans to provide, say, an automatic `opam publish` for these packages?

I also wonder what to do with the other coq-contribs packages. I could also add an `opam` file in each repository so that the same method used in coq-community can be applied to coq-contribs too.

In any case, I guess that I should remove the atbr and huffman entries from this PR? Or does it help that I keep them?

**Comment by palmskog** [comment]
@herbelin I don't mind that you're adding packages for these old releases from the time before the projects were moved to Coq-community. Regarding OPAM files, I believe that our template for them in Coq-community is reasonably complete. What is missing is the automation to actually add a release date and run the `opam publish` command. I believe we can use the upcoming 8.9 release of Coq to drive more automation/scripting in this direction, since the Coq release should imply new releases for all Coq-community projects.

Regarding other Coq contribs, I wouldn't mind if we added `meta.yml` files for them and used those to generate `opam` files from the template maintained in Coq-community. Maybe @Zimmi48 and I could split some contrib projects between us to write `meta.yml` for?

**Comment by Zimmi48** [comment]
>I wouldn't mind if we added meta.yml files for them and used those to generate opam files from the template maintained in Coq-community

The template should first be generalized to allow for other organizations hosting the package, or patched specifically for coq-contribs.

>Maybe @Zimmi48 and I could split some contrib projects between us to write meta.yml for?

The coq-contribs all had a `description` file. If it is deemed useful to convert this file in a `meta.yml` file for the coq-contribs as well, then we could maybe devise a script that does so automatically.

>What is missing is the automation to actually add a release date and run the opam publish command.

I suppose one of the options is to encourage maintainers to use the `date` field in their template and update it before pushing a new tag (we could even rename it into `latest-release-date` for more clarity, and use it in the README as well...). Then, I could have @coqbot automatically run opam-publish everytime someone pushes a new tag on a coq-community repository with an opam file... (pinging the maintainers in the process so that they review the PR...)

**Comment by herbelin** [comment]
> I don't mind that you're adding packages for these old releases from the time before the projects were moved to Coq-community. 

OK, then I keep them.

So, now the main CI tests are running out of time. On its side, the linter is complaining for opam-2 missing fields, but it is still ok to make opam-1 packages, right?

Do I still need to do something on my side for this PR?

@palmskog, @Zimmi48: then, when this will be working for coq-community, I'll probably switch to the same model for coq-contribs.

**Comment by gares** [comment]
> So, now the main CI tests are running out of time.

You have to manually start a pipeline on gitlab in order to have the timout being lifted. I did it for you.

> On its side, the linter is complaining for opam-2

Yes, I hope I'll find time to port all repositories to opam 2 at some point, for now ignore the error (but you can also add the fields).

**Comment by gares** [comment]
pff, timeout after 10h

**Comment by gares** [comment]
Let's put it like that:
- the PR is too big to be reviewed by a human
- it is also too big for our CI

@herbelin to me there  are two options:
- a lot of work is put into splitting it (by hand, or via tools) so that we can at least test it
- it gets merged as is, but then you make sure you have actual time to promptly fix things that may break (that, given we could not test, is likely to happen).

**Comment by herbelin** [comment]
> Yes, I hope I'll find time to port all repositories to opam 2 at some point, for now ignore the error (but you can also add the fields).

As long as the repository it is still opam 1, I prefer to keep the files as they are now.

> @herbelin to me there are two options:

> -  a lot of work is put into splitting it (by hand, or via tools) so that we can at least test it
> -  it gets merged as is, but then you make sure you have actual time to promptly fix things that may break (that, given we could not test, is likely to happen).

Your option 2 seems to mean less work... The tests on coq-bench.github.io seem to run around 9pm-10pm UTC. So, is it ok if you merge tomorrow and I fixed the failures observed on coq-bench at best tomorrow evening and at latest Saturday around noon?

**Pull request merged**
