### PR TITLE
mathcomp-analysis compiles with hierarchy-builder 1.0

### PR DESCRIPTION
**Pull request by proux01**

### CODE REVIEW

**Comment by palmskog** [comment]
The increase of upper bound to "2" looks completely arbitrary to me. It looks like a better idea to completely remove the upper bound.

Can someone involved in Hierarchy Builder (@gares @CohenCyril) comment on handling of version upper bounds generally?

**Comment by gares** [comment]
Given that Cyril is also involved in mc-analysis I guess no upper bound is reasonable for now.

**Comment by proux01** [comment]
Ok, let's remove it.

**Comment by proux01** [comment]
Thanks!

**Comment by CohenCyril** [comment]
My wild guess is that the only version to bump up the major version number would a change of syntax (which would justify an upper bound of `2`). But that's just a guess and it will happen in interaction with the devs of HB when it happens anyway. So I'm fine with no upper bound for now.

**Pull request merged**
