### PR TITLE
fixed color sources to avoid clashes with other libraries

### PR DESCRIPTION
**Pull request by fblanqui**

### CODE REVIEW

**Comment by mattam82** [comment]
I gather it's to fix the bug with older versions seen by Vadim?

**Comment by mattam82** [comment]
@fblanqui  I'm a bit surprised because the bug was about version 1.1.0 of color, not 1.2.0.

**Comment by fblanqui** [comment]
The bug would occur in 1.2.0 too I guess. So, I fixed 1.2.0. I won't fix 
1.1.0.

**Comment by mattam82** [comment]
Ok

**Pull request merged**
