### PR TITLE
Add mit-plv/engine-bench / coq-engine-bench

### PR DESCRIPTION
**Pull request by JasonGross**
This is here mostly so that we can add it to the Coq bench

### CODE REVIEW

**Comment by clarus** [comment]
Hi,

There are some errors in the build. Is that expected and should we merge anyway?

**Comment by JasonGross** [comment]
No this is not expected.  Apparently the following script fails on GitLab for reasons that are not clear to me
```bash
#!/bin/sh

set -x

lscpu
uname -a
lsb_release -a
```
I'll fix it shortly.

**Comment by JasonGross** [comment]
Now the failures are OOMs.  This is expected, as this dev takes 4.2 GB RAM.  I think we should merge anyway.

**Comment by clarus** [comment]
OK! Merged!

**Comment by JasonGross** [comment]
Thanks!

**Pull request merged**
