### PR TITLE
disable -warn-error for coq-elpi

### PR DESCRIPTION
**Pull request by gares**
This is a more drastic fix than #1642
I guess it should be recommended as a best practice in coq-community CC @Zimmi48 @palmskog

### CODE REVIEW

**Comment by Zimmi48** [comment]
What should be recommended is to build with fatal warnings in CI and locally but to build without warnings in releases (exactly what Dune does) since it enhances compatibility with future versions of Coq and OCaml which may add new warnings.

**Comment by gares** [comment]
it's a bit tricky because the opam file is both used for ci (eg coq-docker-action) and uploaded here. Here it should not have the -warn-error set. Does dune(-release) unset it in the .tbz?

**Comment by ejgallego** [comment]
> Does dune(-release) unset it in the .tbz?

opam packages for dune must use `dune build -p` which indeed unset warn-as-error. For CI I'm unsure what solution people is using.

Note that Dune 3.0 is aiming to have much improved warning support, as this is a top complain from users.

https://github.com/ocaml/dune-www/blob/0094351afadec33598574d957c35fb05b2913750/_posts/2021-02-26-dune-3-plan.md

**Comment by Zimmi48** [comment]
> it's a bit tricky because the opam file is both used for ci (eg coq-docker-action) and uploaded here. Here it should not have the -warn-error set. Does dune(-release) unset it in the .tbz?

That's a good point and probably worth an issue on the Docker-Coq-Action repo. It may be possible to come up with some solution to this.

**Comment by ejgallego** [comment]
Yes you can have a different build command depending on a few environment settings, for example have a look at https://github.com/ocaml/opam-repository/blob/master/packages/ocaml-variants/ocaml-variants.4.12.0%2Boptions/opam

**Comment by clarus** [comment]
There is a `with-test` setting, like in https://github.com/clarus/coq-of-ocaml/blob/master/coq-of-ocaml.opam , maybe we can rely on it to activate fatal warnings?

**Comment by gares** [comment]
IMO the defaults are all wrong in this story, and we are here inheriting a bad choice made in dune and inherited via Coq.

The default should be to not fail on warnings, indeed the programmers decided to make these things warnings (and not errors) for a reason. Failing on warnings should be considered as linting your code, not as building it.

In the project's CI warnings could be fatal to keep the code linted. If you use the coq-community template this action is based on the opam file, the very same you want to upload here and the very same to be used for .dev (branches). So the wrong default can't be turned off by a line sneaked into a release tarball or some gimmick in the opam file. (eg, we want to run the CI job in this repo with with-test set, but not fail on ocaml compilation warnings).

IMO the right solution for the Coq community is to have the 2 build systems honor an environmet variable which sets fatal warnings on (both for ocaml part and the Coq part). You set it and coq_makefile or dune will lint the code while compiling it. All ci configuration files accept env variables, and the coq-docker action could just be patched to pass it along to the container. This is also build system and packaging system agnostic, the very same problem also applies to nix for example.

**Pull request merged**
