### PR TITLE
Add fiat-crypto conflict with new coq-fiat-crypto-with-bedrock

### PR DESCRIPTION
**Pull request by JasonGross**

### CODE REVIEW

**Comment by JasonGross** [comment]
Your patch before did not build the files that use `par:` and are memory-intensive.  Building fiat-crypto with multiple threads is easy to accidentally OOM.

**Comment by Alizter** [comment]
@JasonGross But this is the regular fiat crypto job no?

**Comment by JasonGross** [comment]
Yes, but [Coq's CI uses `-j 1` for the relevant file](https://github.com/coq/coq/blob/61644902cb89da5a260f07f855f0cc2e4c9dbea0/dev/ci/ci-fiat_crypto.sh#L26) and [our CI uses either `-j 1` or `COQEXTRAFLAGS="-async-proofs-j 1"`](https://github.com/mit-plv/fiat-crypto/blob/3e3fcf2262b8a85063c6b1454db72bf3e03f86c4/.github/workflows/coq-opam-package.yml#L22-L23).

Plausibly we should be passing this by default, though I still hold out hope that [coqworkmgr will someday integrate with the observer of `make`/`dune`](https://github.com/coq/coq/issues/14203)

**Comment by JasonGross** [comment]
In any case, all failures seems to be OOMs or timeouts, so I'm merging this

**Pull request merged**
