### PR TITLE
Release mathcomp 1.6.3

### PR DESCRIPTION
**Pull request by CohenCyril**

### CODE REVIEW

**Comment by CohenCyril** [comment]
Obviously, Travis did not test the opam packages. Is there a specific thing that should be done to trigger an opam install? (Only one package per commit or something?)

**Comment by CohenCyril** [comment]
rebased on top of master

**Comment by gares** [comment]
The package looks good to me, but I'd like to see if travis is now happy with it before merging

**Comment by gares** [comment]
yet another try...

**Comment by gares** [comment]
Amen, it is running.
The linter says that dev-repo is missing in character and algebra for example (minor issue).
It is now installing and removing each and every package (it will surely timeout doing so).

I think we should let travis run, and them if it fails by timeout merge this PR!

**Comment by CohenCyril** [comment]
agreed

**Comment by Zimmi48** [comment]
From @maximedenes in https://github.com/coq/coq/issues/5776#issuecomment-340475082

> In fact, it is worse than that. An 1.6.3 tag has been created (because the math-comp build for Coq 8.4 was broken), but that critical fix was not backported. I notified @CohenCyril , hopefully he'll see it in time to do a new tag before announcing the release.

**Comment by maximedenes** [comment]
@Zimmi48 Thanks!

**Comment by gares** [comment]
The current head of `release/1.6` builds fine on windows now (cyril cherry picked the relevant commits).
The win installer fails to build because commit https://github.com/math-comp/math-comp/commit/76387e0ca14b449a75467334a3efa2730f471b2f is missing.  Once this commit is picked, then I think we are good to go.

**Pull request closed without merging**
