### PR TITLE
Add coq-http

### PR DESCRIPTION
**Pull request by liyishuai**

### CODE REVIEW

**Comment by liyishuai** [comment]
The Makefile currently uses ```install extract/$(EXE) ``opam var bin`` ```. What's the recommended way to specify the installation directory?

**Comment by gares** [comment]
Did you try `%{bin}%` ? https://opam.ocaml.org/doc/Manual.html#Switch-variables

**Comment by liyishuai** [comment]
That'll move the binary installation from Makefile to OPAM file, which is also feasible. I wonder if there's a make-level solution.

**Comment by gares** [comment]
I mean, in opam you call `make install INSTALL_BIN=%{bin}%` and inside the Makefile you do `install thing $(INSTALL_BIN)`

**Comment by silene** [comment]
An intermediate solution might be to have `INSTALLDIR ?= $(shell opam var bin)` in the `Makefile` and then have `make install INSTALLDIR=%{bin}%` in the opam file.

**Comment by silene** [comment]
Oops, Enrico beat me to.

**Pull request merged**
