### PR TITLE
Providing opam files for those contribs which compile with Coq 8.6

### PR DESCRIPTION
**Pull request by herbelin**
Split of #496.

### CODE REVIEW

**Comment by herbelin** [comment]
The linter seems to complain about opam 2.0 fields synopsys and description, but these are opam 1.2 files and, moreover, opam doc says that these fields are optional. (Though it seems indeed better that opam 2.0. allows having only one file rather than three.)

**Comment by herbelin** [comment]
It seems to recompile coq for each package, which seems to take 15-20 minutes. But there are 158 packages, so 10h will not be necessary. Should I really split into say 6 groups of 26 or 27 packages, or can we change the CI so that, e.g., it does not recompile coq every time?

**Comment by clarus** [comment]
I would say to merge these pull-requests if it is too slow, and to use the results of the OPAM bench on https://coq-bench.github.io/clean/Linux-x86_64-4.05.0-1.2.2/released/ to fix potential errors afterwhile.

**Comment by herbelin** [comment]
How should the success of test "opam-build-no-timeout:4.06.0" and the failure of the other tests being interpreted?

What about accepting @clarus' proposal?

**Comment by herbelin** [comment]
Am I supposed to do something on this PR and the two related ones?

**Comment by herbelin** [comment]
To unblock this, let me suggest that we proceed with @clarus's proposal.

**Comment by gares** [comment]
I think it is OK to merge. The PR worked with 4.06, but not 4.02.

**Comment by herbelin** [comment]
According to https://coq-bench.github.io/clean/Linux-x86_64-4.05.0-1.2.2/released/ , there are two problems:
- lesniewski-mereology failed at uninstall due to a missing `-R`/`-Q`
- projective-geometry fails brutally (maybe a timeout)?

I fixed lesniewski-mereology in PR #500 (for 8.7) and #501 (for 8.8). I shall submit an update for 8.6.

**Pull request merged**
