### PR TITLE
move itauto.8.13 to its subdirectory

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
Oh yes, I had this problem locally, then I did run dune from opam and I could debug/fix the issue.
So it seems there is a second issue which is nix specific, CC @Zimmi48

**Comment by Zimmi48** [comment]
The attribute `dune` has been removed from nixpkgs in favor of the more explicit `dune_1` and `dune_2`.

**Comment by gares** [comment]
how wonderful, `dune exec` has warn as errors...

**Comment by gares** [comment]
it seems the easiest fix is to pin opam to an older version, just using the non deprecated function is not enough, the data type is slightly different

**Pull request merged**
