### PR TITLE
[extra-dev] upgrade to opam 2.0 format

### PR DESCRIPTION
**Pull request by gares**
As far as I know the main user of this repo is coq-bench, CC his maintainer: @ejgallego 
IIRC pendulum already has opam 2.x installed, hence it should just work.

ci-skip: coq-aac-tactics.dev coq-additions.dev coq-ails.dev coq-algebra.dev coq-amm11262.dev coq-angles.dev coq-automata.dev coq-axiomatic-abp.dev coq-bdds.dev coq-bignums.8.7.dev coq-bignums.8.8.dev coq-bignums.dev coq-buchberger.dev coq-checker.dev coq-cheerios.8.7.dev coq-chinese.dev coq-circuits.dev coq-color.8.7.dev coq-color.dev coq-compcert.8.7.dev coq-compcert.8.8.dev coq-compcert.dev coq-concat.dev coq-constructive-geometry.dev coq-coqoban.dev coq-coqprime.dev coq-coquelicot.dev coq-corn.dev coq-cours-de-coq.dev coq-ctltctl.dev coq-dblib.dev coq-demos.dev coq-dep-map.dev coq-dictionaries.dev coq-distributed-reference-counting.dev coq-domain-theory.dev coq-elpi.v0.1.1.dev coq-equations.8.7.dev coq-equations.8.8.dev coq-euler-formula.dev coq-exceptions.dev coq-ext-lib.dev coq-fcsl-pcm.dev coq-fermat4.dev coq-fiat-core.dev coq-fiat-crypto.8.7.dev coq-fiat-crypto.8.8.dev coq-fiat-crypto.8.9.dev coq-fiat-crypto.dev coq-fiat-crypto-legacy.8.7.dev coq-fiat-crypto-legacy.8.8.dev coq-fiat-crypto-legacy.8.9.dev coq-fiat-crypto-legacy.dev coq-fiat-parsers.8.7.dev coq-fiat-parsers.dev coq-float.dev coq-flocq.8.7.dev coq-flocq.dev coq-formal-topology.dev coq-free-groups.dev coq-fssec-model.dev coq-functions-in-zfc.dev coq-fundamental-arithmetics.dev coq-generic-environments.dev coq-geocoq.dev coq-goedel.dev coq-graph-basics.dev coq-groups.dev coq-group-theory.dev coq-hardware.dev coq-hedges.dev coq-higman-cf.dev coq-higman-nw.dev coq-higman-s.dev coq-historical-examples.dev coq-hoare-tut.dev coq-hott.8.7.dev coq-hott.8.8.dev coq-hott.dev coq-idxassoc.dev coq-ieee754.dev coq-inf-seq-ext.8.7.dev coq-inf-seq-ext.dev coq-int-map.dev coq-ipc.dev coq-itree.dev coq-izf.dev coq-jordan-curve-theorem.dev coq-lambda.dev coq-lazy-pcf.dev coq-lemma-overloading.dev coq-lesniewski-mereology.dev coq-ltac2.8.7.dev coq-ltac2.dev coq-markov.dev coq-math-classes.dev coq-mathcomp-algebra.dev coq-template-coq.8.7.dev coq-verdi.8.7.dev coq-verdi-raft.8.7.dev coq-vst.8.7.dev coq-vst.dev coq-tal0.dev coq-tarski-geometry.dev coq-three-gap.dev coq-topology.dev coq-tortoise-hare-algorithm.dev coq-traversable-fincontainer.dev coq-tree-automata.dev coq-unimath.dev coq-weak-up-to.dev coq-zchinese.dev coq-zf.dev coq-zfc.dev coq-zorns-lemma.dev coq-zsearch-trees.dev coq-mathcomp-character.dev coq-mathcomp-field.dev coq-mathcomp-fingroup.dev coq-mathcomp-multinomials.1.x.dev coq-mathcomp-odd-order.dev coq-mathcomp-solvable.dev coq-mathcomp-ssreflect.dev coq-maths.dev coq-mini-compiler.dev coq-miniml.dev coq-mod-red.dev coq-multiplier.dev coq-ott.8.7.dev coq-ott.dev coq-otway-rees.dev coq-paco.dev coq-paradoxes.dev coq-param-pi.dev coq-pocklington.dev coq-propcalc.dev coq-qarith.dev coq-quickchick.8.8.dev coq-quickchick.dev coq-railroad-crossing.dev coq-ramsey.dev coq-regexp.dev coq-rem.dev coq-rsa.dev coq-ruler-compass-geometry.dev coq-sf-plf.8.7.dev coq-sf-plf.dev coq-shuffle.dev coq-simple-io.dev coq-smc.dev coq-streams.dev coq-struct-tact.8.7.dev coq-struct-tact.dev coq-subst.dev

### CODE REVIEW

**Comment by gares** [comment]
> This should wait for [coq/coq-bench#57](https://github.com/coq/coq-bench/pull/57)

merged. So this PR can continue its slow convergence toward something acceptable.

**Comment by gares** [comment]
dear @coq/ci-maintainers I need some help to have the logs stored as artifacts. I did what you can see in the last commit, but I don't know if I've to do something extra (since the last run failed but I don't get any artifact).

**Comment by SkySkimmer** [comment]
I think when it dies from oversized log or timeout you don't get artifacts.

**Comment by ejgallego** [comment]
Yeah you ought to do some structured logging to files instead.

**Comment by gares** [comment]
Each "opam job" generates a single log file (exactly to avoid exceeding the log size limit).
But yes, it times out. Is there a way to force saving the logs while the job is running?

**Comment by ejgallego** [comment]
> But yes, it times out. Is there a way to force saving the logs while the job is running?

I guess you could indeed wrap the whole process on a in-job timeout and then perform your own cleanup?

**Comment by gares** [comment]
I'd rather ask how to avoid the 10h timeout (on demand) since I need more time to test the packages in these "whole repo" tests. It is not diverging, it just takes more time.

**Comment by ejgallego** [comment]
> I'd rather ask how to avoid the 10h timeout (on demand) since I need more time to test the packages in these "whole repo" tests. It is not diverging, it just takes more time. EDIT: and I can't split the PR into smaller chunks, since I'm changing the archive format.

I'm much afraid that TTBOFMK you'll either had to do the test locally or split the CI job on different stages [or use your own gitlab instance]

**Comment by gares** [comment]
IIRC @Zimmi48 said that the 10h timeout was an arbitrary choice, if it is hardwired then I'll hack the scripts to avoid reaching the timeout.

**Comment by ejgallego** [comment]
> IIRC @Zimmi48 said that the 10h timeout was an arbitrary choice, if it is hardwired then I'll hack the scripts to avoid reaching the timeout.

Indeed you can modify it in the setting, try 20h if you want, but at some point we may hit some limit by gitlab .

**Comment by Zimmi48** [comment]
>Indeed you can modify it in the setting, try 20h if you want, but at some point we may hit some limit by gitlab .

Note that we are already using our own runners for long timeout jobs. So indeed, bump the 10h timeout to whatever value feels right.

**Comment by gares** [comment]
OK, I've revamped CI. It now prints regularly the progress, and one can skip single packages by writing a directive in the PR message. In this way one can "continue" from a timed out job (currently 1day) and skip what worked. It's a poor man tool, but should do it.

**Comment by gares** [comment]
Just to be clear, we are talking about dev packages, not the released ones (that are still available for any coq version in the released archive). 

The dev packages I removed are the ones for a specific version of Coq X where X + 2 < current. I did remove no (working) package targeting coq master or coq 8.8 or coq 8.7.

I also doubt that the branch, say, coq 8.4 specific of package P is any different from the released version of P for 8.4.  It may be the case for 8.9 (since the coq branch may still move and hence the package may move too).
This repo is mostly using for benchmarking. I don't see the use case of benchmarking P.8.4.dev rather than P.8.4.

Of course these packages can be put back, but I don't think it is useful.

**Comment by gares** [comment]
Oh, w.r.t. broken packages my plan is to simply remove them. If there is interest, they can then be added back. But having broken code around is just making testing/benchmarking harder, so I take the occasion to clean up the archive of dev packages.

I did fix the opam lint errors on all packages, since that is easy to do.

**Comment by herbelin** [comment]
> I also doubt that the branch, say, coq 8.4 specific of package P is any different from the released version of P for 8.4. 

OK, I did not check but that's probably the case indeed.

**Comment by JasonGross** [comment]
> Just to be clear, we are talking about dev packages, not the released ones (that are still available for any coq version in the released archive).
> The dev packages I removed are the ones for a specific version of Coq X where X + 2 < current.

What's the reason for removing dev versions of packages for which there is no released version?  (e.g., HoTT, fiat-crypto)  If the package supports released versions of Coq 8.4, 8.5, 8.6, I don't see any reason to remove it just because it is called "dev" (though perhaps it makes sense to rename it to remove the "dev"), and it seems better to keep around for posterity, for the same reason that old versions of Coq are nice to keep around / accessible.

**Comment by gares** [comment]
I don't see the point of keeping them, to me .dev packages are used to test an ongoing development, ie a not yet released branch. Wild guess, not many people develop against Coq 8.4 and we don't develop 8.4 either. What it your use case? In any case, you can put the ones that interest you back by opening a PR.

**Pull request merged**
