### PR TITLE
Fix coq-interval.1.1.0 for opam 2

### PR DESCRIPTION
**Pull request by clarus**

### CODE REVIEW

**Comment by palmskog** [comment]
The URL (https://gforge.inria.fr/frs/download.php/file/34004/interval-1.1.0.tar.gz) gives 404. Is this archive version available at all anymore?

**Comment by silene** [comment]
No, the older archives were lost, unfortunately. They can still be generated from the source repository, and the library can directly be built from it too. But I am not sure it is worth having such old versions in the opam repository.

**Comment by palmskog** [comment]
I believe there are still notable projects stuck on Coq 8.4, and I think one goal is to preserve historical releases, but I'll leave up to @clarus to decide what to do here.

**Comment by clarus** [comment]
@silene It seems that all the versions of `coq-interval` before the 3.x ones are offline, namely:
* `1.1.0` and `2.2.1` which were removed moving to opam 2;
* `2.0.0`, 2.1.0` and `2.2.0` which are still there.
It seems no packages depend on these versions. I would also prefer to keep these versions for historical value, but if you are OK I can remove them.

**Comment by silene** [comment]
I will regenerate some archives for 1.1.1 and 2.2.1 and submit a pull request with the corresponding URLs in the `opam` files. I don't see much value in restoring the other versions, even for historical purpose.

**Comment by palmskog** [comment]
Thanks @silene. I'll close this then.

**Comment by silene** [comment]
Actually, I won't do a package for Interval 1.1.1, as I have been unable to install the opam package for Coq 8.4, which makes the point moot for the time being.

**Pull request closed without merging**
