### PR TITLE
Development versions of SMTCoq and Sniper for Coq-8.13, 8.15 and 8.16

### PR DESCRIPTION
**Pull request by ckeller**

### CODE REVIEW

**Comment by palmskog** [comment]
@ckeller the only failure here was the 8.13 development version of SMTCoq. Is this some missing dependency or something else maybe?
```
# [...]
# CAMLC -c ../3rdparty/alt-ergo/smtlib2_ast.mli
# CAMLC -c smtlib2/sExpr.mli
# CAMLC -c verit/veritParser.mli
# CAMLC -c lfsc/shashcons.mli
# CAMLOPT -c -for-pack Smtcoq_plugin lfsc/type.ml
# File "lfsc/type.ml", line 1:
# Error (warning 70 [missing-mli]): Cannot find interface file.
# make[2]: *** [Makefile:668: lfsc/type.cmx] Error 2
# make[2]: *** Waiting for unfinished jobs....
# make[1]: *** [Makefile:343: all] Error 2
```

**Comment by palmskog** [comment]
I remember now what the problem is: the `v8.13` branch of Coq is not patched to fix the error-from-warning thing that OCaml introduced. Since this is unlikely to be fixed anytime soon, how about we drop the 8.13 dev package for SMTCoq?

**Comment by ckeller** [comment]
I was rather thinking of adding mli for every ml, I'll write when it is done to check compilation again.

**Comment by ckeller** [comment]
> I was rather thinking of adding mli for every ml, I'll write when it is done to check compilation again.

This is actually not possible because some ml files are generated by ocamllex, which does not generate mli files. I will thus skip the changes for Coq-8.13, as you suggested.
I have created two new PRs, one for each remaning version, just to make sure ;-) #2615 #2616

**Pull request closed without merging**
