### PR TITLE
Add coq-of-ocaml.2.1.0

### PR DESCRIPTION
**Pull request by clarus**

### CODE REVIEW

**Comment by clarus** [comment]
I am investigating the issue. Surprisingly, only the `any` build fails.

**Comment by clarus** [comment]
@here I would need some help to fix this pull-request. I do not really understand why it fails on the `any` plateforme. To me, the only difference is that there is a switch of compiler. The error is the following:
```
- dune build src/coqOfOCaml.exe
- Entering directory '/builds/coq/opam-coq-archive'
- File "opam-root-4.09.0-2.0.5-plain/4.09.0/bin/dune", line 1, characters 0-0:
- Error: Invalid dune file
- make: *** [Makefile:2: default] Error 1
```
It seems to me that `dune` is looking for `dune` files and finds itself.

**Comment by gares** [comment]
It works, what did you change?

**Comment by clarus** [comment]
Ah, I tested another version of coq-of-ocaml. I think the change is not a fix actually because this version is compatible with OCaml 4.09 which is the version used by the `any` target. Hence the test do not do a change of OCaml compiler as before, and it works but just as the `4.09` target works.

So I remove the test commit and plan to merge it as it.

**Pull request merged**
