### PR TITLE
Add bmsherman/topology package as coq-formal-topology

### PR DESCRIPTION
**Pull request by JasonGross**
This development of @bmsherman tests universe polymorphism and setoid rewriting in type, and should build with v8.6 and trunk.  It's primarily for the bench.

### CODE REVIEW

**Comment by matejkosik** [comment]
Unless I made a mistake, the `coq-formal-topology` provided by this pull-request is not installable. @JasonGross can you please confirm?

**Comment by JasonGross** [comment]
Ack, sorry, I forgot that https://github.com/bmsherman/topology/pull/11 hadn't been merged yet.  Once that's merged, it should be installable.

**Comment by JasonGross** [comment]
Should be fixed now; let me know if it's not.

**Comment by matejkosik** [comment]
Ok. I've retested it and now it [works](https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/88/console).

**Pull request merged**
