### PR TITLE
add 8.12 releases of pocklington and goedel

### PR DESCRIPTION
**Pull request by palmskog**

### CODE REVIEW

**Comment by silene** [comment]
Should we start capitalizing keywords (e.g., Goedel, Rosser)? I have considered cleaning the keywords of numerous packages, but I was unsure whether I should go for lower case or upper case for such keywords.

**Comment by palmskog** [comment]
@silene I'm fine with starting to capitalize keywords, here I was just following the existing conventions. In any case, I think a keyword-based search (separate from opam's), if/when we add one in the future, should be case-insensitive.

**Comment by silene** [comment]
> I'm fine with starting to capitalize keywords, here I was just following the existing conventions

Note that some packages already capitalize Goedel and Rosser. (Also, just to be clear, I was not suggesting to capitalize all keywords, only those that people would write in uppercase, given the choice.)

> In any case, I think a keyword-based search (separate from opam's), if/when we add one in the future, should be case-insensitive.

Definitely. But that is not what I had in mind. I am currently more concerned with the mess that is https://coq.inria.fr/opam/www/

**Comment by palmskog** [comment]
I capitalized the keywords here, but my view is that https://coq.inria.fr/opam/www/ is fundamentally non-functional, so I don't think it should be a basis for decisions about conventions. For example, most packages there don't even have their descriptions/synopses shown (#691).

**Pull request merged**
