### PR TITLE
Release fcsl-pcm 1.1.0 + small fixes for 1.0.0 and dev

### PR DESCRIPTION
**Pull request by anton-trunov**
Updating dependencies to incorporate the recent Mathcomp 1.8 release.

CC @palmskog

### CODE REVIEW

**Comment by palmskog** [comment]
@anton-trunov you probably want to have
```
flags: light-uninstall
```
in the OPAM files (as I believe is idiomatic for other Coq OPAM packages).

**Comment by anton-trunov** [comment]
@palmskog Thanks, I wasn't aware of this flag. It seems that with opam 2.0 `remove` can be [omitted altogether](https://opam.ocaml.org/doc/Upgrade_guide.html):

>opam now tracks installed files, so the `remove:` field can now in general be omitted. Specify `flags: light-uninstall` if you do need remove: instructions, but these are not required to be run from the source tree of the package.

If my understanding is correct, then I can leave out `remove` (because opam tracks files for me) and since I won't have `remove`, I don't need `flags: light-uninstall` either.

**Comment by anton-trunov** [comment]
@gares Could you please confirm that I can safely delete `remove` field from the opam files in this PR? (I marked this PR as WIP for now).

**Comment by anton-trunov** [comment]
Ok, I tried it locally and it seems to work -- opam 2.0 is able to remove `fcsl-pcm` even without the `remove` field. I think this is ready to be merged.

**Pull request merged**
