### PR TITLE
add core-dev Coq 8.11+beta1 package

### PR DESCRIPTION
**Pull request by palmskog**
Ping @Blaisorblade, based on copying `8.11.dev` package.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
Please consider blacklisting lablgtk beta7 (like on official 8.10) as long as https://github.com/coq/coq/pull/11234 isn't merged. Beta6 and beta8 are fine. Can send more links on background if needed.

**Comment by palmskog** [comment]
@Blaisorblade But isn't that only for CoqIDE? Maybe you can handle the CoqIDE 8.11+beta1 package and make sure the blacklisting is OK? I don't use CoqIDE or have a Mac.

**Comment by Blaisorblade** [comment]
@palmskog whoops, you're right. I'm quite possibly worrying too much, and I'm happy to wait for actual users of coqide who'd use the beta. Sorry for the noise!

**Comment by palmskog** [comment]
Ping @erikmd that you now probably want to switch to `8.11+beta1` in the `coq:8.11` Docker image.

**Comment by erikmd** [comment]
Thanks @palmskog ! I've just started the build so `coqorg/coq:8.11 = coqorg/coq:8.11-beta1` should be ready in `90'` or so. I'll update the docker-coq wiki at that moment.

**Comment by erikmd** [comment]
[done](https://github.com/coq-community/docker-coq/wiki).

**Pull request merged**
