### PR TITLE
Add Flocq 3.2.0, Gappa 1.4.2, CoqInterval 3.4.1.

### PR DESCRIPTION
**Pull request by silene**
This should ensure compatibility with Coq 8.10.

### CODE REVIEW

**Comment by palmskog** [comment]
Even though the sandbox changes for pyrolyse were merged in #831, the CI here still gives errors as before:
```
[ERROR] The compilation of ocaml-base-compiler failed at "/builds/coq/opam-coq-archive/opam-root-4.07.1-sandbox/opam-init/hooks/sandbox.sh build ./configure -prefix /builds/coq/opam-coq-archive/opam-root-4.07.1-sandbox/4.07.1 -with-debug-runtime".
```
@gares should we disable sandboxing completely?

**Comment by gares** [comment]
Not yet,there was a silly typo in my script

**Comment by gares** [comment]
@silene would you mind rebasing this?

**Comment by gares** [comment]
thanks!

**Comment by silene** [comment]
It still fails with the same error message, as far as I can tell.

**Comment by gares** [comment]
CI is still broken on pyrolyse, but last PR push was scheduled on regular runners so it should work (the linting problem is due to pyrolyse, but we can ignore that)

**Pull request merged**
