### PR TITLE
Package coq-quickchick.1.5.1

### PR DESCRIPTION
**Pull request by liyishuai**
### `coq-quickchick.1.5.1`
Randomized Property-Based Testing Plugin for Coq

---
* Homepage: https://github.com/QuickChick/QuickChick
* Source repo: git+https://github.com/QuickChick/QuickChick.git
* Bug tracker: https://github.com/QuickChick/QuickChick/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by palmskog** [comment]
@liyishuai it looks like the testing part of the package fails on all versions. If you still want this to be merged, please remove the `with-test` line.

**Comment by MSoegtropIMC** [comment]
Let me test it in Coq Platform CI - it might be some issue with the separate executable opam CI can't handle.

**Review by MSoegtropIMC — APPROVED** [review]
The same opam file works for me in Coq Platform - including our small "smoke test", so I would say the failure are artifacts. From my desk this is good to go.

**Comment by MSoegtropIMC** [comment]
P.S.: one reason this doesn't work might be that there is no 8.14 compatible instance of coq-ext-lib in released. I will do a PR for the opam package and then we can rerun CI.

**Comment by palmskog** [comment]
Having an 8.14 compatible version of coq-ext-lib is good, but it doesn't affect this error. How do I know this? Well, the CI is set up in such a way that `released` packages are not tested with Coq versions in `core-dev`.

I also checked the differences between 1.5.0 and 1.5.1, and there are extensive changes to to how testing is done (the `tests` action in the Makefile). What I think is happening is that some tests assume there is already a pre-installed `quickChick` executable - it's impossible to use the one being built in an opam test due to sandboxing.

@MSoegtropIMC are you there isn't already an installed `quickChick` executable in the Platform CI? We had the same problem for bignums, where the tests assumed some bignums package was already installed, which it typically is in a Coq Docker image.

**Comment by MSoegtropIMC** [comment]
@palmskog : I am quite sure that the quickchick executable is created by this opam package - Coq Platform doesn't do anything other than "opam install coq-quickchick.1.5.1".

`which quickchick` gives me:

`/Users/msoegtrop/.opam/__coq-platform.2021.09.0~8.14+rc1/bin/quickchick`

But I do only a rather small test - the so called "smoke test". It exercises QuickChick via its Coq plugin - I am not even sure if this requires the external executable or if this is required for other things.

What I can say is that typical applications of QuickChick from inside Coq do work.

But we can leave this open until the CI issues are fixed - I already put the opam file into the Coq Platform local patch repo and it is fine like this for a few weeks (until Coq Platform is released). So there is no urgency.

**Comment by palmskog** [comment]
@MSoegtropIMC are you sure the platform CI even runs opam tests? It would need to pass `-t` to `opam install` or set the environment variable `OPAMWITHTEST`. I took a look at the workflows in the platform repo, and I couldn't find anything like that.

**Comment by MSoegtropIMC** [comment]
@palmskog : I am sure we don't run opam tests - maybe I should add an option to do so. In general Coq Platform assumes that the packages are tested in their own CI and all Coq Platform can mess up is packaging so all what is tested in Coq Platform is the so called "smoke test". That is we run a few examples for each of the installed packages to test if things basically work, e.g. the files are actually installed. This smoke test does work for QuickChick 1.5.1. Also my own usages of QuickChick do work.

As I said, in this situation it is probably best that I keep the local patch opam package for QuickChick 1.5.1 until this is sorted out. Still from Coq Platforms side, this looks good to go.

**Comment by palmskog** [comment]
@MSoegtropIMC Haven't we always said that platform packages should live in the Coq opam repo (or OCaml opam repo)? If the platform has laxer requirements for package inclusion than the opam repos' CI, then there will probably be discrepancies.

For the `released` repo, there has to be some good really reason to merge when C is red. As per above, a simple fix for this package is just to remove this line:
```
  [make "-j" jobs "tests"] {with-test}
```

**Comment by MSoegtropIMC** [comment]
> @MSoegtropIMC Haven't we always said that platform packages should live in the Coq opam repo (or OCaml opam repo)? If the platform has laxer requirements for package inclusion than the opam repos' CI, then there will probably be discrepancies.
> 
> For the `released` repo, there has to be some good really reason to merge when CI is red. As per above, a simple fix for this package is just to remove this line:
> 
> ```
>   [make "-j" jobs "tests"] {with-test}
> ```

Yes sure - having the files locally is only a temporary solution for bringup.

"Fixing" tests by disabling them is IMHO not what we should do - I would prefer to keep a local patch in Coq Platform until things are 100% proper upstream and then remove the local patch package. That's what I usually do. The local packages are always a "there is something left to be done" reminder.

**Comment by palmskog** [comment]
The question here to me is how much time we want to spend debugging non-critical parts of packages while holding up the regular packaging process. If packages are not merged into `released` due to getting stuck on CI for something like this, regular users of the Coq opam archive (who may not use the platform) will not get those packages, even if they contain nice improvements and bugfixes. On the other hand, if this was a package targeting `extra-dev` that only worked with 8.14, then the "loss" is minimal to spend time to debug it.

**Comment by MSoegtropIMC** [comment]
As far as I can tell the package was created for 8.14 compatibility in response to a Coq Platform auto generated "please tag" issue (https://github.com/QuickChick/QuickChick/issues/236) so I expect the usefulness before the release of 8.14 is limited.

To summarize my point: I think it is fine to take some short cuts to enable people to do their work in case the risk is low. But one should keep reminders about this and still try to do it properly as soon as possible. In that view removing a test target from an opam file is a bad solution - there is certain likelihood that it won't be enabled again which is not what we want in the long run.

**Comment by palmskog** [comment]
There is no chance that we can do an "origin analysis" of all packages submitted as PRs here. I would suggest using the following procedure for platform packages:
- always target the `extra-dev` repo, regardless of whether a stable version is supported or not
- if the PR doesn't pass CI here, close the PR and investigate if the error can be reproduced in the platform CI
- if necessary, modify the package and reopen the PR here, push any changes, then merge if CI green

The situation I want to avoid is having tons of PRs here that are stuck until investigated upstream.

Finally, enabling the platform CI to run opam tests would probably help a lot.

**Comment by MSoegtropIMC** [comment]
My approach used more to be to sort things out in Coq Platform (that's the reason d'être of the platform local opam patch repo) and push things here after it is tested in Coq Platform.

But of course this would mean that I need a switch to enable opam tests. Also I guess I need to communicate this better in the platform domain who does the opam packages. I usually request a tag and frequently do the opam packages myself then, but some package maintainers do the opam packages also.

Btw.: in my experience it is rather rate that version update packages fail here. What is your experience?

**Comment by palmskog** [comment]
> in my experience it is rather rate that version update packages fail here. What is your experience?

PRs fail in CI here quite often, for anything from the most obvious to the most obscure reasons. This doesn't mean the underlying *projects* (Coq files) are broken often. Common reasons for breaking:
- old or new (unexpected) Coq version, i.e., inaccurate Coq version bound
- install command or other opam package definition error (could also be changed semantics for `make` or `make install`)
- unexpected libraries (inaccurate dependency bounds)

I haven't really seen any substantial difference between "version bumps" and completely new packages.

**Comment by MSoegtropIMC** [comment]
I see. But I guess OCaml version deviations are rare?

If so, I would think if I run a Coq Platform install with tests enabled, it should come quite close to the tests here, and we can proceed as I said - first test things in Coq Platform and then bring it here. One reason for that approach is also that in the past I frequently had to change packages for compatibility with other packages. That is getting better, though.

**Comment by palmskog** [comment]
> But I guess OCaml version deviations are rare?

OCaml versions have given us a lot of grief in plugin packages. Some plugins will not build with low OCaml versions (say, 4.05.0) without the authors being aware. Certain OCaml compilers also give rare spurious errors (see, e.g., AbsInt/CompCert#327).

I was not aware until recently that aac-tactics didn't build with OCaml 4.12.0, since we don't use that version in the default Docker image (latest release of aac-tactics works fine with 4.12.0 now).

**Pull request merged**
