### PR TITLE
coq.8.8.1 is not compatible with CompCert 3.3 and 3.2

### PR DESCRIPTION
**Pull request by ildyria**
(or packaging has to be re-done)

### CODE REVIEW

**Comment by Zimmi48** [comment]
Do you have a pointer to an issue explaining the incompatibility? We are trying very hard not to introduce such incompatibilties in patch-level releases but we are testing the master branch of CompCert even in v8.8. We should probably test a released version (latest tag) instead...

**Comment by ejgallego** [comment]
Let me guess, it is maybe because of the version check in Compcert?

**Comment by maximedenes** [comment]
> Let me guess, it is maybe because of the version check in Compcert?

Yes, see: https://github.com/AbsInt/CompCert/commit/679ecfeaa24c0615fa1999e9582bf2af6a9f35e7

**Comment by Zimmi48** [comment]
What is preventing this from being merged?

**Pull request merged**
