### PR TITLE
Support arm64 targets in CompCert 3.10

### PR DESCRIPTION
**Pull request by QDelta**

### CODE REVIEW

**Comment by palmskog** [comment]
We have no way of testing ARM64 targets in the CI, so I will defer to the de facto maintainer of the package (@MSoegtropIMC) on whether this can be merged.

**Comment by MSoegtropIMC** [comment]
@QDelta : on which platforms did you actually test this (say Apple M1, Raspberry ...)?

**Comment by QDelta** [comment]
> @QDelta : on which platforms did you actually test this (say Apple M1, Raspberry ...)?

I have tested this on Apple M1 Pro and raspberry pi 4b by copying the opam file to the source directory then run `opam install .`

On mac, previously the generated libcompcert.a will contains x86_64 objects, now they will be arm64.
On pi, previously the installation will fail due to incorrect gcc options, now it works.

**Review by MSoegtropIMC — APPROVED** [review]

**Comment by MSoegtropIMC** [comment]
@palmskog : with tests on Apple silicon Mac and Raspberry this looks good for merge to me.

**Pull request merged**
