### PR TITLE
Package coq-libhyos-2.0.4 (compatible with coq-8.14).

### PR DESCRIPTION
**Pull request by Matafou**
New version of the coq-libhyps package. Compatible with coq-8.14.

### CODE REVIEW

**Comment by palmskog** [comment]
I believe this is the intended package for the 8.14 Coq Platform.

cc: @MSoegtropIMC

**Comment by Matafou** [comment]
Sorry I will submit a new package shortly, fixing a small bug due to my misunderstanding of the semntics of "move" tactics.

**Comment by palmskog** [comment]
@Matafou then you may consider changing the existing package instead (you could delete the old GitHub release and recreate it at the right commit).

**Comment by Matafou** [comment]
You mean replace the libhyps.2.0.4/opam file in place?

**Comment by palmskog** [comment]
@Matafou yes, if you replace the GitHub tag with a new tag with the same name pointing to the "good" commit, you can simply update the checksum of the `libhyps.2.0.4/opam` file. This might be preferable to having several opam package versions with essentially the same content, but up to you to decide.

**Pull request merged**
