### PR TITLE
ITree 1.0.0

### PR DESCRIPTION
**Pull request by liyishuai**

### CODE REVIEW

**Comment by Lysxia** [comment]
I pushed the 1.0.0 tag. (And there have been a couple of tweaks to the opam file.)

**Comment by liyishuai** [comment]
The dev version has failed, but will succeed after DeepSpec/InteractionTrees#105 is merged.
Should I add version constraints to extra-dev, or leave it as is?

**Comment by Lysxia** [comment]
Yes, please add a version constraint.

**Comment by liyishuai** [comment]
Ready to merge.

**Comment by gares** [comment]
Sorry for the dealy, we are migrating the archive to opam 2 format. I'll then provide a fix for this PR.

**Pull request merged**
