### PR TITLE
Use external coq-coqutil in coq-fiat-crypto-with-bedrock

### PR DESCRIPTION
**Pull request by JasonGross**

### CODE REVIEW

**Comment by JasonGross** [comment]
I'm going to optimistically mark this as ready for review, hoping that https://github.com/mit-plv/fiat-crypto/pull/1151 is sufficient

**Comment by palmskog** [comment]
@JasonGross I see nothing problematic in these changes, and this is a dev package, so feel free to merge it whenever you feel it's ready despite CI failures.

**Comment by JasonGross** [comment]
The CI failures are real, I need to do more debugging

**Comment by JasonGross** [comment]
CI is now failing with the standard OOM for fiat-crypto, so I will merge this.

**Pull request merged**
