### PR TITLE
coq-dpdgraph for coq 8.15

### PR DESCRIPTION
**Pull request by ybertot**
This is a preparation for coq-platform.

### CODE REVIEW

**Comment by palmskog** [comment]
@MSoegtropIMC this means you should be able to close coq-community/coq-dpdgraph#95

**Comment by ybertot** [comment]
I was going to close the issue myself and warn @MSoegtropIMC as soon as this PR is merged.

**Comment by palmskog** [comment]
@ybertot but did you see the following in the issue:
> Please don't close this issue, even after creating the new tag and/or opam package.
> We will close the issue after updating Coq Platform.
> This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

(Also somewhat unrelated point, but maybe you can mark the 8.15 release as "proper" release on GitHub instead of a pre-release?)

**Comment by palmskog** [comment]
Sorry for being unclear, I meant this one is marked as a prerelease: https://github.com/coq-community/coq-dpdgraph/releases/tag/v1.0%2B8.15

**Comment by ybertot** [comment]
Thanks for the heads up!

**Comment by MSoegtropIMC** [comment]
Thanks @ybertot !

As @palmskog mentioned the preferred and safest procedure is if you just leave a comment on the tag to choose in (https://github.com/coq-community/coq-dpdgraph/issues/95). I will then update Coq Platform and close the issue.

**Pull request merged**
