### PR TITLE
2 packages from gitlab.inria.fr/charguer/cfml2/-/archive/20220102/archive.tar.gz

### PR DESCRIPTION
**Pull request by fpottier**
This pull-request concerns:
-`coq-cfml-basis.20220102`: The CFML Basis library
-`coq-cfml-stdlib.20220102`: The CFML program verification system

---
* Homepage: https://gitlab.inria.fr/charguer/cfml2
* Source repo: git+https://gitlab.inria.fr/charguer/cfml2.git
* Bug tracker: https://gitlab.inria.fr/charguer/cfml2/-/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by palmskog** [comment]
@fpottier as before, we want CI to pass - so this should wait for the corresponding `cfml` package PR to be merged and appear through `opam update`.

**Comment by fpottier** [comment]
OK, no problem! There is no hurry.

**Comment by fpottier** [comment]
The `cfml` package has been published a few days ago.

**Comment by palmskog** [comment]
I tried CI yesterday, but I'm getting these errors:
```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - coq-cfml-basis.20220102:
            https://gitlab.inria.fr/charguer/cfml2/-/archive/20220102/archive.tar.gz (Bad checksum, expected md5=c700eda608565dade2188990adb04168)
          - coq-cfml-stdlib.20220102:
            https://gitlab.inria.fr/charguer/cfml2/-/archive/20220102/archive.tar.gz (Bad checksum, expected md5=c700eda608565dade2188990adb04168)
```
Can you check what the correct checksum should be?

**Comment by fpottier** [comment]
Sorry, I updated the archive a few days ago and forgot to update the checksums in this PR.

**Pull request merged**
