### PR TITLE
Fix QCert for OPAM 2

### PR DESCRIPTION
**Pull request by clarus**
Fixing packages which were broken (and removed) during the move to OPAM 2

### CODE REVIEW

**Comment by palmskog** [comment]
Package seems to fail on Coq 8.8.2, please adjust version bound.

**Comment by palmskog** [comment]
All the relevant CI jobs time out. This may be because of some bug (in Coq 8.7.2) or similar. @gares any advice what we should do here?

**Comment by clarus** [comment]
I will open separated pull-requests for each version of QCert to workaround the time out issue if that is the bug.

**Comment by gares** [comment]
The readme (bottom) documents how to run a pr with no timeout, but I don't know if you have the rights to do so. Please try

**Comment by clarus** [comment]
OK thanks, I did not know. I do not have the rights.

**Comment by gares** [comment]
Dear @coq/ci-maintainers I don't know how gitlab teams work, do we have a policy for adding people? @palmskog and @clarus are active contributors here, it would be nice if they could create jobs to overcome the time limit when needed.

**Comment by palmskog** [comment]
Closing this since separate PRs with content have been merged.

**Pull request closed without merging**
