### PR TITLE
Package coq-semantics.8.14.0

### PR DESCRIPTION
**Pull request by k4rtik**
Adds compatibility with Coq v8.14. See https://github.com/coq-community/semantics/issues/8

### CODE REVIEW

**Comment by palmskog** [comment]
@k4rtik there is nothing wrong per se with the package, but do you really depend on `num`? The last package had the dependency `"ocamlbuild" {build}`, which just said that `ocamlbuild` was used during the build phase. Did anything really change since then?

**Comment by k4rtik** [comment]
Hi @palmskog, thanks for being so careful while reviewing these changes.

The change is that until Coq 8.13, `num` was being installed as a dependency of Coq, so we didn't to explicitly mark it in this opam file. But since 8.14, that's not the case. The previous [opam file here on this repo](https://github.com/coq/opam-coq-archive/commit/7ef5f86b06d7c5e4e57c88b4a647206cf2d0fd0e) actually marked 8.14 as unsupported which I was surprised to find out.

I understand that in the long term the package should try and switch to `zarith` instead of depending on `num`.

**Comment by palmskog** [comment]
I see, then everything seems to be in order. Another option you could also consider in the future is to have separate opam packages for the OCaml parts (that use ocamlbuild and num or zarith) and the pure Coq library. I do something like this in [Chapar](https://github.com/coq-community/chapar).

**Comment by k4rtik** [comment]
That sounds like a good technique. Will certainly consider it in the future. Thanks!

**Pull request merged**
