### PR TITLE
Fix version constraints for Corn 1.2.0.

### PR DESCRIPTION
**Pull request by Zimmi48**
See coq-community/corn#57.

### CODE REVIEW

**Comment by spitters** [comment]
[released] /home/travis/build/coq/opam-coq-archive/released/archives/coq-bignums.8.7.0+opam.tar.gz unavailable
[coq-bignums: from released] Repo archive not found
[coq-bignums: http] Command started
[released] /home/travis/build/coq/opam-coq-archive/released/archives/coq-corn.1.2.0+opam.tar.gz unavailable

**Comment by Zimmi48** [comment]
@spitters Sorry can you be more explicit regarding what you did that resulted in this error?
BTW, since it seems that the second commit in this PR is more complicated to get right that I initially thought, I will split this PR in two independent parts.

**Comment by spitters** [comment]
I don't think I changed anything in this commit. I was just reporting the Travis error message.

**Comment by Zimmi48** [comment]
OK thanks for the clarification.

**Comment by Zimmi48** [comment]
This one passed so no reason to delay further.

**Pull request merged**
