### PR TITLE
Coq: specify libdir and datadir

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes coq/coq#5782.

### CODE REVIEW

**Comment by RalfJung** [comment]
Unfortunately, the Coq 8.7.0 opam package now still uses the old opam file.

Also, I just remember that CoqIDE has its own opam file, I suppose it should get the same fix for consistency?

**Comment by herbelin** [comment]
@RalfJung:
> Also, I just remember that CoqIDE has its own opam file, I suppose it should get the same fix for consistency?

I guess so, even more that `-datadir` is for the purpose of CoqIDE.

I see other issues by the way:
- there are 8 relevant directories (`-bindir`, `-libdir`, `-configdir`, `-datadir`, `-mandir`, `-docdir`, `-emacslib`, `-coqdocdir`, as shown by `configure -h`); I believe that all of them should be given explicitly (or `configure` to provide an option to bypass the `win32` layout, as @gares judiciously proposed)
- the `-prefix prefix` is suspectful: shouldn't it be `-prefix %{prefix}%`?

**Comment by RalfJung** [comment]
> the -prefix prefix is suspectful: shouldn't it be -prefix %{prefix}%?

Notice the missing quotes. I think `prefix` and `"%{prefix}%"` are equivalent.

**Comment by RalfJung** [comment]
> I guess so, even more that -datadir is for the purpose of CoqIDE.

Actually there are now CoqIDE opam packages in core-dev, nor in extra-dev. Where would I have to send a PR so that the 8.7.1 release of CoqIDE uses a fixed opam file? And will coq.8.7.1 even be based on the opam files I patched here, or on others?

**Pull request merged**
