### PR TITLE
use opam 2

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by Zimmi48** [comment]
I'm not sure I understand what this does and the relation with what we discussed in #257.

**Comment by gares** [comment]
We use opam 2, so that we can access recent packages on the main opam repo. This repo, for now, is still in 1.2 format

**Comment by gares** [comment]
concrete example, the coq-elpi package cannot be built because elpi 1.1 is only available in the 2.0 repo

**Comment by gares** [comment]
adding the elpi pr on top of this commit in order to see if things work now

**Comment by gares** [comment]
OK, it worked, I've cleaned up the history and I'll merge after the last CI round

**Comment by gares** [comment]
@Zimmi48 does this make sense to you?

**Comment by Zimmi48** [comment]
It does. Thanks for the explanation.

**Pull request merged**
