### PR TITLE
coq-paco.8.6.0

### PR DESCRIPTION
**Pull request by liyishuai**

### CODE REVIEW

**Comment by gares** [comment]
Are you sure the maintainer field is correct?

**Comment by liyishuai** [comment]
I was copying the maintainer information of the [previous version](https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-paco/coq-paco.8.5.0/opam#L2). Shall I replace it with myself?

**Comment by gares** [comment]
@matejkosik are you OK with this update? Shall the maintainer be updated?

**Comment by matejkosik** [comment]
> Shall the maintainer be updated?

I think it is a good idea to let them know that their development is being released for Coq 8.6 as an OPAM package.

**Pull request merged**
