### PR TITLE
Symbol ':' replaced by '-' for Windows users

### PR DESCRIPTION
**Pull request by clarus**
This is a breaking change. I will wait till the end of the week to see if no one is opposed.

### CODE REVIEW

**Comment by gares** [comment]
I guess we should update, at the same time, also coq:shell (to coq-shell, but also its code to use- instead of : )

**Comment by clarus** [comment]
Yes. I also need to get ready to update the OPAM bench and the documentation I produced.

**Comment by herbelin** [comment]
Glad to see so much energy developed in making the opam thing working well. Do you intend to be in a strong breaking with the past or would you prefer to maintain some consistency with the existing. In the latter case, may I suggest that we take the opportunity of this needed change to adopt the convention of naming packages the same way as the users see them from the Require point of view, e.g. "Flocq", or "CoLoR".

**Comment by clarus** [comment]
My personal opinion is that this would cool to have this uniform naming scheme. However, I am afraid that:
* some users may not like it;
* some projects may not fit into this scheme (like CompCert);
* this may come to late.

Thus, I think we should allow letters in both lower and upper cases, and let users take the convention they prefer. This is also the less risky move from us.

**Comment by clarus** [comment]
Fixes #16

**Pull request merged**
