### PR TITLE
8.8.2 update

### PR DESCRIPTION
**Pull request by thery**

### CODE REVIEW

**Comment by Zimmi48** [comment]
Wait a minute. Our OPAM instructions are probably still targeting OPAM 1.2, but the package is (for now) only available for OPAM 2.0. We should probably expand this doc to say:
- if you are using OPAM 2.0...
- if you are using OPAM 1.2...

See also #257

**Comment by thery** [comment]
Is 8.8.2 avaiable in 1.2?

**Comment by Zimmi48** [comment]
No (see also the discussion on Coq-Club) because the offical OPAM 1.2 repository has been frozen. The plan to provide an OPAM 1.2-compatible package of Coq 8.8.2 (and following versions) is to do it through the opam-coq-archive. But nobody has done it yet (I don't want to do it myself as I'm not an OPAM user).

**Comment by thery** [comment]
This is a nightmare ;-)

**Pull request merged**
