### PR TITLE
[released] Add coq-bignums.8.13.0

### PR DESCRIPTION
**Pull request by erikmd**
href: https://github.com/coq/bignums/issues/52

### CODE REVIEW

**Comment by palmskog** [comment]
@erikmd the principle we have applied for 8.12 and other early packages for 8.13 is that unless a package builds with a released version of Coq, it should go in `extra-dev`. Then, once a supporting version of Coq is released, it can be moved from `extra-dev` to `released`. This ensures a package is fully tested when someone installs it with a Coq release.

**Comment by erikmd** [comment]
OK I didn't know what was the expected workflow; @gares had asked to tag bignums and other libs before coq itself, in order to test the main reverse dependencies in advance in a reproducible way; also @palmskog just to recall, coq-bignums.8.13+beta1 that is semantically equivalent to coq-bignums.8.13.0, is already in extra-dev.
But it makes sense to merge this PR only once it has been tested with coq.8.13.0 indeed!

**Comment by erikmd** [comment]
So can we get this PR as is and just merge it later on when coq.8.13.0 is released,
or would you prefer that I amend my PR so it is merged in advance in extra-dev ?

**Comment by palmskog** [comment]
@erikmd rather than having the PR open until the release of 8.13.0, my personal preference would be if you could switch the location to `extra-dev` and we can merge it. Then when 8.13.0 is released we can relocate all packages at once.

**Comment by erikmd** [comment]
@palmskog done. BTW did you or @gares document that "relocating process" somewhere? (it's not strictly needed of course, but it looks like a sensible workflow anyway)
also I'd bet having chosen for coq-bignums the same version scheme as that of Coq is a bit cumbersome (all the more as in the end, we notice that coq-bignums.8.13.0, tagged before, wasn't compatible with coq.8.13.0 :) but that's just the continuation of the initially chosen version naming convention for bignums, which was part of Coq beforehand.
So, if you document that workflow, bignums and its versioning should probably not be part of the workflow document I guess!

**Comment by erikmd** [comment]
Finally this comment is an opportunity to raise again the question that I had discussed at some point with @Zimmi48:
should one day bignums become part of the coq repository again? a bit like Ltac2 has been integrated (albeit both packages don't have the same impact of course…), anyway even if Coq's CI Overlay Workflow nicely takes into account the bignums-vs-coq compatibility, it would dramatically simplify the release workflow for this specific contrib. (which is also the only one to be part of Docker images of Coq, to preserve backward compatibility w.r.t. the time `BigZ` etc. were part of Coq)

**Comment by gares** [comment]
This relation is new to me, I did add a projects to track the PRs and then I guess I'll make the move myself.
For the next Coq release we shall find something better. It would be easy to have the CI script also load the core-dev/extra-dev repo when testing stuff in released, but the policy is that released should be "self contained"...

My feeling is that betas are released versions. They are put in the -dev repo to avoid users installing it "by mistake" but they are not moving targets. I don't know if opam provides another "preference" mechanism other than "the most recent version".

**Comment by silene** [comment]
> I don't know if opam provides another "preference" mechanism other than "the most recent version".

There is the trick they are using for OCaml, which is to have a repository containing a single dummy package named `ocaml-beta` and then all the beta packages in the main repository depend on this package. So, if the users have not registered this special repository, they will be unable to install beta packages, despite them being available.

**Comment by palmskog** [comment]
Each year already has 4-6 regular Coq releases (two major releases, each with at least one minor). If we assume each beta is now a release, then this blows up to 6-8 releases per year that regular packages have to indicate compatibility with. To me, this provides no clear gain for Coq project maintainers with plenty of downsides.

Hence, I am against entangling betas with the `released` repo.

**Comment by gares** [comment]
I'm not following your count, I think we do 2 betas per year (one per major) no?

FTR: we now call it beta, but possibly the plan is to call it release-candidate next time, to stress that it won't change in breaking ways from there to the final. The time between the RC and the final is the time were package maintainers shall decide if they can just relax the upper bound or have to make a new release, or shout if something is broken.

I don't understand why one would need to bump compat twice, even today, but especially if we follow the plan above. Can you clarify you concern? (I too want no extra pain on contributors)

**Comment by palmskog** [comment]
8.10 had three betas and was only last year (2019). Historically, many betas have had show-stopping bugs and different behavior in tactics and other commands compared to releases, which if you go the "release candidate" route, project maintainers would have to figure out.

Here is a possible count for 2021:
- 8.13+beta2
- 8.13.0
- 8.13.1
- 8.13.2
- 8.14+beta1
- 8.14+beta2
- 8.14+beta3
- 8.14.0
- 8.14.1
- 8.14.2

@gares I'm not sure what you mean by "bump compat twice", but in my experience one can't trust that just because something works in a beta it will work in the released version.

**Comment by silene** [comment]
> - 8.14+beta1
> - 8.14+beta2
> - 8.14+beta3

As @gares said, Coq's core developers agreed that there would be no beta versions for Coq 8.14. And for the same reason, there will be no 8.13+beta2.

**Comment by palmskog** [comment]
If there will be no beta versions of 8.14 and later (or release candidates, which definitionally would be betas), why are we having this discussion? Then, we don't need to figure out any special solution for packages in `released` or for opam archive CI, etc., the solution here of moving from `extra-dev` to `released` will be a one-time thing.

**Comment by silene** [comment]
There will be no beta, but there will be a single release candidate, so that package maintainers have a few days/weeks to make sure their packages work, before the release is officially announced.

**Pull request merged**
