### PR TITLE
add coq-serapi.8.16+rc1+0.16.0

### PR DESCRIPTION
**Pull request by palmskog**
cc: @ejgallego @erikmd @MSoegtropIMC

### CODE REVIEW

**Review by erikmd — APPROVED** [review]

**Comment by erikmd** [comment]
Thanks @palmskog !

BTW @ejgallego, if I'm not mistaken, [Line 27 of `coq-serapi.opam`](https://github.com/ejgallego/coq-serapi/blob/8.16+rc1+0.16.0/coq-serapi.opam#L27) should be bumped in the branch of your tag `8.16+rc1+0.16.0`(?):

```
  "coq"                 { !pinned & >= "8.15" & < "8.16"     }
```

− But regarding this PR #2200, the patch is already OK, given @palmskog put [this on Line 27](https://github.com/coq/opam-coq-archive/pull/2200/files#diff-49a965e2fb68cc652b0c26ca8fa2d4c0cdaf98eec11deff3e92aedce225eff3eR27):

```
  "coq"                 {           >= "8.16" & < "8.17"     }
```

**Comment by palmskog** [comment]
I don't think there is any need to bump the tag just because the opam file in the source has the wrong requirements. However, I think this should be fixed for the final 8.16 release.

**Comment by erikmd** [comment]
Yes, that's what I meant: bumping the `"8.15"` **in the branch of the tag** but keep the tag as is.

**Comment by ejgallego** [comment]
Oh yes, sorry for the mess, SerAPI's CI uses `--ignore-constraints-on=coq`, I'm not sure why, that should be fixed !

**Comment by erikmd** [comment]
OK ! but no worries @ejgallego − as `opam` first looks at the opam repo spec, there's no real issue over there.
(actually the `coq-serapi.opam` in the upstream github repo is mostly useful for git-pinning… or for your CI :)

**Pull request merged**
