### PR TITLE
Added coq-fiat-crypto-with-bedrock

### PR DESCRIPTION
**Pull request by Alizter**
This is a version of fiat-crypto that also builds the files using bedrock.

Might need fixing, let's see how far it gets.

### CODE REVIEW

**Comment by clarus** [comment]
OK, I do not really understand the error message. Do you? If it works on your machine I guess we can add this package as this is a development package.

**Comment by Alizter** [comment]
@clarus I haven't been able to test it on my machine yet. I will try to fix this today.

**Comment by Alizter** [comment]
@clarus I think we are good to go.

**Comment by clarus** [comment]
OK top, merging!

**Pull request merged**
