### PR TITLE
Bump opam to 2.1.2

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by palmskog** [comment]
@gares is there anything fundamental preventing us from switching to opam 2.1.2? The main advantage I see is that we can set up automatic installation of system packages, like we [just did for Docker-Coq-Action](https://github.com/coq-community/docker-coq-action/commit/e8a69bdb47e9ca5f1b736a940ba3d8f3a21faa2e)

**Comment by gares** [comment]
all for it, but I did not investigate these failures

**Comment by silene** [comment]
"opam: --unlock-base was removed in version 2.1 of the opam CLI, but version 2.1 has been requested. Use --update-invariant instead or set OPAMCLI environment variable to 2.0."

**Comment by silene** [comment]
Note that there are actually three occurrences of `--unlock-base` (2 in `.gitlab-ci.yml` and 1 in `scripts/opam-coq-install-remove`).

**Comment by gares** [comment]
thanks

**Pull request merged**
