### PR TITLE
added Opam entry for coq-squiggle-eq

### PR DESCRIPTION
**Pull request by aa755**

### CODE REVIEW

**Comment by mattam82** [comment]
Hi Abishek, did you "opam lint" it?

**Comment by aa755** [comment]
Should I remove the warnings as well? Is there a comprehensive list of requirements for pull-requests like this one?

**Comment by mattam82** [comment]
Well, it's always better without warnings :) The install one just asks you
to split the build part in two,
the dev-repo one you can ignore. There's no comprehensive list AFAIK,
however "opam lint" catches
most things that can go wrong I think.
-- Matthieu

**Comment by aa755** [comment]
I will come back with a pull request once the library has matured. Thanks.

**Comment by mattam82** [comment]
Hmm, I think this version can be merged already, no?

**Comment by mattam82** [comment]
I'll test it right away.

**Comment by mattam82** [comment]
It works for me.

**Pull request merged**
