### PR TITLE
Package coq-tactician

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**

### CODE REVIEW

**Comment by gares** [comment]
Is the timeout expected? We cap to 3h by default, but we can lift that, see https://github.com/coq/opam-coq-archive#continuous-integration

What is fishy to me is that things did not timeout on other ocaml compilers, they took 50 minutes. Is there a known problem with 4.09?

**Comment by LasseBlaauwbroek** [comment]
Yes, this is expected. The builds with OCaml < 4.09 do not time out because most packages have a requirement for OCaml >= 4.08. The 'ocaml: any' build succeeds because it has a time limit of a day. So as far as I can tell everything is alright.

**Comment by silene** [comment]
What is the story with the standard library being recompiled? Should all the other user libraries be reinstalled or are the new `.vo` files compatible with the old developments?

**Comment by LasseBlaauwbroek** [comment]
Yes, everything needs to be recompiled. The coq-tactician package comes with a utility that helps users to do this. I'll show it during the demo I'm giving today. This situation is not ideal but it makes not sense to have two stdlibs installed because then all other packages also need to be installed twice.

Thanks for the merge btw.

**Comment by silene** [comment]
> Yes, everything needs to be recompiled.

Then it should certainly be written in the description. Because "exactly the same .vo files are installed" sounds like nothing needs to be recompiled.

**Comment by LasseBlaauwbroek** [comment]
Well, there is an "except ..." after that quote. The .vo files are fully compatible in principle. The reason recompilation is necessary is that the magic number changes and Coq therefore complains about "inconsistent assumptions".

But I can add the need for recompilation in the description (it is already stated as a post-compilation message).

**Comment by silene** [comment]
The post-compilation message only states that "in order to finish the process, you should run 'tactician recompile'". I don't expect users to understand that it means that all the user developments will be recompiled (or that they should). I am not even sure which one it is. Is `tactician recompile` uninstalling and reinstalling all the packages using Opam?

I wonder if it would not be better for `coq-tactician` to behave as the proposed `coq-native` package. In other words, `coq` would have an optional dependency on it, which would thus force Opam to recompile all the user libraries to be recompiled, when `coq-tactician` is installed (or removed).

**Comment by LasseBlaauwbroek** [comment]
>  Is tactician recompile uninstalling and reinstalling all the packages using Opam?

It recompiles all packages depending on Coq. But I'll indeed improve the messages and descriptions.

> I wonder if it would not be better for coq-tactician to behave as the proposed coq-native package.

That would certainly be a possibility I'm open to. (I assume you mean `coq-tactician-stdlib` and not `coq-tactician`.

**Comment by silene** [comment]
> I assume you mean `coq-tactician-stdlib` and not `coq-tactician`.

No, I meant `coq-tactician` (or some other package). With my suggestion, `coq-tactician-stdlib` would no longer exist because the Tactician-enabled standard library would just be provided by `coq` (as done today).

Obviously, this is a bit complicated, because `coq-tactician` needs to be installed before Coq itself. So, it really depends on how much of Coq it needs to do so. That is why the dependency might be on some other package rather than `coq-tactician` proper. Or perhaps the `{post}` dependency variable from Opam could be of use.

**Comment by LasseBlaauwbroek** [comment]
I see what you are getting at. I'll see if I can get something like that to work sometime.

However, for the existing releases of Coq, the situation will have to remain as is, unless the Coq team is willing to change the (optional) dependencies retroactively.

**Comment by silene** [comment]
> for the existing releases of Coq, the situation will have to remain as is

Sure. Moreover (but hopefully I am wrong), for the whole setup to work, we might need to split the `coq` package itself between `coq-base` (on which `coq-tactician` would depend) and `coq-stdlib` (which would optionally depend on `coq-tactician`). This would make it even more tedious to support existing releases.

Note that the name `coq-stdlib` above is just there for exposition. In practice, this package would certainly be called just `coq`, to preserve compatibility with all the existing uses.

**Pull request merged**
