### PR TITLE
`coq-mathcomp-apery` and `coq-prosa` conflict with `coq-mathcomp-word.2.0`

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**
Follow up on https://github.com/coq/opam-coq-archive/pull/2452.

Conflict for apery is here:
https://github.com/coq-community/apery/blob/4239449caf0e2d05bf36a4fb9c42c702b9b9df70/theories/rat_of_Z.v#L3
Conflict for prosa is here: https://gitlab.mpi-sws.org/RT-PROOFS/rt-proofs/-/blob/v0.5/model/priority/gel.v#L4

### CODE REVIEW

**Comment by silene** [comment]
I had missed it yesterday for #2452, but if I understand correctly, the conflict is not just with `coq-mathcomp-word` version 2.0, it also exists with any future release, since CoqWord will presumably stay in `mathcomp.word` for a long time.

**Comment by palmskog** [comment]
Can't we put the conflicts in the `coq-mathcomp-word.2.0` itself? Otherwise, this may become a maintenance nightmare as new versions of conflicting packages are released.

**Comment by silene** [comment]
Conflicts cannot be declared against ranges of versions, only against half-ranges or specific versions. (I suppose that is due to a limitation of Opam's constraint solver.) So, depending on the conflicting versions, moving everything to `coq-mathcomp-word` might make it even worse in the long run, maintenance-wise. But for now, it indeed seems like a good idea.

**Comment by LasseBlaauwbroek** [comment]
> I had missed it yesterday for #2452, but if I understand correctly, the conflict is not just with `coq-mathcomp-word` version 2.0, it also exists with any future release, since CoqWord will presumably stay in `mathcomp.word` for a long time.

I don't believe that will be the case. The problem is being resolved from several fronts:
- In `coq-mathcomp-word`: https://github.com/jasmin-lang/coqword/issues/15
- In the dev version of `coq-mathcomp-algebra-tactics` it is already resolved: https://github.com/math-comp/algebra-tactics/blob/fb87fb0434c17e825b22e3bac9904c8e4f6cd1c2/theories/ring.v#L5
- I opened a PR for `coq-mathcomp-apery`: https://github.com/coq-community/apery/pull/13
- I opened an issue for `coq-prosa`: https://gitlab.mpi-sws.org/RT-PROOFS/rt-proofs/-/issues/104

I moved all of the conflicts to `coq-mathcomp-word`. (Although I'm not sure if that's better.)

**Comment by silene** [comment]
> The problem is being resolved from several fronts

Among all these fronts, only one actually matters: https://github.com/jasmin-lang/coqword/issues/15. Until this one is fixed, any new version of `coq-mathcomp-word` will necessarily conflict with any old version of `coq-whatever`. And there does not seem to be any progress on that front.

**Comment by LasseBlaauwbroek** [comment]
I disagree. By patching `apery` and `prosa`, all of their future versions become compatible with every version of `word`. Conversely, by updating `word`, all it's future versions become compatible with every version of `apery` and `prosa`.

**Pull request merged**
