### PR TITLE
Equations 1.2beta packages for 8.8 and 8.9

### PR DESCRIPTION
**Pull request by mattam82**
Working with the recently released coq.8.9.0 package on the opam repository

### CODE REVIEW

**Comment by mattam82** [comment]
The linting fails because these are 1.2 opam files, the build fails because 8.8.dev fails to install. I'd rather have released packages be tested with released coq versions, here 8.8 is supposed to compile with 8.8.0/1/2 for example.@gares any idea what should we do here?

**Comment by gares** [comment]
The "problem" is here:
  https://github.com/coq/opam-coq-archive/blob/master/scripts/opam-coq-install-remove#L43
there is an heuristic that enables the dev repositories if the package name matches beta dev.
I think the intent was to say "if the package is for extra-dev then enable extra-dev and core-dev" but the current code does something silly IMO. Could you try patching that file (in this PR) to something like this (untested):
```
 case "$PKG_VERSION_DIR" in
    *core-dev*)
      echo Add dev repos
      opam repo add core-dev file://$PWD/core-dev >> $LOG
      opam update core-dev
    ;;
    *extra-dev*)
      echo Add dev repos
      opam repo add core-dev file://$PWD/core-dev >> $LOG
      opam repo add extra-dev file://$PWD/extra-dev >> $LOG
      opam update core-dev extra-dev
    ;;
esac
```

**Comment by gares** [comment]
This time the failure does not seem to be spurious (coq 8.8.2 was installed)

**Comment by mattam82** [comment]
@gares indeed, the script did the right thing. Looks like a List/CList confusion in ocaml 4.02.3, I'll investigate

**Comment by mattam82** [comment]
Yet another try with fixed packages. 8.9 succeeded already in the last run, at least!

**Comment by mattam82** [comment]
Now they both compile.

**Pull request merged**
