### PR TITLE
Package coq-simple-io.0.2

### PR DESCRIPTION
**Pull request by Lysxia**
### `coq-simple-io.0.2`

IO monad for Coq

---
* Homepage: https://github.com/Lysxia/coq-simple-io
* Source repo: https://github.com/Lysxia/coq-simple-io.git
* Bug tracker: https://github.com/Lysxia/coq-simple-io/issues

---
### opam-lint failures
- **WARNING** 97 long description unspecified

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by Lysxia** [comment]
ugh, this appears to be put in the wrong place by opam-publish.

**Comment by Lysxia** [comment]
Now that's better.

**Comment by gares** [comment]
Could you make the description, well, more descriptive? For example I see you use the extraction keyword, so maybe you could write about that.

**Comment by Lysxia** [comment]
Sure. Is this better?

**Comment by gares** [comment]
From the website:
This library provides tools to implement IO programs directly in Coq, in a similar style to Haskell. Facilities for formal verification are not included.

In my opinion at least the last sentence should be part of the description, since it is quite uncommon for a coq package to provide no support for formal verification.

**Comment by Lysxia** [comment]
Thanks for the feedback!

**Comment by gares** [comment]
looks like the checksum is wrong

**Comment by Lysxia** [comment]
Oops, I'm so sorry!

**Pull request merged**
