### PR TITLE
Update menhir constraint for compcert.dev

### PR DESCRIPTION
**Pull request by SkySkimmer**
cc @jhjourdan

### CODE REVIEW

**Comment by palmskog** [comment]
It looks like menhirlib is currently broken on Coq master. Please consider making an `extra-dev` package for menhirlib and then change this package to depend on that instead of a released version of menhirlib.

**Comment by SkySkimmer** [comment]
>It looks like menhirlib is currently broken on Coq master.

I don't understand, menhirlib isn't mentioned by the compcert opam file. How is it related?

**Comment by palmskog** [comment]
CompCert apparently bundles an outdated version of menhirlib that is not compatible with the indicated version of menhir. If CompCert stops the bundling and instead directly depends on a separate menhirlib package, it will work. That's what I meant.

**Comment by jhjourdan** [comment]
Bundling menhirlib and Flocq in Compcert is a deliberate, long-standing choice of CompCert's development team. The rationale is that it makes it simpler to compile and install without opam. I am afraid this decision will not be revised.

But anyway, this is not the point here, since the bundled version of menhirlib in CompCert is not outdated. It is exactly the same as the most recent standalone release.

The actual question here is what introduced the incompatibility which breaks menhirlib on Coq trunk, and whether it is legitimage. Let me investigate a bit more.

**Comment by jhjourdan** [comment]
See https://github.com/AbsInt/CompCert/pull/303 for a fix which should be integrated soon in CompCert. This should fix the CI of this PR.

**Comment by jhjourdan** [comment]
AbsInt/CompCert#303 has been merged. Could someone merge this or trigger CI again ?

**Pull request merged**
