### PR TITLE
[extra-dev] coq-lsp for Coq 8.17+rc1

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by palmskog** [comment]
@ejgallego just to double check, do you really want to use the `+v8.17` suffix? To my knowledge, all packages that use a Coq version suffix or prefix always use `+8.XY` (no `v`).

**Comment by palmskog** [comment]
Also, can you please remove the binary file?

**Comment by ejgallego** [comment]
Oh yes, thanks!

I actually tagged with `v8.17` in the coq-lsp repos, I guess it sounded more natural to me. Anyways, this should be done automatically instead of that. I'm not a fan of this versioning tricks but I don't know how to do better.

**Comment by ejgallego** [comment]
For example for SerAPI we do `coq_version+serapi_version`, however I feel that for coq-lsp the other scheme could be better. OMMV.

**Comment by palmskog** [comment]
@ejgallego if you actually support `master` continuously in the GitHub repo, maybe you want to add a Git-based `coq-lsp.dev` package to `extra-dev` as well? People might want to develop with coq-lsp on Coq `master`.

**Comment by ejgallego** [comment]
That's planned but not until we merge https://github.com/coq/coq/pull/16964

**Pull request merged**
