### PR TITLE
Add dev packages for coq-gappa and coq-interval

### PR DESCRIPTION
**Pull request by MSoegtropIMC**
This PR adds dev packages for coq-gappa and coq-interval.

@silene : FYI : this is required for the Coq Platform master branch.

It is an interesting question where the .dev package for gappa itself should be. As far as I can see the opam main repo doesn't have such a concept.

### CODE REVIEW

**Comment by palmskog** [comment]
We get similar problems here as in #1503. I think we should wait for a conclusion in that PR until merging.

**Comment by silene** [comment]
Please mark yourself as the maintainer of these packages. I do not want to have anything to do with packages in `extra-dev`. As Karl once said, "the main utility of extra-dev is that it documents (installation instructions for) many Coq projects which do not have regular (tarball) releases." This is certainly not the case of `coq-gappa` and `coq-interval`.

(I know I am marked as the maintainer of `coq-flocq.dev`, but that was done without my consent, and look how bit-rotten the package has become.)

Anyway, once you are the maintainer of these packages, you can handle the `gappa` dependency as you see fit.

**Comment by MSoegtropIMC** [comment]
@silne: sure, I will change this.

@palmskog: As discussed in zulip I will add the packages here.

**Comment by MSoegtropIMC** [comment]
@palmskog : the gappa opam file expects that CI calls opam depext. It is a rather involved business to install all the prerequisites of gappa, but this is well tested in the Coq Platform CI and also opam's CI (there is a non dev gappa package there).

So I would say this is a non-feature of the opam-coq-archive CI system that this fails.

**Comment by MSoegtropIMC** [comment]
@silene : if this is OK with you I can take over the maintainership of the flocq package in extra-dev. I would then delete the flocq.8.7.dev package (I guess for extra-dev it is OK to delete a package).

There is also a dev package for Coquelicot where the maintainer is Matej Košík from INRIA, but it doesn't look like he is still maintaining it (it has been created 2017). Since you are one of the authors, if this is OK with you I can also take this over.

As far as I can see there is no other package in extra-dev, where you are mentioned as maintainer or author.

**Comment by silene** [comment]
> if this is OK with you I can take over the maintainership of the flocq package in extra-dev

That is OK with me (and also for Coquelicot). Thanks.

**Comment by MSoegtropIMC** [comment]
Will redo this later.

**Pull request closed without merging**
