### PR TITLE
Equations v1.2.2 release

### PR DESCRIPTION
**Pull request by mattam82**
The 8.12 version has been tested with 8.12+beta1, I hope it's ok to put it here in released anticipating the 8.12 final version.

### CODE REVIEW

**Comment by mattam82** [comment]
The CI is not ready to accept this situation yet. I don't know if we should allow dependencies on core-dev, just accept to add "not yet" installable versions, or maybe first move the equations for 8.12 release to core-dev too and later on move it to released when 8.12 final lands.

**Comment by palmskog** [comment]
The method of first having a package in `extra-dev` and then moving it to `released` later was practiced by the MathComp team, in my view successfully. So please consider this as an option.

**Comment by mattam82** [comment]
Ok, I moved it.

**Comment by mattam82** [comment]
@palmskog better now :)

**Pull request merged**
