### PR TITLE
change the tag for the MathComp packages from 1.11.0+beta1 to 1.11+beta1

### PR DESCRIPTION
**Pull request by affeldt-aist**
This change follows a discussion that occurred on Zulip about the naming convention for tags.

### CODE REVIEW

**Comment by palmskog** [comment]
@affeldt-aist just a reminder that `coq-mathcomp-analysis.0.3.0` will cease to be installable after this PR is merged (since `coq-mathcomp-solvable.1.10+beta1` is below its floor of `coq-mathcomp-solvable.1.10.0`. Will you do a separate PR?

**Comment by CohenCyril** [comment]
I think the whole renaming should be done in a single PR for consistency (and testing)

**Comment by affeldt-aist** [comment]
@CohenCyril I took advantage of the fact that you are in this conversation to update other MathComp-dependent packages as well.

**Comment by affeldt-aist** [comment]
The checks seem to have failed because of timeouts. Is there a way to restart them?

**Comment by clarus** [comment]
If they are too many changes and feel this is fine, we can also merge. There is the https://coq-bench.github.io/ CI testing everything to eventually catch errors if there are some.

**Comment by affeldt-aist** [comment]
> If they are too many changes and feel this is fine, we can also merge.
> There is the https://coq-bench.github.io/ CI testing everything to
> eventually catch errors if there are some.

I have pushed force but still have timeouts. :-(

**Comment by clarus** [comment]
OK, so let's merge then.

**Pull request merged**
