### PR TITLE
Add coq-equations 8.7.dev package to extra-dev

### PR DESCRIPTION
**Pull request by mattam82**
This branch tracks the 8.7 branch of Coq.

### CODE REVIEW

**Comment by gares** [comment]
Compilation failed...

**Comment by mattam82** [comment]
Hmm, it's hard to see why from the logs. Could you make the script output the .err and .out files maybe? It works locally.

**Comment by gares** [comment]
Should be more verbose this time

**Comment by mattam82** [comment]
Apparently there's an error in the build script now

**Comment by mattam82** [comment]
Did you remove the compilation test from the script? It did catch an interesting incompatibility with 4.05.0 here.

**Pull request merged**
