### PR TITLE
[fiat-crypto] Also build some files to test printing time

### PR DESCRIPTION
**Pull request by JasonGross**
For the bench

See https://github.com/coq/coq/pull/982#issuecomment-364789352

### CODE REVIEW

**Comment by JasonGross** [comment]
@ejgallego I'm not really sure how to set that up in a nice way.  Hopefully soon fiat-crypto will move to a pipeline that's faster, and we can build more targets on opam, and I can set up a display target / project that's just for testing printing.  Alternatively, it might be useful to take the notation file and PHOAS syntax file from fiat-crypto, and just generate large terms in a systematic way, to print.

**Comment by ejgallego** [comment]
I understood you were kind of heavy users of printing to generate some primitives, if that's not the case not sure if it is worth it to spend time doing a custom thing for fiat-crypto as opposed to a more general printing bench.

**Comment by JasonGross** [comment]
We are heavy users, in that we have a ~6000 line file of `Notation`s generated by a Python script which use use to generate almost C code which spans a couple hundred lines (or possibly more, in some cases).  But we might be switching to generating strings, soon, rather than notations, in which case you should not rely on fiat-crypto to test notations.

However, I am strongly considering submitting something to Coq Workshop this summer along the lines of "How to coax Coq's printer into generating C code", and can probably make a few benchmarks as part of that.

**Comment by gares** [comment]
The build fails, see travis logs. It seems a fail is missing

**Comment by JasonGross** [comment]
The issue is that opam is not cloning submodules.  Do you happen to know how to fix this?

**Comment by gares** [comment]
Hum, in my projects it is the Makefile that does `git submodule --init ...`, why should opam do it?

**Comment by JasonGross** [comment]
@gares opam 2.0 will do it for us, but opam 1.2 won't.  (I think opam should do this because it is part of "checking out the git repo".)  In any case, I've updated this PR to explicitly update the submodules, so hopefully it'll work fine now.

**Comment by JasonGross** [comment]
This now seems to be blocked on https://github.com/coq/coq/issues/6830

**Comment by JasonGross** [comment]
However, assuming it builds on Linux, I'd like to get this merged; I believe the current package does not build on either Linux or Mac OS, because we do already use submodules, so this is strictly better.

**Comment by gares** [comment]
sorry for the delay

**Pull request merged**
