### PR TITLE
compilation with Coq 8.7

### PR DESCRIPTION
**Pull request by fblanqui**

### CODE REVIEW

**Comment by gares** [comment]
Travis gives an error, as well as opam lint:
  https://travis-ci.org/coq/opam-coq-archive/builds/300080416?utm_source=github_status&utm_medium=notification

In short, it seems the install/remove instructions are broken.

**Comment by fblanqui** [comment]
Hi Enrico. I forgot to add the dependency on bignums. It is fixed now.


Le 12/11/2017 à 08:57, Enrico a écrit :

**Comment by maximedenes** [comment]
Hello,

I think the history would deserve a bit of cleaning.

**Comment by fblanqui** [comment]
Hi Maxime. Sorry but I don't know how to do that. I'm not familiar with 
git as you can see... Should I redo a new pull request from a new clean 
repo?


Le 13/11/2017 à 09:38, Maxime Dénès a écrit :

**Comment by maximedenes** [comment]
You don't need to create a new pull request.

The first step is to clean the history on your local git branch, usually using the `git rebase -i` command (but that depends on the exact state of your branch, here you seem to have a merge commit, that is a bit suspicious, for instance).

Once the history is clean on your local branch, you can use `git push -f yourremote yourbranch` to overwrite the history shown in this PR, without recreating one.

Maybe you can get some assistance by a local git expert for the first step?

**Comment by gares** [comment]
subsumed by #224

**Pull request closed without merging**
