### PR TITLE
add coq-aac-tactics.8.13.1

### PR DESCRIPTION
**Pull request by palmskog**

### CODE REVIEW

**Comment by palmskog** [comment]
@MSoegtropIMC even though the bugfix is only for OCaml 4.12 and later, would be nice if this package could be in the next 8.13 platform: https://github.com/coq/opam-coq-archive/blob/ea1ebc079e17883006af17e9ed1b8ff0bf005ea9/released/packages/coq-aac-tactics/coq-aac-tactics.8.13.1/opam

**Comment by MSoegtropIMC** [comment]
Yes, it would make sense. I will ask the authors for their opinion.

**Comment by palmskog** [comment]
> I will ask the authors for their opinion.

@MSoegtropIMC not sure what you mean by "authors" here. I'm the sole maintainer (in  Coq-community) of aac-tactics, so you can view this as a request from the maintainer to include the package.

**Comment by MSoegtropIMC** [comment]
@palmskog: sorry, I still associate it with Fabian Kunze. I will update 8.13.

Will there also be an 8.14.1 (there is an 8.14.0 in extra-dev)?

**Comment by palmskog** [comment]
There won't be a 8.14.1 release unless some completely new bug shows up, since 8.14.0 already included all fixes that were applied to 8.13.1.

**Comment by MSoegtropIMC** [comment]
Ok, thanks. I updated 8.13 in PR https://github.com/coq/platform/pull/148.

**Pull request merged**
