### PR TITLE
Fix changed tar ball hashes for current coq-hammer packages

### PR DESCRIPTION
**Pull request by MSoegtropIMC**
This PR fixes the tar ball hashes for coq-hammer.

@palmskog : this breaks all build of Coq Platform

### CODE REVIEW

**Comment by gares** [comment]
Can you explain what happened? Did all tag change?

**Comment by MSoegtropIMC** [comment]
Interestingly they just changed back ...

**Comment by MSoegtropIMC** [comment]
Hmm no - actually when I download the tar files, I get a text file with content like:
```
the given path has multiple possibilities:
#<Git::Ref:0x00007f7b5070c8d0>,
#<Git::Ref:0x00007f7b50713748>
```

**Comment by MSoegtropIMC** [comment]
Hmm hmm hmm - it gets more weird every minute. Actually I downloaded the tar files twice and the hashes given in the text files are different each time ... Let me try a third time ...

**Comment by MSoegtropIMC** [comment]
Yes - it changes each time. If someone has a good idea about what this might be - please let me know.

**Comment by silene** [comment]
The URLs are slightly wrong. I suppose Github is being confused because the URLs point both to a tag and a branch. I suggest putting the correct URLs, which should look like `https://github.com/lukaszcz/coqhammer/archive/refs/tags/v1.3.2-coq8.15.tar.gz` (notice the `refs/tags` part of the URL).

**Comment by ybertot** [comment]
None of the other opam files in opam-coq-archive/released that use github has the refs/tags substring.  Why should it fail only here?

**Comment by MSoegtropIMC** [comment]
> Why should it fail only here?

and only since today morning for that matter.

Anyway I will change it and see what happens.

**Comment by palmskog** [comment]
My understanding is that `archive/...tar.gz` breaks only for CoqHammer, since the author of CoqHammer consistently makes branches with the same name as the repo tags.

Hence, it looks like most of the changes in this commit can be avoided by just inserting the `refs/tags` part after `archive`, which disambiguates the file.

**Comment by silene** [comment]
> None of the other opam files in opam-coq-archive/released that use github has the refs/tags substring. Why should it fail only here?

CoqHammer's tags and branches have the exact same names. Are there many other Opam packages that have the same property?

**Comment by MSoegtropIMC** [comment]
Thanks @silene - this seems to have fixed it. The hashes actually did not change.

**Pull request merged**
