### PR TITLE
Also release an 8.10 version of Equations 1.2 (using 8.10beta1)

### PR DESCRIPTION
**Pull request by mattam82**

### CODE REVIEW

**Comment by palmskog** [comment]
There's currently no 8.10 branch version of Coq in either the official OPAM repo or the `released` repo which this package targets, and there won't be until `8.10.0` is out. This means the `released` repo would no longer be standalone after merging this - a user would also need to add `core-dev` to get the package to build. Hence, I'm hesitant to merge this, but maybe you can comment @gares?

**Comment by mattam82** [comment]
Sorry, I should move it to extra-dev for the time being then.

**Comment by palmskog** [comment]
Yes, temporarily moving it to `extra-dev` would be great, then we can move it back when `8.10.0` is out.

In fact, I'm going to submit a package for `8.10+beta1` into `core-dev` as well.

**Comment by mattam82** [comment]
Done

**Pull request merged**
