### PR TITLE
QuickChick: update build parameter

### PR DESCRIPTION
**Pull request by liyishuai**

### CODE REVIEW

**Comment by gares** [comment]
@lemonidas can you comment on this? (your very recent PR does call the "plugin" target)

**Comment by lemonidas** [comment]
Not sure what this is. Let me check.

**Comment by liyishuai** [comment]
This is a fix to the build error in a previous version of QuickChick development branches, but I think it's still reasonable for now: `make all` should do all the compilation before installation.

**Comment by liyishuai** [comment]
Update: both release and dev versions compile everything in build stage. Future releases should also follow this.

**Comment by lemonidas** [comment]
To clarify: 
The original QuickChick release had a weird Makefile that mixed building and installation between the two targets (library + tool). This caused a bug in our development which was addressed (via a different solution) in the other pull request. This PR fixes the underlying issue to avoid similar issues in the future (for the dev builds) and to keep things cleaner in the released ones.

**Pull request merged**
