### PR TITLE
coqide: use 'version' to automatically depend on the matching coq version

### PR DESCRIPTION
**Pull request by RalfJung**
This also means we can just copy-paste that part in the future.

### CODE REVIEW

**Comment by gares** [comment]
I think the dev package is (already) broken, in particular you need lablgtk3.
The error is about `./configure`, so this part should also be fixed.

**Comment by RalfJung** [comment]
What is the fix though, which flags are needed now?

**Comment by gares** [comment]
I think `camlp5dir` is not accepted anymore (since we don't use camlp5 anymore)

**Comment by RalfJung** [comment]
That gets us a bit further but still fails...
```
# make --warn-undefined-variable --no-builtin-rules -f Makefile.build install-ide-bin install-ide-files install-ide-info install-ide-devfiles
# make[1]: Entering directory '/home/r/.opam/coq-test/.opam-switch/build/coqide.dev'
# install -d "/home/r/.opam/coq-test/bin"
# install bin/coqide "/home/r/.opam/coq-test/bin"
# install: cannot stat 'bin/coqide': No such file or directory
# make[1]: *** [Makefile.ide:203: install-ide-bin] Error 1
# make[1]: Leaving directory '/home/r/.opam/coq-test/.opam-switch/build/coqide.dev'
# make: *** [Makefile:176: submake] Error 2
```

**Comment by gares** [comment]
weird, here with the two commands to build I get
```
gares@ollypat:~/COQ/wt/master$ ls bin/
coqdep_boot  coqide  coqidetop  coqidetop.opt  coqpp  ocamllibdep
```

**Comment by gares** [comment]
Oh I see, you need to depend on `lablgtk3` (now you don't have the 3, so configure disables coqide)

**Comment by RalfJung** [comment]
Does `conf-gtksourceview` also need a 3 somewhere?

**Comment by RalfJung** [comment]
There's `conf-gtksourceview3` and `lablgtk3-gtksourceview3`, the latter depending on the former.

**Comment by RalfJung** [comment]
Yay, got it to build locally. :D  Let's see what CI says.

**Comment by RalfJung** [comment]
Looks like some Debian packages are missing:
```
[ERROR] The compilation of conf-gtk3 failed at "/usr/bin/pkg-config --short-errors --print-errors --atleast-version 3.18 gtk+-3.0".
[ERROR] The compilation of conf-gtksourceview3 failed at "/usr/bin/pkg-config --short-errors --print-errors gtksourceview-3.0".
```

**Comment by gares** [comment]
What a fight!
Add them here plz (as part of this PR) https://github.com/coq/opam-coq-archive/blob/master/.gitlab-ci.yml#L14

**Comment by RalfJung** [comment]
Yay, it's green. :D

**Pull request merged**
