### PR TITLE
FileSync: add SimpleIO requirement

### PR DESCRIPTION
**Pull request by liyishuai**

### CODE REVIEW

**Comment by gares** [comment]
Note that the dev package is used by CI if this pkg or any users of it is in the Coq platform. CC @MSoegtropIMC

**Comment by palmskog** [comment]
To my knowledge, this package is not in the Platform, and is not depended on by any package in the Platform. So fine by me to remove it if the author wants this (although it's generally useful to have git based packages in extra-dev, even if they are updated rarely).

**Comment by MSoegtropIMC** [comment]
SImplIO is in Coq Platform, but FileSync is not.

**Comment by palmskog** [comment]
@liyishuai looks like the dev package is not compatible with Coq master, do you still want me to merge?
```
File "./theories/CeresString.v", line 114, characters 0-70:
# Error: The default value for instance locality is currently "local" in a
# section and "global" otherwise, but is scheduled to change in a future
# release. For the time being, adding instances outside of sections without
# specifying an explicit locality attribute is therefore deprecated.
```

**Comment by liyishuai** [comment]
This is a Ceres issue. I'll fix it with Li-yao. Needn't block here.

**Pull request merged**
