### PR TITLE
initial opam packaging for coq-coqrel

### PR DESCRIPTION
**Pull request by vzaliva**
initial opam packaging for coq-coqrel.
(also see https://github.com/CertiKOS/coqrel/issues/11 )

### CODE REVIEW

**Comment by silene** [comment]
This looks fine globally, except for the documentation part. This is unfortunate since a lot of effort seems to have gone into writing a proper coqdoc documentation. Would it be possible to generate this documentation and host it somewhere?

**Comment by gares** [comment]
Given that the sources are on github, I suggest you host the doc on github.io.  IIRC you can just commit them on a special branch (gh-pages) or in master but under the docs/ directory.

**Comment by gares** [comment]
Anyway, the package seems fine so I'm merging it, but I encourage you to follow the advice of @silene !
Best,

**Comment by vzaliva** [comment]
I am not a developer, but I will rely your suggestions to @jeremie-koenig. Thanks!

I can add `make html` and `make install-doc` to the package, if that helps.

**Comment by herbelin** [comment]
It happens that we already have an infrastructure to automatically produce documentation for user packages. This infrastructure was used for the former [repository](http://www.lix.polytechnique.fr/coq/pylons/contribs/index) of so-called user contributions and I started to extend it a little bit so that it produces automatically gh-pages for github as mentioned by Enrico.

So, in theory, if a demand exists, this could be made into an option at submission time of opam packages that a documentation is automatically generated (including linking to other packages the given package depends on, etc.).

In its current layout, the documentation automatically produces looks like [this](http://pauillac.inria.fr/~herbelin/tmp//aac-tactics/v8.5/AACTactics.html) in its last version.

Not a lot of work is yet needed to make it fully working.

I would be glad also of the feedback and advices of a web specialist.

**Comment by vzaliva** [comment]
I think it would be very useful to have automatically generated documentation. Ideally, package docs should be linked from package info pages here: https://coq.inria.fr/opam/www/

**Comment by herbelin** [comment]
@vzaliva: The current status is that there is a combination of shell and python scripts to automatically generate github "gh-pages" web pages of the form indicated [here](http://pauillac.inria.fr/~herbelin/tmp//aac-tactics/v8.5/AACTactics.html) using a metadata file for the dependencies. To make this systematical, one would need a way to give these metadata, whether it is at submission time in the PR, or probably better in the opam file. So question 1 is to adopt a policy to give this metadata and to ask for automatic generation of the documentation.

A second question is what to do when linking to packages which provide source documentation on a web site of their own. Should we expect these packages to indicate in their opam file the correct link to pass to coqdoc to point to them or should we better regenerate the source documentation for these packages independently (and automatically).

The specialist is Enrico, so, I don't know what he would propose as a solution for questions 1 and 2.

Incidentally, there is also the question of the html style and layout for the web page. If know that some people are very sensitive to the "look" of pages, so if someone around is willing to help, that would be nice.

**Comment by jeremie-koenig** [comment]
I published some relevant links and the Coqdoc html at http://certikos.github.io/coqrel/.

**Pull request merged**
