### PR TITLE
Split coq dev package for 8.16

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**

### CODE REVIEW

**Comment by palmskog** [comment]
This is contrary to how the Coq 8.16+rc1 (and 8.16.0) package works. I think the `8.XY.dev` package should be like the RC and released packages as far as possible, so I'm personally against this PR. The split packages will only start to be used for Coq 8.17.

**Comment by palmskog** [comment]
Perhaps @gares can weigh in to break a possible deadlock?

**Comment by gares** [comment]
Fankly I don't understand what this Pr wants to do

**Comment by palmskog** [comment]
Maybe this is due to a misunderstanding. As far as I know, the changes to the Coq build system to split the `coq` package into `coq-stdlib` and friends is only present in the `master` branch and not in `v8.16`, which the `coq.8.16.dev` opam package points to. Hence the errors.

**Comment by LasseBlaauwbroek** [comment]
Ah, indeed. My memory failed me here, I thought that the final PR to split the packages had landed in 8.16. Apologies, I should have tested beforehand.

**Comment by Zimmi48** [comment]
This is indeed an 8.17 change only (https://github.com/coq/coq/pull/15560) and the `coq.dev` package is already split here. Feel free to test it and report feedback so that we can be confident that it works when preparing the packages for Coq 8.17+rc1 (no timeline yet) and 8.17.0.

**Pull request closed without merging**
