### PR TITLE
Add (new) dev package for coq-menhirlib

### PR DESCRIPTION
**Pull request by MSoegtropIMC**
This PR adds a dev (master) opam package for coq-menhirlib (it didn't have one as yet).

@fpottier : FYI : this is required for the Coq platform master build. It is a good question where the dev packages for menhir itself and the OCaml lib of menhir should go - the main opam repo doesn't seem to have the concept of dev packages.

The options I see are:
- put these dev packages into coq's extra-dev repo
- don't use a dev package but the latest release for these
- put the opam packages permanently into the Coq platform master branch opam patch repo

Strictly speaking I don't need menhir as dev/master, but I think it wouldn't hurt to test the master branch of these packages as well in Coq Platform master, so I would prefer the first or last option above, but I am open to use the release version of menhir.

### CODE REVIEW

**Comment by palmskog** [comment]
@MSoegtropIMC it looks to me like this package is unusable without `menhir.dev`, which is not available. This makes it very difficult to use this package for anything but CI testing. Maybe you could remove the conflict? The `extra-dev` repo has no handholding anyway.

**Comment by fpottier** [comment]
Hi, Michael, I did not know about these dev packages; what are they used for?

As Karl points out, the package `menhir.dev` doesn't exist; Karl's suggestion of removing the `conflict` line sounds good to me.

**Comment by MSoegtropIMC** [comment]
@palmskog : yes - sorry - an effect of more or less bulk merging from the Coq platform.

We had a discussion on Zulip where these packages should go - as concluded I will add them here as update to this PR. The packages should be usable then (I use them in Coq Platform master).

@fpottier : the dev packages are a convenient way to install the master version of a package via opam. This is mostly used for compatibility checks. The dev packages for menhir are required for the Coq Platform master branch which needs opam packages pointing to the master branch of all projects contained in the Coq Platform. Menhir is included in the Coq Platform since it was included in the Windows installer since 8.7 - I hope this is OK, I think we never discussed this. The main point of the master branch of Coq Platform is to stay informed early about emerging incompatibilities between packages in the Coq Platform. We don't expect or require it to work - we just want to know what works and what not, so that we can ping package maintainers early.

See (https://github.com/coq/platform) (https://github.com/coq/platform/blob/master/charter.md)

**Comment by MSoegtropIMC** [comment]
I added the 3 missing packages. This shoul dbe good to go now.

**Pull request merged**
