### PR TITLE
Release mathcomp-finmap 1.5.1

### PR DESCRIPTION
**Pull request by CohenCyril**

### CODE REVIEW

**Comment by chdoc** [comment]
@palmskog , can you merge this?

**Comment by gares** [comment]
May I ask why `< 8.13` on Coq? It is not customary for .v only projecs.

**Comment by gares** [comment]
The same also holds for https://github.com/coq/opam-coq-archive/pull/1492 and forces me to make an "overlay" in the coq platform.

**Comment by chdoc** [comment]
What is "customary" depends very much on who you ask. I'm all in favor of "upwards open" versioning, but @palmskog for instance insists on bounded versions for actively-maintained projects, making this the de-facto standard in coq-community projects.

**Comment by gares** [comment]
To more precise, pure .v projects depending on math-comp.
I too favor upper bounds, but this tag works with 8.13.

**Comment by palmskog** [comment]
@chdoc I don't think I've ever forced anyone to add an upper bound when they wanted otherwise. I think it's generally good to have upper bounds since things don't break uncontrollably, but from what I can remember I've never refused to merge an archive PR for this reason.

**Comment by palmskog** [comment]
For the record, I also favor having `< "8.14~"` as the upper bound for MathComp-related projects, which enables convenient alpha and beta testing of 8.13 on projects that depend on MathComp.

**Comment by chdoc** [comment]
@palmskog Sorry, maybe "insists" was too strong a wording. But I recall having had a discussion about "not ruling out configurations that might just work" vs "not having things break uncontrollably". And different people/communities make different choices here.

**Comment by chdoc** [comment]
> For the record, I also favor having `< "8.14~"` as the upper bound for MathComp 1.12.0 and closely related projects, which enables convenient alpha and beta testing of 8.13 on projects that depend on MathComp.

Good point, will do that for the upcoming `graph-theory` release (which was blocked on `finmap` being available)

**Comment by chdoc** [comment]
Or not? : `coq-hierarchy-builder >= 0.10 -> coq-elpi >= 1.5.0 -> coq (< 8.13~ | >= dev)` :disappointed:

**Pull request merged**
