### PR TITLE
Maintain VST releases

### PR DESCRIPTION
**Pull request by QinshiWang**
This PR contains:
1. Releasing VST 2.11;
2. Carving out a very useful library, Zlist, from VST, so it is now called `coq-vst-zlist`;
3. Removing useless dev versions and updating dev versions.

### CODE REVIEW

**Comment by palmskog** [comment]
cc: @MSoegtropIMC

**Comment by palmskog** [comment]
@MSoegtropIMC looks like there is some issue with `coq-compcert.3.11`:
```
# Testing Menhir... NOT FOUND
# Error: make sure Menhir version 20190626 or later is installed.
```

**Comment by palmskog** [comment]
@QinshiWang there is a lot going on in this PR, and we get CI timeouts. Any chance you could split off into new PRs:
- all `coq-vst-zlist` packages
- all `coq-vst` 2.11 packages

This should make it possible to see what is going wrong with each package (if anything).

**Comment by MSoegtropIMC** [comment]
@palmskog : coq-vst-zlist is a carve out of VST and VST 2.11 depends on it. That's the reason it is done in one PR. But of course one can first do the tlist package, merge it and then do the VST package (which usually times out on its own).

**Comment by QinshiWang** [comment]
@palmskog I created two PRs to instrument testing. So you can treat them as three sequential versions in the order of #2264, #2265, and #2260. But I have the same opinion as @MSoegtropIMC that the changes should be merged in a single PR.

**Comment by palmskog** [comment]
OK, so we seem to have figured out the problems in other PRs, so merging.

**Comment by QinshiWang** [comment]
@palmskog There is still a necessary change. This [error](https://github.com/coq/opam-coq-archive/pull/2265#issuecomment-1225621177) is related to a Makefile change, so we need to repackage the 2.11 release packages. So we need to change their checksums in this OPAM archive.

**Comment by QinshiWang** [comment]
@palmskog By the way, it seems `coq-vst` and `coq-vst-32`, and `coq-compcert` and `coq-compcert-32` are installed into the same positions, respectively? So are they actually conflicting? Just if you know it. Or maybe I should ask Prof. Andrew Appel

**Comment by palmskog** [comment]
@QinshiWang if a package and its `-32` variant indeed installs into the same directory, then there are two solutions:
- insert an opam `conflict` clause into one of the packages (ideally the `-32` variant)
- change or patch the `-32` package to make it install somewhere else

I was under the impression that @MSoegtropIMC had already set the `coq-compcert-32` package to install somewhere else, so we should check with him first. But you're free to insert the `conflict` into VST `-32` packages if you want, something like:
```
conflicts: [
  "coq-vst"
]
```

**Comment by silene** [comment]
At the very least, they have the same `logpath` tag. So, either the metadata is wrong, or they are indeed conflicting.

**Comment by MSoegtropIMC** [comment]
The 32 bit version installs under the same logpath, but into a completely different folder - outside of `coqc --where`. This is done so that one can compile the same code for 32 and 64 bit with just a change - Q options and without changing the require statements in each and every file.

I thought I documented this in both VST and CompCert (which does the same) but apparently I didn't or it got lost. For the instructions in CompCert see (https://github.com/coq/opam-coq-archive/blob/9d2937df72eb066103fb479158a49b048a058481/released/packages/coq-compcert-32/coq-compcert-32.3.11/opam#L40).

I think we should add similar instructions to VST.

Anyway it might make sense to set a different logpath. I don't think we have rules for handling this case as yet, but we could create them.

But to be sure, the 64 and 32 bit version of VST and CompCert can be installed in parallel and I do this regularly.

**Comment by MSoegtropIMC** [comment]
See also the discussion at (https://github.com/coq/coq/issues/12686).

**Comment by palmskog** [comment]
@MSoegtropIMC am I reading you right that the following is the current state of the `-32` packages:
- `coq-compcert` and `coq-compcert-32` always install into different directories for both releases and `dev` (no need to mark as conflicting)
- `coq-vst` and `coq-vst-32` *do not currently* install into different directories for releases and `dev`, but they *can* be modified to do this.

So what action points does this lead to? Should we mark all `coq-vst`/`coq-vst-32` as conflicting until we figure things out?

**Comment by MSoegtropIMC** [comment]
@palmskog: not quite. For all release version of VST and CompCert, 32 and 64 bit version (and cross variants for that matter) install into different folders. For dev I am not sure, but it should be the same.

It is only so that for VST this is not properly documented in the opam packages, for CompCert it is.

**Comment by MSoegtropIMC** [comment]
Please note that the default version - the one which installs under `$(coqc --where)/user-contrib` changed a while back. Originally it was the 32 bit version, but 3 or 4 versions back we changed the default to 64 bit.

**Comment by palmskog** [comment]
@MSoegtropIMC OK, so this is hardcoded in the VST `Makefile`?

So is then the bottom line that we:
1. remove the newly added `vst`/`vst-32` conflict
2. copy-paste the `coq-compcert-32` note on installation into `coq-vst-32` packages?

**Comment by MSoegtropIMC** [comment]
@palmskog : yes this is in the VST Makefile here (https://github.com/PrincetonUniversity/VST/blob/013640e9837c0cdbe03d38a7f318171b01aaca87/Makefile#L231).

And yes to my best knowledge this is what should be done.

We could discuss having some form of logpath notation for variants - since as @silene noted it is odd that two packages are compatible although they have the same logpath.

**Pull request merged**
