### PR TITLE
update Prosa package to v0.5 release

### PR DESCRIPTION
**Pull request by brandenburg**
Please integrate the latest release of the Prosa project. Thanks! 

CC: @proux01

### CODE REVIEW

**Comment by brandenburg** [comment]
Thanks, Pierre!

**Comment by brandenburg** [comment]
Uh, I'm confused. Why did you remove the updates to the `dev` package? Should that be a separate PR?

**Comment by proux01** [comment]
The dev package was apparently broken on Coq master. Let's first merge 0.5 for which CI is green. I'm opening a merge request on Prosa to fix compilation with Coq master and I'll then reopen a PR here with the dev package update.

**Comment by brandenburg** [comment]
Ah, ok, I see. Thanks!

**Pull request merged**
