### PR TITLE
coq-gappa 1.3.3

### PR DESCRIPTION
**Pull request by silene**
This commit also adds upper bounds on dependencies of older releases.

### CODE REVIEW

**Comment by gares** [comment]
The compilation error on OSX does not seem bogus... anything weird about the ./configure that fails to find Coq (if /bin/sh is not bash for example?)

**Comment by silene** [comment]
> anything weird about the ./configure that fails to find Coq

Nothing obvious to me; the detection code is almost the same as for Flocq, which does work fine according to the log. Here is the relevant code, in case it rings a bell to someone:

```
AC_ARG_VAR(COQBIN, [path to Coq executables [empty]])
if test ${COQBIN##*/}; then COQBIN=$COQBIN/; fi

AC_ARG_VAR(COQC, [Coq compiler command [coqc]])
if test ! "$COQC"; then COQC=`which ${COQBIN}coqc`; fi

# the code above is the same as for Flocq, the code below differs

coqc_version=[`$COQC -v | sed -n -e 's/^.*version \([0-9.]\+\).*$/\1/p'`]

AC_DEFUN([AX_VERSION_GE], [AS_VERSION_COMPARE([$1],[$2],[$4],[$3],[$3])])
AX_VERSION_GE([$coqc_version], [8.4],
  [ AC_MSG_RESULT([$COQC]) ],
  [ AC_MSG_RESULT([no])
    AC_MSG_ERROR([ *** Unable to find Coq (http://coq.inria.fr/)]) ])
```

**Comment by silene** [comment]
And just to be clear, the `configure` file works fine with `dash`, it does not need `bash`.

**Comment by gares** [comment]
I think `sed` on OSX is not the `sed` we all know...

I don't recall the exact differences, I'm afraid you'll have to look at something like

   https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed

In any case I'll accept this PR, the opam code is fine.

**Comment by silene** [comment]
> I think sed on OSX is not the sed we all know...

Good catch, according to your link, it seems that OSX' sed does not know about `\+`.

**Pull request merged**
