### PR TITLE
release MathComp-Analysis 0.4.0

### PR DESCRIPTION
**Pull request by affeldt-aist**

### CODE REVIEW

**Comment by affeldt-aist** [comment]
:-( I'll fix that tomorrow first thing in the morning. Thank you for the report.

**Comment by palmskog** [comment]
@affeldt-aist any news on incompatibility with HB 1.1 and below? Can we fix this package by just requiring `> 1.1`?

**Comment by affeldt-aist** [comment]
Indeed, MathComp-Anslysis requires HB to be >= 1.2.0. We are actually thinking of crafting a new release soon. That will fix the problem.

**Comment by affeldt-aist** [comment]
@palmskog I see you have fixed and merged. Sorry for not having been reactive enough. Thank you.

**Pull request merged**
