### PR TITLE
coq.dev: update ocaml dependency and camlp5 removal

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/coq/coq/issues/9050

### CODE REVIEW

**Comment by Zimmi48** [comment]
I'm not usually handling these PRs but it seems urgent enough.

**Comment by ejgallego** [comment]
Sorry this PR had some problems reported by the linter so it should be amended

**Comment by Zimmi48** [comment]
Note the linter failures: it would be nice to fix them in another PR:

```
error 32: Field 'ocaml-version:' and variable 'ocaml-version' are deprecated, use a dependency towards the 'ocaml' package instead for availability, and the 'ocaml:version' package variable for scripts
error 57: Synopsis and description must not be both empty
warning 58: Found `doc` variable, predefined one is `with-doc`
```

**Comment by Zimmi48** [comment]
Sorry @ejgallego but linter failures are usually non blocking: this PR is not the one that introduced them.

**Comment by RalfJung** [comment]
That sounds like opam2 lints to me?

**Comment by ejgallego** [comment]
Sure I didn't mean this PR to be held, but I'd be good to do a bit more of update

**Comment by Zimmi48** [comment]
>That sounds like opam2 lints to me?

That's right. CI is using opam2. #506 is about moving the dev packages to opam2 format BTW.

**Pull request merged**
