### PR TITLE
fix opam for infotheo 0.3.5

### PR DESCRIPTION
**Pull request by affeldt-aist**

### CODE REVIEW

**Comment by palmskog** [comment]
@affeldt-aist I just tested locally, and Infotheo 0.3.5 works just fine with Analysis 0.3.11, so the current change would needlessly constrain Infotheo 0.3.5.

What you probably want to do instead is to change Infotheo **0.3.4** to disallow Analysis **0.3.12**, i.e., change the old Infotheo to disallow the new Analysis ("inverse" of the current PR?)

**Comment by affeldt-aist** [comment]
Isn't infotheo 0.3.4 already disallowing analysis 0.3.12?

**Comment by palmskog** [comment]
You're right, it looks like you already addressed this in 52c51a703d385ac0f4e623e1aaaaac02ebd9343f and this change was not reflected in the [opam bench run](https://coq-bench.github.io/clean/Linux-x86_64-4.12.1-2.0.8/released/8.14.1/infotheo/0.3.4.html).

Sorry for the noise on Zulip then, I think we can just close this?

**Comment by affeldt-aist** [comment]
It sounds that we can close. No problem at all. Thank for your careful follow-up.

**Pull request closed without merging**
