### PR TITLE
Release coq-fcsl-pcm 1.8.0

### PR DESCRIPTION
**Pull request by aleksnanevski**

### CODE REVIEW

**Comment by palmskog** [comment]
@aleksnanevski since MathComp 1.17.0 was just released, maybe this could be compatible? Do you want to make an attempt to relax the MathComp bound to include 1.17.0, or should I merge?

**Comment by palmskog** [comment]
@aleksnanevski since MathComp 1.17.0 was just released, maybe this could be compatible? Do you want to make an attempt to relax the MathComp bound to include 1.17.0, or should I merge?

**Comment by clayrat** [comment]
Let us try to relax the bound first.

**Comment by aleksnanevski** [comment]
done

**Pull request merged**
