### PR TITLE
Add coq-equations.1.2+8.10

### PR DESCRIPTION
**Pull request by xuanruiqi**

### CODE REVIEW

**Comment by clarus** [comment]
For me this is OK. I wonder if there should be a `date:` field in the tags.

**Comment by xuanruiqi** [comment]
I'm not sure. I just copied the opam file for 1.2+8.9 and changed the version number and the checksum. The date wasn't there in that version, so maybe we should keep it as-is?

...of course, unless @mattam82 decides otherwise.

**Comment by clarus** [comment]
OK. For me it is fine.

**Comment by xuanruiqi** [comment]
It should be OK to merge it IMO

**Comment by clarus** [comment]
OK !

**Comment by mattam82** [comment]
That’s fine, thanks!

**Pull request merged**
