### PR TITLE
New release of TLC.

### PR DESCRIPTION
**Pull request by fpottier**
Adding compatibility with Coq 8.7.

### CODE REVIEW

**Comment by gares** [comment]
Sorry to write this comment only now.
Isn't the description of the package a bit too vague?

**Comment by gares** [comment]
I mean, I've no clue from the description if this package may solve my problems or not...
Does it provide theorems about lists? Tactics about sets?
(I know what TLC is, but a random user may have an hard time guessing)

**Comment by fpottier** [comment]
Hmm. I'll ask Arthur (@charguer) for a better one-line description.
That said, I don't think it's easy to describe this library in one line.

**Comment by fpottier** [comment]
The description of ssreflect is "The Small Scale Reflection extension" :-/

**Comment by CohenCyril** [comment]
@fpottier, this should be discussed in another thread, but I'm curious where you find this description. Indeed, everywhere I look I find this: https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-mathcomp-ssreflect/coq-mathcomp-ssreflect.1.6.4/descr

**Comment by fpottier** [comment]
@CohenCyril, hello Cyril! I've been looking at coq-ssreflect-1.5.0, not realizing that the latest package was renamed coq-mathcomp-ssreflect. The new description paragraph is indeed much better. That said, `opam list` still shows only the first line:
```
$ opam list "*ssreflect*"
# Available packages for 4.05.0:
coq-mathcomp-ssreflect  --  Small Scale Reflection
coq-ssreflect           --  The Small Scale Reflection extension.
```

**Comment by mattam82** [comment]
opam info gives the longer description I hope, and I suppose the archive at
Coq.inria.fr/opam does too.

**Comment by fpottier** [comment]
I have added a longer description of TLC as part of the package description.

**Comment by gares** [comment]
Much better now, I'll wait for travis to test the compilation and then merge.

**Pull request merged**
