### PR TITLE
Release of real closed

### PR DESCRIPTION
**Pull request by CohenCyril**

### CODE REVIEW

**Comment by silene** [comment]
Note that the `extra-dev` directory is using opam 2 format, which is slightly different from opam 1 format.

**Comment by CohenCyril** [comment]
@silene oh ok. Thanks

**Comment by CohenCyril** [comment]
@silene everthing is ok now :smile:

**Comment by gares** [comment]
This is the right PR. Did the attempt to submit a 1.2 format package fail CI or not?

**Comment by CohenCyril** [comment]
> This is the right PR. Did the attempt to submit a 1.2 format package fail CI or not?

yes it did, but it also complayed on the legit 1.2 format (for `released/`) that it lacked a synopsis or description (which I believe is not a requirement for 1.2 format...)

**Comment by gares** [comment]
> yes it did

Did it fail *compilation* or did it no? (I don't care about linting)

**Comment by CohenCyril** [comment]
I don't know...

**Pull request merged**
