### PR TITLE
package adapted to coquelicot3 and coq8.7

### PR DESCRIPTION
**Pull request by ybertot**
Actually the acceptability to coq8.7 has not been tested yet, this will depend the availability of
coquelicot 3.0.1 for that version of coq

### CODE REVIEW

**Comment by silene** [comment]
> this will depend the availability of coquelicot 3.0.1

Did you mean Interval? Because Coquelicot already works fine with Coq 8.7. For Interval, I still need to release a version that supports Coq 8.7 (once I have gotten my head around the best way of dealing with Bignums no longer being shipped). You can already use the `master` branch of Interval if you want support for Coq 8.7.

Also, I think you are being overly restrictive with the version numbers of the dependencies. For example, unless you are computing improper integrals, I don't understand why you would want to force Interval `> "3.1.1"`. Moreover, if you expect your development to work with Coq 8.7, I don't understand why you would want to force Interval `<= "3.2.0"`. So, all in all, it should be plain `>= "3"`.

Similarly, for Coquelicot, I don't see any reason not to use just `>= "3"`. Finally, for SSReflect, just having `>= "1.6"` should be fine; no point in forbidding version 1.6.2 for example.

**Comment by ybertot** [comment]
I am not sure I agree with open-ended dependencies.  I can probably assume that all modifications
of coquelicot within the "3" versions will consist in additions, so that accepting that range is safe.  For interval I agree with you, because it is probably a safe bet that the power of interval will only increase.  For ssreflect, it is not used directly by me, so the dependencies of Coquelicot will take precedence.

**Comment by silene** [comment]
> For ssreflect, it is not used directly by me, so the dependencies of Coquelicot will take precedence.

If you mean that you will remove the dependencies on SSReflect, then I agree it is the way to go.

**Comment by silene** [comment]
Note that version 1.1.9 of your development does not work with 8.7 either (due to the 8.7 changes to `IZR` and `BigZ`, hence PR ybertot/pi-agm#1, which supports both 8.5 and 8.7). So the dependency on Coq should be `"coq" {>= "8.6" & < "8.7"}`.

**Pull request merged**
