### PR TITLE
coq-elpi 1.8.1

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
This is blocked because coq 8.13+beta1 is in core-dev, while this package is in released.

@palmskog did this happen before? It seems we lack a way to have CI run but still to put the package in released/: it would be uninstallable using just released until 8.13.0 is out, but should not be a problem.

In previous released, did all packages with an ml part release after the final?

**Comment by palmskog** [comment]
@gares for the last release, any packages that depended on an unreleased Coq had to be first placed in `extra-dev', then transferred to `released` after the Coq release happened. I suggest you do the same here.

**Comment by gares** [comment]
Done thanks.
Is there a place were we keep the list of such packages?

**Comment by gares** [comment]
@palmskog I made a project to keep that list (FYI)

**Pull request merged**
