### PR TITLE
Release fcsl-pcm 1.0.0 for Coq 8.8

### PR DESCRIPTION
**Pull request by anton-trunov**

### CODE REVIEW

**Comment by gares** [comment]
LGTM but maybe you could just patch your previous package to say that it depends on mathcomp
>= 1.6 && <= 1.7 and Coq >= 8.6 && < 0.9~ . I'm fine with this package too, so just tell me what you prefer.

**Comment by anton-trunov** [comment]
@gares I changed it just as you and @palmskog suggested.
But I see the checks failed. Is it something I did?

**Comment by gares** [comment]
failures are spurious, when you push -f travis gets (sometimes) screwed

**Comment by anton-trunov** [comment]
@gares Thanks you!

**Pull request merged**
