### PR TITLE
Fix Coq version for coq-gappa.1.4.2

### PR DESCRIPTION
**Pull request by clarus**

### CODE REVIEW

**Comment by clarus** [comment]
@silene The latest version of `coq-gappa` seems to not be compatible with Coq 8.10: https://coq-bench.github.io/clean/Linux-x86_64-4.07.1-2.0.1/released/8.10.0/gappa/1.4.2.html (tested locally also).

**Comment by silene** [comment]
> The latest version of coq-gappa seems to not be compatible with Coq 8.10

It is compatible (this version was released specifically for 8.10). But there is some data race between OCaml and Camlp5 which I have yet to understand. This causes the Opam package to fail to build.

**Comment by silene** [comment]
Oops, sorry, I should have looked at your error message before replying. Your error is caused by a missing dependency on Camlp5. But, once it is fixed, the compilation still fails because of the aforementioned data race. That is why I have not yet updated the opam file.

**Comment by clarus** [comment]
OK!

**Pull request merged**
