### PR TITLE
Unified version of coq-paco

### PR DESCRIPTION
**Pull request by minkiminki**
as discussed in #219,
I updated packages to point [upstream](https://github.com/snu-sf/paco) and fixed the info.

### CODE REVIEW

**Comment by gares** [comment]
There is a build failure (on 8.5 at least)

**Comment by mattam82** [comment]
@minkiminki ping?

**Comment by minkiminki** [comment]
oh... I'll fix it soon

**Comment by minkiminki** [comment]
I agree. I fixed it.

**Comment by mattam82** [comment]
@gares I'm trying to relaunch the test-suite but apparently am failing. Any idea how to do it?

**Comment by gares** [comment]
I don't know why, but someone disabled travis. I've re-enabled it.

**Pull request merged**
