### PR TITLE
MetaCoq 1.0alpha2 for Coq 8.11 version

### PR DESCRIPTION
**Pull request by mattam82**
```
ci-skip: coq-metacoq-checker.1.0~alpha2+8.11 coq-metacoq-template.1.0~alpha2+8.11 coq-metacoq-pcuic.1.0~alpha2+8.11 coq-metacoq-safechecker.1.0~alpha2+8.11 coq-metacoq-erasure.1.0~alpha2+8.11 coq-metacoq-translations.1.0~alpha2+8.11
```

### CODE REVIEW

**Comment by palmskog** [comment]
@mattam82 this all looks good, but one thing I'm a bit wary about is the constraint `"ocaml" >= "4.07.1"`. Suppose Coq 8.11.1 gets support for OCaml 4.10.0 - do you think these packages will break or not with 4.10.0?

**Comment by mattam82** [comment]
I have absolutely no idea, we'll see and revise if necessary no?  Remember this is still alpha-stage quality :)

**Comment by palmskog** [comment]
OK, I see, sure. The cause of the CI failure seems to be that the package `coq-metacoq-translations` is not defined, can you please add that?

**Comment by palmskog** [comment]
It looks like the CI failures are now due to `coq-metacoq-template` missing a dependency on `coq-equations`.

**Comment by mattam82** [comment]
This works now, I've relaunched the 4.09.0 job which should succeed in ~1hr

**Pull request merged**
