### PR TITLE
Update CompCert packages.

### PR DESCRIPTION
**Pull request by jhjourdan**
CompCert is broken because of a recent change in Menhir.

This commit fixes the dependencies of already released versions of CompCert. The development version of CompCert is in the process of being fixed:

https://github.com/AbsInt/CompCert/pull/236

### CODE REVIEW

**Comment by ildyria** [comment]
Once the PR https://github.com/AbsInt/CompCert/pull/236 is accecpted, CI will still break:

`-coqdevdir` is not set as a result the install path will be default: `/usr/ ... `

Proposed PR to fix this problem: https://github.com/jhjourdan/opam-coq-archive/pull/1

**Comment by jhjourdan** [comment]
Thanks, merged.

**Comment by ildyria** [comment]
Would it be possible to run Travis again on that one now that https://github.com/AbsInt/CompCert/issues/234 has been fixed ?

**Comment by gares** [comment]
travis restarted

**Comment by jhjourdan** [comment]
I do not know how to interpret the failure of Travis. This seems unrelated to the content of the MR.

**Comment by gares** [comment]
it sometimes happens, I suspect it gets confused when one force-pushes while the job is running

**Comment by gares** [comment]
closing/reopening does sometime unscrew travis...

**Comment by maximedenes** [comment]
> it sometimes happens, I suspect it gets confused when one force-pushes while the job is running

Doesn't that launch a new Travis build?!

**Comment by gares** [comment]
yes, but it is not the same than clicking on "restart job" according to my experience I did that before and it did not pick up the right git commits).

**Comment by maximedenes** [comment]
You mean the new job doesn't pick up the new commits? I've never observed that on the Coq CI, so I'm skeptical. What does happen is that an outdated job does not find the commits it is looking for because the branch has been forced-pushed meanwhile. But then, there should be a new job in the queue already.

**Comment by gares** [comment]
I agree but it happens quite frequently here. If you want to look at the setup you are welcome to do it

**Comment by ildyria** [comment]
Error is as follow:
```
[coq-compcert: ./configure ia32-linux] Command started
+ ./configure "ia32-linux"
"-bindir" "/home/travis/opam-root/4.02.3/bin"
"-libdir" "/home/travis/opam-root/4.02.3/lib/compcert"
"-clightgen" (CWD=/home/travis/opam-root/4.02.3/build/coq-compcert.8.6.dev)
- Testing assembler support for CFI directives... yes
- Testing linker support for '-no-pie' / '-nopie' option... no
- Testing Coq... version 8.6.1 -- good!
- Testing OCaml... version 4.02.3 -- good!
- WARNING: some Intel processors of the Skylake and Kaby Lake generations
- have a hardware bug that can be triggered by this version of OCaml.
- To avoid this risk, it is recommended to use OCaml 4.05 or later.
- Testing OCaml .opt compilers... yes
- Testing Menhir... version 20180530 -- good!
- Testing GNU make... version 3.81 (command 'make') -- good!
- 
- CompCert configuration:
-     Target architecture........... x86
-     Hardware model................ 32sse2
-     Application binary interface.. standard
-     Endianness.................... little
-     OS and development env........ linux
-     C compiler.................... gcc -m32
-     C preprocessor................ gcc
-     Assembler..................... gcc
-     Assembler supports CFI........ true
-     Assembler for runtime lib..... gcc -m32 -c
-     Linker........................ gcc
-     Linker needs '-no-pie'........ false
-     Math library.................. -lm
-     Build command to use.......... make
-     Binaries installed in......... /home/travis/opam-root/4.02.3/bin
-     Runtime library provided...... true
-     Library files installed in.... /home/travis/opam-root/4.02.3/lib/compcert
-     Standard headers provided..... true
-     Standard headers installed in. /home/travis/opam-root/4.02.3/lib/compcert/include
-     Coq development installed in.. /usr/local/lib/compcert/coq
```

This configuration does not match the setting in `opam` :
https://github.com/coq/opam-coq-archive/pull/339/commits/f664a50198cabd15e8d644fe98c4184c3ae394fd

I don't know what is wrong but travis is not building on the correct commit.

**Comment by ildyria** [comment]
I think I found the problem it is in version `coq-compcert.8.6.dev` and `coq-compcert.8.7.dev` the opam file does not have the path specified.

**Comment by ildyria** [comment]
Proposed: https://github.com/jhjourdan/opam-coq-archive/pull/2

**Comment by jhjourdan** [comment]
Alright, now the Travis job does a timeout... That's probably because we updated several packages, and the Travis job tries to build all of them. I *could* split this MR into several other MR to make Travis happy. However, I would prefer not. Is there a way to increase the timeout ?

**Comment by gares** [comment]
No, it looks good to me.

**Pull request merged**
