### PR TITLE
re-enable 4.13 for bignums 8.14.0

### PR DESCRIPTION
**Pull request by palmskog**

### CODE REVIEW

**Comment by ejgallego** [comment]
CI is not going to test this works tho, right?

**Comment by clarus** [comment]
Indeed. We could also do a PR to add OCaml 4.13 in the tests, as the last version is 4.11.

**Comment by palmskog** [comment]
Fine by me to add a CI job for 4.13, but this was just to ensure the package is tested by the 4.13 opam bench.

**Comment by clarus** [comment]
Yes, OCaml 4.13 is now running.

**Comment by ejgallego** [comment]
Ok let's see, I did push a fix to opam's coq (8.14.0) but wasn't really tested so we'll see.

**Pull request merged**
