### PR TITLE
Use coq-packages.json to regenerate the static web page

### PR DESCRIPTION
**Pull request by silene**
They were incorrectly parsed as empty descriptions.

Edit: The comment above is no longer relevant since #1570 has been merged. This pull request now replaces the handcoded parser by the one from Opam, as used to generate `coq-packages.json`.

### CODE REVIEW

**Comment by gares** [comment]
I guess you had an example in mind.
Could you please check that this file is not OK? (search for your package, at least firefox makes it easy to browse the file)
https://coq.gitlab.io/-/opam-coq-archive/-/jobs/940811573/artifacts/coq-packages.json

**Review by gares — APPROVED** [review]

**Comment by palmskog** [comment]
@gares the `.json` file is the same as the deployed one - shouldn't this PR be orthogonal to what appears in the JSON?

**Comment by silene** [comment]
If I understand correctly, the `coq-packages.json` file is generated by `archive2web.ml`, while the `index.html` file is generated by `archive2web`. I only fixed the latter. The former does not need any fix, since it relies on Opam itself to parse the package descriptions.

That said, in the long run, I guess it would be better to also use `archive2web.ml` to generate `index.html`. This would at least make it possible to avoid all the parsing bugs.

**Comment by silene** [comment]
So, in the end, I did rewrite `archive2web` to use the json file as input. Here are a few comments about the commits:

1. unchanged, but no longer relevant, mostly useful to check the correctness of the whole pull request;
2. not relevant either, but as with commit 1, it was helpful to make sure the web page did not regress;
3. tag trimming in the json output (to avoid the regression fixed by #1509);
4. the core commit (notice that the `print_pkg` is completely unmodified);
5. script renaming, because it was really confusing.

@gares: The changes to `Makefile` needs to be double-checked, in particular to ensure that the server has the needed packages already (e.g., `dune`, `yojson`).

**Comment by gares** [comment]
Oh right, I guess we did not finish the job, we should definitely use the json file also for the index.html.
@maximedenes do recall what was the plan?

**Comment by gares** [comment]
Great, I'll look at it carefull. For now the only comment I have is the `require "json"` in the lua script, which I believe we could just vendor. I guess you are using `lua-json` on a Debian like distro, right?

**Comment by silene** [comment]
> I guess you are using `lua-json` on a Debian like distro, right?

Yes, I just used the first answer given by `apt-cache`. (In hindsight, I should have bothered a bit more looking for a json library. It would have saved me the pain of reading the source code to find the correct second argument to `json.decode`.)

**Comment by gares** [comment]
Hum, I start to think that the whole lua buseness is a leftover:
```
gares@ollypat:~/COQ/www$ git grep packages.js
pages/opam/www/index.html:<script src="/scripts/packages.js"></script>
scripts/packages.js:fetch('https://coq.inria.fr/opam/coq-packages.json')
```

**Comment by gares** [comment]
Maybe @maximedenes recall if the lua script is still used

**Comment by silene** [comment]
> To the best of my understanding, `scripts/packages.js` does what the lua script does (after your edits)

That would be surprising, because my previous pull requests (e.g., #1509) certainly had an effect on the webpage.

**Comment by silene** [comment]
Also, are you sure the `index.html` webpage you grepped for is the actual one? Because I do not find any trace of `packages.js`:

```console
$ curl https://coq.inria.fr/opam/www/index.html 2> /dev/null | grep '<script'
<script src="filter.js"/></script>
<script>filter_init();</script>
```

**Comment by gares** [comment]
At some point in time coq.inria.fr/opam/www was built from this repo by cron. Then, I believe, Maxime made this repo only generate the json file and move the index page to https://github.com/coq/www . I start to wonder if the cron is still running and is overwriting the index.html that is in the www repo (which would be a silly bug, and explain why you recent edit did something in the first place).

**Comment by silene** [comment]
Okay, so the third commit of this pull request is even more relevant now. We can forget about the other commits, once the server mess is fixed.

**Comment by silene** [comment]
This pull request now just discards the handcoded parser and uses `coq-packages.json` instead. Its relevance depends on how long it takes to fix the server issue.

**Comment by silene** [comment]
The server has been fixed. (Hopefully we hunted down all the cron jobs.) So, closing. I will submit another pull request to clean all the now obsolete files.

**Pull request closed without merging**
