### PR TITLE
New releases and development versions of SMTCoq and Sniper

### PR DESCRIPTION
**Pull request by ckeller**

### CODE REVIEW

**Comment by ckeller** [comment]
Hi
The script (for instance https://gitlab.com/coq/opam-coq-archive/-/jobs/4359532059 l.2283) reports a failure in the installation of Coq itself.

**Comment by ppedrot** [comment]
The relevant erros in the log seem to indicate something went wrong with make install:
```
-> compiled  coq.8.14.dev
Processing 22/24: [coq: make install]
+ /usr/bin/make "install" (CWD=/builds/coq/opam-coq-archive/opam-root-4.11.2-2.1.2-sandbox/4.11.2/.opam-switch/build/coq.8.14.dev)
- /usr/bin/make --warn-undefined-variable --no-builtin-rules -f Makefile.build install
- make[1]: Entering directory '/builds/coq/opam-coq-archive/opam-root-4.11.2-2.1.2-sandbox/4.11.2/.opam-switch/build/coq.8.14.dev'
- DUNE      sources
- dune install --display quiet  --mandir=""/builds/coq/opam-coq-archive/opam-root-4.11.2-2.1.2-sandbox/4.11.2/man"" --prefix="/builds/coq/opam-coq-archive/opam-root-4.11.2-2.1.2-sandbox/4.11.2" coq-core
- File "opam-root-4.11.2-2.1.2-sandbox/4.11.2/bin/dune", line 1, characters 0-0:
- Error: Invalid dune file
- make[1]: *** [Makefile.install:56: install-dune] Error 1
- make[1]: Leaving directory '/builds/coq/opam-coq-archive/opam-root-4.11.2-2.1.2-sandbox/4.11.2/.opam-switch/build/coq.8.14.dev'
- make: *** [Makefile.make:122: submake] Error 2
```

**Comment by silene** [comment]
> `File "opam-root-4.11.2-2.1.2-sandbox/4.11.2/bin/dune", line 1, characters 0-0: Error: Invalid dune file`

This is a recurring bug. Dune mistakes its own binary executable for a Dune file, and thus fails at parsing it. I don't know what triggers this bug and how to work around it.

**Comment by palmskog** [comment]
@ckeller any chance you could break out the packages targeting `released` into a different PR? Usually the bug doesn't trigger for `released`-only packages.

**Comment by ckeller** [comment]
> @ckeller any chance you could break out the packages targeting `released` into a different PR? Usually the bug doesn't trigger for `released`-only packages.

Actually compilation for the release packages also failed. Maybe I can provide a PR for 8.13, 8.15 and 8.16?

**Comment by palmskog** [comment]
Any split of packages related to `released` into different PRs would help. I don't remember seeing the `dune` problem for any such package. Also, it will make problems with this PR easier to troubleshoot.

**Comment by ckeller** [comment]
I splitted into 4 PR: #2607 #2608 #2609 #2610

**Pull request closed without merging**
