### PR TITLE
Add OCaml 4.09.0 to the CI

### PR DESCRIPTION
**Pull request by clarus**

### CODE REVIEW

**Comment by clarus** [comment]
@gares @palmskog I you are OK with it I can merge. The idea is to add the new version of OCaml to prevent bugs such as https://github.com/coq/opam-coq-archive/issues/974 It may slow down the CI, but hopefully the computing power of GitLab will follow the number of OCaml releases.

**Comment by gares** [comment]
Should we remove 4.02?

**Comment by gares** [comment]
Coq requires 4.05 these days, so testing a PR against that is not very useful

**Comment by clarus** [comment]
OK, I removed OCaml 4.02 (still tested in https://coq-bench.github.io/ for the worst case).

**Comment by clarus** [comment]
OK thanks.

**Pull request merged**
