### PR TITLE
coq-fcsl-pcm dev depends on mathcomp dev

### PR DESCRIPTION
**Pull request by anton-trunov**
To use latest mathcomp features

### CODE REVIEW

**Comment by palmskog** [comment]
@anton-trunov when I test the latest SHA of fcsl-pcm locally with Coq 8.10+beta1 and MathComp 1.9.0, it works fine. Are you sure you want to rule out this combination even though it still works?

**Comment by anton-trunov** [comment]
Yes. It's just I haven't pushed the breaking changes yet. I didn't want to break fcsl-pcm's `dev` version.

**Comment by palmskog** [comment]
OK I see.

**Comment by anton-trunov** [comment]
Thank you!

**Pull request merged**
