### PR TITLE
Update Coq version requirement for ATBR

### PR DESCRIPTION
**Pull request by tchajed**
ATBR is now compatible with Coq v8.7 and v8.8.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Hi @tchajed, this PR seems to contradict the fact that you needed a PR to make this contrib compatible with 8.8. coq-atbr-8.5.0 is actually pinned to a specific version, not tracking the master branch of the contrib. So what would be actually needed is to create a new release (by copying the coq-atbr-8.5.0 directory in some other directory with a new version number and updating the `url` file.

BTW, if you are interested in this contrib, would you like to become its principal maintainer as part of coq-community? See https://github.com/coq-community/manifesto.

**Comment by tchajed** [comment]
Oh darn, I didn't pay enough attention. I guess disregard this, and I can't fix the opam install until ATBR gets a new v8.8 release.

As far as becoming the maintainer, sure, why not? I think I actually want [coq-contribs/relation-algebra](https://github.com/coq-contribs/relation-algebra), but this is also a nice result and I like the associated paper.

**Comment by Zimmi48** [comment]
>Oh darn, I didn't pay enough attention. I guess disregard this, and I can't fix the opam install until ATBR gets a new v8.8 release.

You can actually use a hash even when there is no tag. This is (I think) what has been done for most contribs until now.

>As far as becoming the maintainer, sure, why not? I think I actually want coq-contribs/relation-algebra, but this is also a nice result and I like the associated paper.

Great. Can I let you open an issue on https://github.com/coq-community/manifesto to track this?
You could also open one about relation-algebra and we could ping the original authors to know what they think (because IIUC they are still working on it on another repo somewhere...).

**Comment by tchajed** [comment]
@anton-trunov I meant "[Deciding Kleene Algebras in Coq](https://arxiv.org/abs/1105.4537)" from LMCS 2012.

**Comment by anton-trunov** [comment]
@tchajed Thank you

**Pull request closed without merging**
