### PR TITLE
Update coq-validsdp.dev

### PR DESCRIPTION
**Pull request by proux01**
ci-skip: coq-libvalidsdp.dev

### CODE REVIEW

**Comment by proux01** [comment]
@silene well, this still seems to first check coq-libvalidsdp.dev alone

BTW, definitely unrelated but what's that:
```
$ apt-get install libgtksourceview2.0-dev -y || true
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libgtksourceview2.0-dev
E: Couldn't find any package by glob 'libgtksourceview2.0-dev'
E: Couldn't find any package by regex 'libgtksourceview2.0-dev'
```

**Comment by silene** [comment]
My mistake. You need to put a space after the colon. (This could definitely be improved.)

**Comment by palmskog** [comment]
@proux01 doesn't look like the project is compatible with `coq.dev` due to lack of locality hints:
```
Error: The default value for instance locality is currently "local" in a
# section and "global" otherwise, but is scheduled to change in a future
# release.
```
Do you want to fix this or should I merge anyway? We have laxer standards for the `extra-dev` repo.

**Comment by proux01** [comment]
Upstream fixed, CI green

**Pull request merged**
