### PR TITLE
Add bignums 9.0.0

### PR DESCRIPTION
**Pull request by proux01**
Following https://github.com/coq-community/bignums/pull/74 after that zulip conversation https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Notation.20for.20Explicit.20Arrays

### CODE REVIEW

**Comment by palmskog** [comment]
Just wondering how these new package versions will be handled in the Coq Docker images and similar places. Will the `8.XY.Z` versions be pinned @erikmd? Otherwise, we may see opam trying to upgrade in every run.

**Comment by proux01** [comment]
Very good point. I unfortunately don't think pining is a very good solution as it would make any job requiring the new version fail. I guess the "best" solution would be to upgrade the images.

**Comment by erikmd** [comment]
> Will the 8.XY.Z versions be pinned @erikmd?

Maybe for some versions of coqorg/coq… given putting coq-bignums 9.0.0 in, say, coqorg/coq:8.13 would be a non backward compatible change.

On the other hand, I've heard from opam maintainers that keeping too many `<` constraints on dependencies is bad practice.

> I unfortunately don't think pining is a very good solution as it would make any job requiring the new version fail.

I'm unsure a third-party library for Coq < 8.17 would need to require Bignums 9.0.0, given there was only one release of Bignums, and 9.0.0 does not bring much (it only removes a notation)

So why not pinning Bignums 8.x for 8.13 ≤ Coq ≤ 8.16, and keeping Bignums 9.0.0+ for Coq ≥ 8.17 ?

Actually, I think we should also ask the opinion of the users that faced the notation incompatibility caused by Bignums 8.x → @proux01, could you contact them?

**Comment by proux01** [comment]
> Actually, I think we should also ask the opinion of the users who faced the notation incompatibility caused by Bignums 8.x → @proux01, could you contact them?

I can't find Quentin here, so asked on the Zulip thread, pointing here: https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Notation.20for.20Explicit.20Arrays

**Comment by proux01** [comment]
I'm still unconfortable with the pinning which can be an annoyance for users, so let's try to list the pros and cons of each solution:

* pinning:
  * pro: no recompilation ever triggered (except if the user exlicitly unpin)
  * pro: old versions get tested in CI
  * con: users needing the new version will need to explicitly unpin
  * con: declared compatibility with the new version will not be tested in CI (except if users explicitly unpin), this is arguably less an issue if we don't pin for 8.17 (at least once users test 8.17 in their CI) but looks like a major con for me

* updating:
  * pro: new version get tested in CI
  * pro: users not compatibl with the new version will realize they need to add an upper bound
  * con: old version doesn't get tested
  * con: some recompilation will be trigerred when installing packages with a (< 9) bound on bignums (although only bignums will be recompiled and this currently touches only the following packages: color, interval, coqeal and validsdp, all package with an already fairly large compilation time, thus recompiling bignums won't make a big difference) note that this will disappear with time as soon as these packages get released since their master branch already handles the new version
 
Considering this, I'm still leaning toward not pinning anything, and if possible updating the images, even if it's not a perfect solution.

**Comment by palmskog** [comment]
I don't have a strong view on this issue, since I don't really depend much on bignums in my projects. However, regardless of whether you choose to pin or not, it seems to me that we need to rebuild all official Docker images going back to Coq 8.13. That is, if we pin, the pin needs to be added, and if we don't pin, then the images need to switch to 9.0.0 to avoid "runtime rebuilds".

So regardless of pinning decision, I was hoping the Docker rebuilds could happen soon after this PR is merged.

**Comment by QuentinCanu** [comment]
Hello!
Currently, I have some compatibility issues that force me to keep my coq version to 8.16. I need the notation removal for writing arrays of rationals using `BigQ` and `PArray`. I don't mind pinning to a specific version of bignums, but I have no strong opinion on which updating solution would be the best.

**Comment by proux01** [comment]
I see some strange error with Coq 8.14 in those jobs: https://gitlab.com/coq/opam-coq-archive/-/jobs/3953652588
```Coq
[ERROR] The installation of coq failed at "make COQ_USE_DUNE= install".
#=== ERROR while installing coq.8.14.1 ========================================#
# context              2.1.2 | linux/x86_64 | ocaml-base-compiler.4.14.0 | [https://opam.ocaml.org#909af7f6](https://opam.ocaml.org/#909af7f6)
# path                 ~/opam-root-4.14.0-2.1.2-sandbox/4.14.0/.opam-switch/build/coq.8.14.1
# command              /usr/bin/make COQ_USE_DUNE= install
# exit-code            2
# env-file             ~/opam-root-4.14.0-2.1.2-sandbox/log/coq-48975-35d728.env
# output-file          ~/opam-root-4.14.0-2.1.2-sandbox/log/coq-48975-35d728.out
### output ###
# /usr/bin/make --warn-undefined-variable --no-builtin-rules -f Makefile.build install
# make[1]: Entering directory '/builds/coq/opam-coq-archive/opam-root-4.14.0-2.1.2-sandbox/4.14.0/.opam-switch/build/coq.8.14.1'
# DUNE      sources
# dune install --display quiet  --mandir=""/builds/coq/opam-coq-archive/opam-root-4.14.0-2.1.2-sandbox/4.14.0/man"" --prefix="/builds/coq/opam-coq-archive/opam-root-4.14.0-2.1.2-sandbox/4.14.0" coq-core
# File "opam-root-4.14.0-2.1.2-sandbox/4.14.0/bin/dune", line 1, characters 0-0:
# Error: Invalid dune file
```
does that ring a bell to anyone, maybe @ejgallego

**Comment by palmskog** [comment]
@erikmd thanks for the nice summary, I think this plan sounds good. However, I will let @proux01 do the merging here at his leisure. It's nice to hear the Docker pipeline automation handles the rebuilds.

**Comment by erikmd** [comment]
As mentioned earlier, was AFK - upto now. Will rebuild the images.

> But IMHO, we should announce from now on (in Discord/Coq-Club) that we plan to merge this https://github.com/coq/opam-coq-archive/pull/2505 which will lead to a non-backward-compatible change in coqorg/coq:{≥8.13} images, why this upgrade is necessary (maybe also take the opportunity to say that notations that start merely with [ … are more risky), and how to mitigate it for using an older bignums (basically by adding a constraint coq-bignums {< "9.0~"} in their opam file, similarly to [PR coq/opam-coq-archive#2512](https://github.com/coq/opam-coq-archive/pull/2512/files)).

@proux01, could you post some message on Coq Discourse ?

**Comment by palmskog** [comment]
Recall that you can post to Coq-Club and Discourse Announcements simultaneously via email: https://github.com/coq/coq/wiki/Discourse

**Comment by erikmd** [comment]
IIUC, @palmskog mean (as per https://github.com/coq/coq/wiki/Discourse#sending-new-messages-by-e-mail):

sending an e-mail to both `coq+using-coq@discoursemail.com, coq-club@inria.fr`

**Pull request merged**
